### ISSUE TITLE
Navigation source code?

### ISSUE THREAD

**Issue by yshi329** [ROBOTIS-GIT/turtlebot3#100]
Hi there, I am using turtlebot3 for navigation purpose. Which navigation algorithm is deployed in the demo? Is it possible to view the source code or customize it? If yes, which file should I look at? Thanks very much!

**Comment by routiful** [comment]
Hi @yshi329 :)

You can view a source code on [github](http://wiki.ros.org/navigation).

Thanks 
Darby

**Comment by yshi329** [comment]
Thank you!!

**Comment by routiful** [comment]
Your welcome!!
