### ISSUE TITLE
Faulty Odometry - The pose values published at startup are extremely large.

### ISSUE THREAD

**Issue by dlwlrma1516** [ROBOTIS-GIT/turtlebot3#1014]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [Y] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [Y] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [Y] Jetson AGX Xavier 

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [Y] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [Y] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    roslaunch turtlebot3_bringup turtlebot3_robot.launch

8. Copy and Paste the error messages on terminal.

    ![odom1](https://github.com/ROBOTIS-GIT/turtlebot3/assets/111411916/7efafc76-9a1b-460d-be74-fd5bc6992892)
    
    ![odom2](https://github.com/ROBOTIS-GIT/turtlebot3/assets/111411916/46aecc7c-38f4-4d90-9e03-5422b6c46fa4)

9. Please describe the issue in detail.

When I start the odometer, the X, Y, and Z values are extremely high and unstable, bouncing around between -5 to 5. Power cycling and re-flashing the OpenCR board have not resolved the issue, and I'm unsure why this problem is occurring. However, after moving the robot a short distance using roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch, the odometer values return to normal.

**Comment by sunghowoo** [comment]
@dlwlrma1516 Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
