### ISSUE TITLE
Coordinated control of the base and manipulator

### ISSUE THREAD

**Issue by shota0610** [ROBOTIS-GIT/turtlebot3#1020]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [○ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ○] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [○ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [○ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.
I am using turtlebot3 with openmanipulator "SARA" with ROS noetic in gazebo.
I wrote an inverse kinematics code in python that moves the arm to reach the target position.
With that code, only the arm moves, but the base does not move.
Openmanipulator "SARA" has 6 degrees of freedom, and assumes that the base is a prismatic joint and a revolute joint, and solves inverse kinematics as a mobile manipulator with a total of 8 degrees of freedom, but the base does not move.

I would like to perform coordinated control so that the base also moves when the end effector reaches the target position.

How can I move the base and arm at the same time?
Is there another way to move the base and arm at the same time?

Your help would be greatly appreciated.

Thank you.

**Comment by sunghowoo** [comment]
@shota0610 Thank you for sharing the details. It seems like you are referring to whole-body control, which involves coordinating both the base and arm as a mobile manipulator. While this is an advanced topic, it might be more appropriate to discuss it on the ROS forum or related communities that specialize in motion planning and whole-body control. They can provide more targeted support and examples for your use case. If you need further assistance with TurtleBot3-specific integration, feel free to reach out again. Thank you for your understanding!
