### ISSUE TITLE
Running TurtleBot3 deactivates the sound output device and video playback of Youtube

### ISSUE THREAD

**Issue by MithraGhlm** [ROBOTIS-GIT/turtlebot3#1024]
1. Which TurtleBot3 platform do you use?
    - Waffle

2. Which ROS is working with TurtleBot3?
    - ROS 2 Humble

7. Specify the commands or instructions to reproduce the issue.
    - $ ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py

8. Copy and Paste the error messages on the terminal.
    - I am not getting any errors from the Gazebo side. But certain things in my computer started malfunctioning.

9. Please describe the issue in detail.
   - I am using Gazebo 11.10.2 with Ros2 Humble with Ubuntu 22.04.4 on Docker.
When running Gazebo solely (e.i. nothing is spawned in Gazebo), everything is fine and there's no problem. But when I run Gazebo with Turtlebot3 spawned in it, the sound output device of the computer stops working. Also all the Youtube videos on Chrome freeze and I can not play them anymore. However, I can still browse websites.
When I close the Gazebo, everything goes back to normal again. 

Any help is highly appreciated.

**Comment by yun-goon** [comment]
Hi @MithraGhlm 

Please note that there are many possible configurations in virtual machine environments, so we are unable to provide in-depth technical support.

However, running Gazebo in Docker could potentially consume a lot of CPU and memory, which might be causing the sound output issues.

We recommend reaching out to the ROS forum for more accurate assistance. Thank you for your understanding.

**Comment by sunghowoo** [comment]
@MithraGhlm Please refer to @yun-goon  answer for initial guidance. This issue will be closed due to prolonged inactivity. If the problem persists, feel free to reopen it, and we will address it promptly. Thank you for your understanding!
