### ISSUE TITLE
Turtlebot velocity is not updating 

### ISSUE THREAD

**Issue by Faheemibrahim** [ROBOTIS-GIT/turtlebot3#1028]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?
    - [x] Waffle Pi

2. Which ROS is working with TurtleBot3?
    - [x] (ROS2 humble  hawksbill)

3. Which SBC(Single Board Computer) is working on TurtleBot3?
    - [x] Raspberry Pi 4 B
    

4. Which OS you installed on SBC?
    - [x] Ubuntu  Server 22.04.4 LTS (Jammy Jellyfish)

5. Which OS you installed on Remote PC?
 - [x] Ubuntu  Desktop 22.04.4 LTS (Jammy Jellyfish)

6. Specify the software and firmware version(Can be found from Bringup messages)
    - Software Version: 2.1.5 (TurtleBot3 ROS Packages)
    - Firmware Version: V230127R1 (opencr board)

7. Specify the commands or instructions to reproduce the issue.
     ros2 launch turtlebot3_bringup robot.launch.py
     ros2 run turtlebot3_teleop teleop_keyboard 
     ros2 topic list /joint_states
     ros2 topic echo /odom

8. Copy and Paste the error messages on terminal.

![image](https://github.com/user-attachments/assets/7488fa45-3f68-47c8-a137-9e975c1db7bc)

9. Please describe the issue in detail.
**Problem Description**

- When using teleoperation to control the robot, the / joint_states topic shows that the wheel velocities are correctly updating. However, the / odom topic and my custom odom subscriber do not reflect any changes in the robot's linear and angular velocities. This issue only occurs when running the robot in the real world; in simulation, the odometry updates correctly

**Comment by yigitboracagiran** [comment]
Can you share us the callback function?

**Comment by Faheemibrahim** [comment]
i have added the content  in these files 

**launch and yaml files** 
[launch_file.txt](https://github.com/user-attachments/files/16558214/launch_file.txt)
[waffle_pi_yaml.txt](https://github.com/user-attachments/files/16558215/waffle_pi_yaml.txt)

**.cpp files** 
* for the output you have asked 
[odomentry_cpp.txt](https://github.com/user-attachments/files/16558221/odomentry_cpp.txt)
[joint_state_cpp.txt](https://github.com/user-attachments/files/16558224/joint_state_cpp.txt)

* i have added the rest just incase 
[diff_drive_controller_cpp.txt](https://github.com/user-attachments/files/16558228/diff_drive_controller_cpp.txt)
[dynamixel_sdk_wrapper_cpp.txt](https://github.com/user-attachments/files/16558229/dynamixel_sdk_wrapper_cpp.txt)
[imu_cpp.txt](https://github.com/user-attachments/files/16558230/imu_cpp.txt)
[node_main_cpp.txt](https://github.com/user-attachments/files/16558231/node_main_cpp.txt)
[sensor_state_cpp.txt](https://github.com/user-attachments/files/16558232/sensor_state_cpp.txt)
[turtlebot3_cpp.txt](https://github.com/user-attachments/files/16558233/turtlebot3_cpp.txt)

Please let me know if you need anything else, and I really appreciate your help !!

**Comment by yigitboracagiran** [comment]
I didn't understand what you're trying to do with this. But did you try to download turtlebot3_simulation from [this address](https://github.com/ROBOTIS-GIT/turtlebot3_simulations) and launch it? Odom topic and your twist data most likely will come in simulation... After you complete this, we can go step by step...

**Comment by yigitboracagiran** [comment]
Don't forget to put this repository to your workspace build with `colcon build`

**Comment by Faheemibrahim** [comment]
I am working with a physical TurtleBot3 robot and have cloned the TurtleBot3 repository, specifically the release 2.1.5  https://github.com/ROBOTIS-GIT/turtlebot3/releases/tag/2.1.5  from GitHub, which is built for ROS 2 Humble. After cloning, I used colcon to build the workspace on the Raspberry Pi. To bring up the robot, I executed the following command on the Raspberry Pi  ros2 launch turtlebot3_bringup robot.launch.py

Then, from my laptop, I used the teleop package to control the robot. While the robot was moving, I monitored the odometry data by running: ros2 topic echo /odom but i dont see it updating the velocity values.

**Comment by yigitboracagiran** [comment]
Did you check the frames?

**Comment by Faheemibrahim** [comment]
[frames_2024-08-09_14.55.02.pdf](https://github.com/user-attachments/files/16560213/frames_2024-08-09_14.55.02.pdf)
yup heres an image

**Comment by yigitboracagiran** [comment]
I didn't work on physical turtlebot3, do you still need to export to turtlebot3 model? Maybe you exported the wrong one?

**Comment by Faheemibrahim** [comment]
No worries, I believe the turtlebot3 waffle_pi.Urdf is properly used when I launch the turtlebot_bringup. so I don’t think the issue is with it opening the wrong urdf. Could there be a problem with the urdf ?  The picture below shows the waffle_pi.urdf being used 
![image](https://github.com/user-attachments/assets/b184cbbd-6e3e-4fe8-9008-bc171a20dc2b)

**Comment by yigitboracagiran** [comment]
I see, what about coordinate information? Are they coming or not ( like velocity data ) with /odom topic? And what about other topics? For example is /cmd_vel coming true?

**Comment by Faheemibrahim** [comment]
For /odom only the linear and angular velocity does not update but the coordinates update normally. And /cmd_vel is updating normally 
![Uploading image.jpg…]()

**Comment by Faheemibrahim** [comment]
The topic updates the the Linear twist and angular twist but the covariance is not updating. Will that be an issue if I use slam or nav2 ? and yes the /cmd_vel updates perfectly 
![image](https://github.com/user-attachments/assets/c444da0f-8e11-4081-983d-9a0383dbb3b9)

**Comment by yigitboracagiran** [comment]
Is /odom topic successfully publish the points?

**Comment by Faheemibrahim** [comment]
![image](https://github.com/user-attachments/assets/cb4a536f-4c40-409a-94ba-282bd763b7d5)
i zoomed out and found this is this how it should be updating ?

**Comment by yigitboracagiran** [comment]
Can you run `ros2 topic echo /odom --no-arr` in a new terminal next to your bringup and teleop nodes?
You can see the robot coordinates in the terminal?
Does it coming true or not?

**Comment by Faheemibrahim** [comment]
The coordinates are being published correctly but for some reason it starts at x =26 and y = 14 and the z updates properly.

**Comment by yigitboracagiran** [comment]
Can you reboot the robot?
If it still  starts at (26, 14) probably there are initialize values in a launch file. Can you check please?

**Comment by Faheemibrahim** [comment]
Rebooting it didn’t work physically turning it off and rebooting as you suggested worked. So is the odom fine ?

**Comment by yigitboracagiran** [comment]
Yes it's looks like it

**Comment by yigitboracagiran** [comment]
If odom coordinates and cmd_vel topics are coming true, linear and angular velocity in /odom should be fine also. Can't you use /cmd_vel in your code instead of using velocities in /odom for now until we figuring it out why the velocity data is coming wrong in /odom?

**Comment by Faheemibrahim** [comment]
Thank you for looking into this issue and being patient with me. may god bless you bro !!

**Comment by Faheemibrahim** [comment]
I thought odom data publishes everything. i just starting learning ros and was trying to make my own control system to experiment and I thought it was important for the odom to publish velocities and thought it wasn’t working.

**Comment by Faheemibrahim** [comment]
So odom only publishes coordinates ? And I use cmd_vel to track the velocity ?

**Comment by yigitboracagiran** [comment]
Exactly, best way to track velocity is subscribing velocity topic, in our case subscribing /cmd_vel

**Comment by Faheemibrahim** [comment]
Honestly man you’re the best thank you !!
