### ISSUE TITLE
Dynamixel xm430 doesn't work

### ISSUE THREAD

**Issue by MortezaHagh** [ROBOTIS-GIT/turtlebot3#109]
Hi,

we have a turtlebot3 robot. we assembled it. when we tested openCR with motors by pushing SW1 and SW2 push buttons, one of the motors didn't start turning.
what should we do ?

thanks

#question #dynamixel

**Comment by patrick95470** [comment]
HI

can you please sent us a picture of the connection wires ?

**Comment by robotpilot** [comment]
@MortezaHagh 
I'm sorry we don't have any action. Has this problem been resolved?

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while.
You can reopen this issue to show this issue to the users whenever.
Thanks. :)
