### ISSUE TITLE
Docking service

### ISSUE THREAD

**Issue by DSaMC** [ROBOTIS-GIT/turtlebot3#114]
Hi !

Any updates about a potential docking service?

Thanks!

**Comment by robotpilot** [comment]
@DSaMC 
Yes, we update it. the method has used the intensity and distance of laser distance sensor and a reflective tape. Check the documents, github and video below. :)
http://emanual.robotis.com/docs/en/platform/turtlebot3/applications/#automatic-parking
https://github.com/ROBOTIS-GIT/turtlebot3_applications
https://youtu.be/IRtdxoPo8Y8

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while.
You can reopen this issue to show this issue to the users whenever.
Thanks. :)
