### ISSUE TITLE
gazebo_ros_turtlebot3.cpp

### ISSUE THREAD

**Issue by RubensQRZ** [ROBOTIS-GIT/turtlebot3#115]
Hi, 

I would like to know why the gazebo_ros_turtlebot3.cpp, used to make the turtlebot3 autonomously navigates in the gazebo 3D, does not work with the real robot? I am using a turtlebot3 waffle. What changes do I have to make in the cpp code, or in the launch file, in order to make it works with the real robot?

What I mean is, if I run "roslaunch turtlebot3_gazebo turtlebot3_world.launch" and after that I run "roslaunch turtlebot3_gazebo turtlebot3_simulation.launch" the turtlebot3 navigates into the simulator. But, if I run "roscore" in the pc, and, after that, I run "roslaunch turtlebot3_bringup turtlebot3_robot.launch" in the turtlebot3 waffle, and then run "roslaunch turtlebot3_gazebo turtlebot3_simulation.launch" the turtlebot3 does not navegate, it just spins around itself. But, if i run "roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch", I can teleoperate the robot normaly using the keyboard.

Thanks.

**Comment by routiful** [comment]
Hi @RubensQRZ :)

turtlebot3_simulation node is example to be used in gazebo simulation.
If you want to use it real turtlebot3, you have to change some parameters in gazebo_ros_turtlebot3.cpp file.

Thanks
Darby

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while.
You can reopen this issue to show this issue to the users whenever.
Thanks. :)
