### ISSUE TITLE
Install Dependent Packages issue

### ISSUE THREAD

**Issue by patrick95470** [ROBOTIS-GIT/turtlebot3#118]
Hi

Due to uncorrect working of my TB3, I decided to remake from scratch  the installation .

thus after having installed ubuntu, installed ROS without problem

now I have a huge concern when it is time to Install Dependent Packages

the RPI freezes when I make the command  cd ~/catkin_ws && catkin_make

it stopsall the time at 94% like the picture is showing

if somebody has an idea of what's going wrong ?

![tb3](https://user-images.githubusercontent.com/13683996/35503314-0f5dc626-04e0-11e8-8942-a7a70585774b.JPG)

**Comment by patrick95470** [comment]
I just tried to delete all folders inside  catkin_ws/src

and retype all commands , but now the RPI stops at 64% !!!!???? :-(
![img_0613](https://user-images.githubusercontent.com/13683996/35504637-db134fa4-04e3-11e8-8f99-e748beb0fdca.JPG)

**Comment by patrick95470** [comment]
And redone the same, now it is stopping at 94%.....

**Comment by robotpilot** [comment]
Hi @patrick95470 
In your case, It would be nice to use the following command.

`cd ~/catkin_ws && catkin_make -j1`

**Comment by patrick95470** [comment]
Ok thx, works now

Can you please tell me more about this attribute ?

**Comment by robotpilot** [comment]
@patrick95470 
This is one option of the 'make' command:
"-j [N], --jobs [= N] Allow N jobs at once; infinite jobs with no arg". 

If you set the option to '-j1', only one process will be used when building. 

P.S. Building all of the TurtleBot packages on SBC(Raspberry Pi 3) seems pretty heavy. So, we will fix it soon. Thanks.
