### ISSUE TITLE
Update cause Raspberry Pi hangs/freezes

### ISSUE THREAD

**Issue by krizchong** [ROBOTIS-GIT/turtlebot3#127]
After i updated Turtlebot folder in my Raspberry Pi of TB3 Burger according to https://discourse.ros.org/t/turtlebot3-software-and-firmware-update-and-waffle-pi/3729, then when I try to catkin_make, Pi will just hang/freeze as
![img_20180208_144837](https://user-images.githubusercontent.com/13959787/35959861-54934a18-0ce2-11e8-9def-27fdf2002423.jpg)

Then I remove turtlebot3_patrol folder and catkin_make again, Pi always hangs/freezes at
![img_20180208_145557](https://user-images.githubusercontent.com/13959787/35959886-755add10-0ce2-11e8-925d-9e3b330f999f.jpg)

Pi will just hang/freeze and even the mouse pointer cannot move at all!
What was happened? Any advice?

**Comment by kijongGil** [comment]
Hi :)

I think that this problem is error about multi-core build.

Try catkin_make again with single-core.

**catkin_make -j1**

Thanks
Gilbert

**Comment by krizchong** [comment]
Thanks Gilbert for your reply.

Justnow I remove the Turtlebot3 folder then clone again from github, then it can compile without freezing.

I will try catkin_make -j1 next time if facing similar problem. Thank you ^^
