### ISSUE TITLE
 iBeacon

### ISSUE THREAD

**Issue by cyberobotics** [ROBOTIS-GIT/turtlebot3#138]
May I know if the TB3 Burger or Waffle Pi Bluetooth can work with the  iBeacon?  Any integration has been done with TB3 and  iBeacon?  Thanks.

**Comment by routiful** [comment]
Hello :)

Raspberry pi 3 attached in TB3 has **Bluetooth 4.1 Classic**. 
So you need to check whether iBeacon supports this version.

Thanks
Darby

**Comment by routiful** [comment]
This issue will be closed since there were no actions for a while.
You can reopen this issue to show this issue to the users whenever.
Thanks. :)
