### ISSUE TITLE
turtlebot3 build map with cartographer 

### ISSUE THREAD

**Issue by ncnynl** [ROBOTIS-GIT/turtlebot3#157]
I have tested turtlebot3 burger to use cartographer  , see : https://github.com/ncnynl/turbot3

**Comment by routiful** [comment]
Thanks you for your test :)

**Comment by ncnynl** [comment]
Now  have supported  building map with cartographer , hector,  karto   :)

**Comment by robotpilot** [comment]
Hi @ncnynl

Thank you for sharing your idea and code. I want to thank you for your contribution. I did several tests as you guided it and reflected it in our develop branch. I will release it in the next TurtleBot3 software release.
https://github.com/ROBOTIS-GIT/turtlebot3/tree/develop/turtlebot3_slam/launch

Thank you again.

**Comment by ncnynl** [comment]
@robotpilot   I have checked your code . good job.

**Comment by robotpilot** [comment]
Thank you very much. We will also apply it to the actual robot and release it this week.

**Comment by robotpilot** [comment]
Hi, @ncnynl !

We update and release new firmware (version 1.2.0) and new software (version 1.0.0) for users of TurtleBot3. :) 

Thank you to your contribution!

Please refer to the link below for details of this update.

https://discourse.ros.org/t/announcing-turtlebot3-software-v1-0-0-and-firmware-v1-2-0-update/4888
