### ISSUE TITLE
Launch may fail if I add any other USB Serial device to Turtlebot

### ISSUE THREAD

**Issue by KurtE** [ROBOTIS-GIT/turtlebot3#161]
As I mentioned up on the Robotis forum: http://en.robotis.com/service/forum_view.php?bbs_no=2406735&slg=&page_type=&mode=&submode=

I am looking into maybe adding one or more sensors to detect a drop (cliff) like the Turtblebot 2 has, such that my new Waffle Pi does not fall down stairs if I have it mapping some rooms. 

Can probably add sensor and code to openCR board, but might at least start out by using an Arduino or Teensy (PJRC) to connect the sensor(s) to.  

Now suppose I plug in a Teensy into the RPI and it gets assigned to: /dev/ttyACM0 
or some other Arduinos may be assigned to /dev/ttyUSB0  than the current launch files won't work as they assume that the OpenCR board has the address /dev/ttyACM0 and the LDR has /dev/ttyUSB0

Hopefully soon I will try adding a sensor, and to work around this I plan to use UDEV rules to give the different devices standard unique names, such that you are not at the mercy of the USB system deciding on what order it will enumerate (and assign) the device names. 

Example I already tried updating your udev rule file like: 

    #cp rules /etc/udev/rules.d/
    #sudo udevadm control --reload-rules
    #sudo udevadm trigger

    ATTRS{idVendor}=="0483" ATTRS{idProduct}=="5740", ENV{ID_MM_DEVICE_IGNORE}="1", MODE:="0666"
    ATTRS{idVendor}=="0483" ATTRS{idProduct}=="df11", MODE:="0666"
    ATTRS{idVendor}=="fff1" ATTRS{idProduct}=="ff48", ENV{ID_MM_DEVICE_IGNORE}="1", MODE:="0666"
    ATTRS{idVendor}=="10c4" ATTRS{idProduct}=="ea60", ENV{ID_MM_DEVICE_IGNORE}="1", MODE:="0666"
    SUBSYSTEM=="tty", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5740", SYMLINK+="ttyOPENCR"

I run this on my RPI and if I now look at the device list, you will see that the alias was created:

    kurt@raspi-turtle:/etc/udev/rules.d$ ls /dev/tty*
    /dev/tty    /dev/tty13  /dev/tty19  /dev/tty24  /dev/tty3   /dev/tty35  /dev/tty40  /dev/tty46  /dev/tty51  /dev/tty57  /dev/tty62    /dev/ttyAMA0
    /dev/tty0   /dev/tty14  /dev/tty2   /dev/tty25  /dev/tty30  /dev/tty36  /dev/tty41  /dev/tty47  /dev/tty52  /dev/tty58  /dev/tty63    /dev/ttyOPENCR
    /dev/tty1   /dev/tty15  /dev/tty20  /dev/tty26  /dev/tty31  /dev/tty37  /dev/tty42  /dev/tty48  /dev/tty53  /dev/tty59  /dev/tty7     /dev/ttyprintk
    /dev/tty10  /dev/tty16  /dev/tty21  /dev/tty27  /dev/tty32  /dev/tty38  /dev/tty43  /dev/tty49  /dev/tty54  /dev/tty6   /dev/tty8     /dev/ttyUSB0
    /dev/tty11  /dev/tty17  /dev/tty22  /dev/tty28  /dev/tty33  /dev/tty39  /dev/tty44  /dev/tty5   /dev/tty55   /dev/tty60  /dev/tty9
    /dev/tty12  /dev/tty18  /dev/tty23  /dev/tty29  /dev/tty34  /dev/tty4   /dev/tty45  /dev/tty50  /dev/tty56  /dev/tty61  /dev/ttyACM0
    kurt@raspi-turtle:/etc/udev/rules.d$ ls -l /dev/ttyOPENCR
    lrwxrwxrwx 1 root root 7 Mar 25 18:03 /dev/ttyOPENCR -> ttyACM0

Next up, is to edit the launch files to use the /dev/ttyOPENCR name instead of /dev/ttyACM0

And likewise make the same changes for the LDR to probably create the name /dev/dev/ttyLDR and change it's launch file(s) as well

**Comment by OpusK** [comment]
Hello, @KurtE 

Thanks for the good feedback :)

This issue has been reviewed in the past and is still under review.
If it is decided whether to apply, I will comment here.

**Comment by robotpilot** [comment]
@OpusK @KurtE
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
