### ISSUE TITLE
Path planning failing

### ISSUE THREAD

**Issue by allanis79** [ROBOTIS-GIT/turtlebot3#163]
Hello,

I collected a map using SLAM and I am using that map for turtlebot3 navigation using AMCL. Whenever i click on goal pose, the path planning algorithm is planning through grey area. I am not sure why this is happening. Can someone help me? 

Thanks

**Comment by allanis79** [comment]
@routiful can you help me?

**Comment by routiful** [comment]
Hi :)

Can you show me your problem by capture image?

**Comment by allanis79** [comment]
![34ceac2b-c8b8-4c34-85b1-833d3d1ca943](https://user-images.githubusercontent.com/15155403/38146171-abba23f2-3401-11e8-8ec2-b0b0a1c83588.jpeg)


You can see the black line (path planned), it's planning through the grey area, why is this happening?

**Comment by routiful** [comment]
Before you set goal pose by _2D Goal Nav_, you have to set initial pose of TB3 by _2D Pose Estimate_.

As shown in your capture, the scan data is not correctly on map. 
This is the reason why your TB3 is not working.

**Comment by allanis79** [comment]
I did set the initial position using 2D pose estimate. I think what you mentioned is not the reason. In first case, path planning algorithm shouldn't generate a path through grey area. 

This github repo is really broken. Lot's of things doesn't work properly.

**Comment by routiful** [comment]
Please show me how it works by capture your monitor.

I don't understand what you said 'broken'. This repo have been using many people in the world. 
Because of different development environment, a lot of problems are caused in any packages.

We are sorry for inconvenience. but we always ready for support.
If you have any problem to this repo you said 'broken', please feel free to open issue

Thanks a lot

**Comment by allanis79** [comment]
Hello,

I replaced all the parameters in TB3 with TB2 and it worked. I am not exactly sure what parameter is making the difference. 

Maybe this package worked for lot of people, but i wasn't able to get it running.

I am using a modified version of this file [https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_navigation/launch/amcl_demo.launch](url)

**Comment by routiful** [comment]
Thank you for sharing. I will review that parameters and engage it to improve our packages.
