### ISSUE TITLE
Navigation (turns around near to the goal) 

### ISSUE THREAD

**Issue by githubuser637** [ROBOTIS-GIT/turtlebot3#167]
If the robot is close to his goal it turns (sometimes several times) around the goal until it reaches it . I assume that it is related to the navigation parameters which you can edit easily. But it would take a lot of time to test all parameters and I think that I'm not the only one who faced to this issue.

I tested it with the exact same setup as described here: http://emanual.robotis.com/docs/en/platform/turtlebot3/navigation/#perform-navigation 
 
Here is a video which you published on YouTube in which the navigation works without any issues: https://www.youtube.com/watch?v=lOZmFC79S6A 
 
Therefore I guess that are maybe better navigation parameters which are not published yet. Can you please publish these parameter files or give me any suggestions how to solve this issue?

Attached you can find the video of this issue.
[VID_20180406_091545.zip](https://github.com/ROBOTIS-GIT/turtlebot3/files/1883199/VID_20180406_091545.zip)

**Comment by routiful** [comment]
Hi :)

You can find all parameters in [param folder](https://github.com/ROBOTIS-GIT/turtlebot3/tree/master/turtlebot3_navigation/param)

And if you want to solve the issue i recommend to modify [tolerance param](https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_navigation/param/dwa_local_planner_params.yaml#L24)

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
