### ISSUE TITLE
Turtlebot3 realsense r200 loses connection after bringup

### ISSUE THREAD

**Issue by zjurgen** [ROBOTIS-GIT/turtlebot3#184]
Hi everyone,
I am new to the Turtlebot3 and I am finding troubles with the Intel Realsense r200 camera.
When I launch on the robot roslaunch turtlebot3_bringup turtlebot3_realsense.launch or roslaunch realsense_camera r200_nodelet_default.launch the nodes run but unfortunately it just connects to the serial port without going on and then it loses the connection from the Wifi.
This is what is displayed.
Thank you in advance.

started roslaunch server http://192.168.137.208:42037/

SUMMARY
PARAMETERS

/camera/driver/base_frame_id: camera_link
/camera/driver/camera_type: R200
/camera/driver/color_fps: 30
/camera/driver/color_frame_id: camera_rgb_frame
/camera/driver/color_optical_frame_id: camera_rgb_optica...
/camera/driver/depth_frame_id: camera_depth_frame
/camera/driver/depth_optical_frame_id: camera_depth_opti...
/camera/driver/fisheye_frame_id: camera_fisheye_frame
/camera/driver/fisheye_optical_frame_id: camera_fisheye_op...
/camera/driver/imu_frame_id: camera_imu_frame
/camera/driver/imu_optical_frame_id: camera_imu_optica...
/camera/driver/ir2_frame_id: camera_ir2_frame
/camera/driver/ir2_optical_frame_id: camera_ir2_optica...
/camera/driver/ir_frame_id: camera_ir_frame
/camera/driver/ir_optical_frame_id: camera_ir_optical...
/camera/driver/mode: manual
/camera/driver/serial_no:
/camera/driver/usb_port_id:
/rosdistro: kinetic
/rosversion: 1.12.13
NODES
/camera/
driver (nodelet/nodelet)
nodelet_manager (nodelet/nodelet)

ROS_MASTER_URI=http://192.168.137.212:11311

process[camera/nodelet_manager-1]: started with pid [10915]
process[camera/driver-2]: started with pid [10916]
[ INFO] [1523953991.263169500]: Initializing nodelet with 4 worker threads.
Intel RealSense F200_camera ; 2.60.0.0
Intel RealSense LR200_camera ; 2.0.71.18
Intel RealSense R200_camera ; 1.0.72.06
Intel RealSense SR300_camera ; 3.10.10.0
Intel RealSense ZR300_adapter ; 1.29.0.0
Intel RealSense ZR300_camera ; 2.0.71.28
Intel RealSense ZR300_motion_module ; 1.25.0.0
[ INFO] [1523953992.400313536]: /camera/driver - Detected the following camera:
- Serial No: 2501011668, USB Port ID: 2-2-3, Name: Intel RealSense R200, Camera FW: 1.0.72.06
[ INFO] [1523953992.400609434]: /camera/driver - Connecting to camera with Serial No: 2501011668, USB Port ID: 2-2-3

**Comment by ROBOTIS-Leon** [comment]
@zjurgen 

Hi,

I think that you can get best answer from [https://github.com/intel-ros/realsense](https://github.com/intel-ros/realsense) issue bulletin.

If you have another questions, please ask without hesitation.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
