### ISSUE TITLE
Waffle Pi cannot map properly

### ISSUE THREAD

**Issue by Wegher** [ROBOTIS-GIT/turtlebot3#196]
Good afternoon,

After a few attempts, it was not possible to do the first mapping with Turtle Bot 3 Waffle Pi. It seems that the Robot loses its reference, and starts to map over the existing map, as you can see in the pictures below.

![screenshot from 2018-04-26 13-36-17](https://user-images.githubusercontent.com/36993172/39444081-de064324-4c8c-11e8-9e69-22a10679bf38.png)
![scrsht](https://user-images.githubusercontent.com/36993172/39444083-de5a8fa6-4c8c-11e8-90fb-02f2b8100f23.png)

Have you experienced something similar? I'd appreciate some help. Thank you!

**Comment by routiful** [comment]
Hi :)

When SLAM have been started, a map which you attached was created well. But the map was crashing when TB3 have been far away. 

I think you need to check `time sync` or wifi connection between RemotePC and TB3.
Below link might be help you.
http://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#timesync-between-turtlebot3-and-remotepc

Thanks

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
