### ISSUE TITLE
MX-28

### ISSUE THREAD

**Issue by Fricodelco** [ROBOTIS-GIT/turtlebot3#206]
ISSUE TEMPLATE ver. 0.0.1

1. Which TurtleBot3 you have?

- [ ] burger
- [ ] waffle
- [x] waffle pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

- [x] Raspberry Pi 3
- [ ] Intel Joule
- [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

- [x] Ubuntu MATE 16.04 or later
- [ ] Raspbian
- [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in RemotePC?

- [x] Ubuntu 16.04 LTS (Xenial Xerus)
- [ ] Ubuntu 18.04 LTS (Bionic Beaver)
- [ ] Linux Mint 18.X
- [ ] etc (PLEASE, WRITE DOWN YOUR OS)

3. Write down software version and firmware version
 - Firmware version : [1.1.2]
 

  
6. Please, describe detailedly what difficulty you are in 

- Hi, im russian student, and our team has a problem. How we can use dynamixel MX-28 motors with turtlebot and also can we even use it? or onle X-series could be used with Turtlebot?

**Comment by routiful** [comment]
Hi :) TB3 series are only compatible with Dynamixel X series. But if you were built manipulator to use MX series, you can refer to [OpenManipulator](https://github.com/ROBOTIS-GIT/open_manipulator)

Thanks

**Comment by Fricodelco** [comment]
So, mx28 support protocol 2.0 and 1.0 also mx28 and xl430 have similar characteristic, I ask because our xl430 was damaged, so we need to substitute them, or it’s terrible idea? Thank you for answer :)

**Comment by routiful** [comment]
Sorry to hear that. 
You can replace XL430 to MX-28(2.0). But it is not recommended due to hardware compatibility. You need to make other parts to assemble it to TB3. Furthermore Because MX-28(2.0) has different dimension compared by XL430, the height of TB3 has been changed.

I recommend buy one more XL430. It makes save your time.

Thanks

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
