### ISSUE TITLE
dynamixel Indicator light is red

### ISSUE THREAD

**Issue by ncnynl** [ROBOTIS-GIT/turtlebot3#210]
ISSUE TEMPLATE ver. 0.0.1

1. Which TurtleBot3 you have?

- [* ] burger
- [ ] waffle
- [ ] waffle pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

- [* ] Raspberry Pi 3
- [ ] Intel Joule
- [ ]  tx2

3. Which OS you installed in SBC?

- [ * ] Ubuntu MATE 16.04 or later
- [ ] Raspbian
- [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in RemotePC?

- [ *] Ubuntu 16.04 LTS (Xenial Xerus)
- [ ] Ubuntu 18.04 LTS (Bionic Beaver)
- [ ] Linux Mint 18.X
- [ ] etc (PLEASE, WRITE DOWN YOUR OS)

3. Write down software version and firmware version

 - Software version : [0.1.2]
 - Firmware version : [1.1.2]
 
4. Write down the commands you used in order

 [RemotePC] roscore
 [SBC] roslaunch turtlebot3_bringup turtlebot3_robot.launch
 [RemotePC] 
export TURTLEBOT3_MODEL=burger
roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=$HOME/map.yaml
rosrun rviz rviz -d `rospack find turtlebot3_navigation`/rviz/turtlebot3_nav.rviz
 
5. Copy and Paste your error message on terminal

6. Please, describe detailedly what difficulty you are in 

After running for a while, dynamixel xl430-w250-T On left will be red and cannot be moved。
After power off,  restart again ， it can work, but it will appear for some time

**Comment by kijongGil** [comment]
Hi ncnynl :)

First, check your DXL is working well. Could you move your TurtleBot3 with teleop?

**Comment by ncnynl** [comment]
@kijongGil  i can control tb3 to move through the keyboard ， it is working well  when i check independently.  This problem occurs when navigating, especially after multiple turns

**Comment by ncnynl** [comment]
@kijongGil   I  I'm going to replace  new DXL, brush the firmware, and then test it as a whole and check if it will appear repeatedly.  I also want to know when the DXL 's indicator will show red  ， blinking or bright

**Comment by kijongGil** [comment]
@ncnynl DLX's LED blinks when shutdown. Usually, it occurs when a strong torque of the motor is caught or the power is unstable. 
Check your cable and DLX's screw.
Thanks.

**Comment by zweistein** [comment]
@kijongGil our left wheel also shuts down frequently when max velocity is used. 
How can we reset the motor without powering off-on the whole system? 
What do you mean by checking the DLX's screw, if the wheel is loose?

**Comment by kijongGil** [comment]
@zweistein please refer to the  http://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#shutdown63 shown in the eManual. 
Tighten the screws too strongly the means burden the motor.

Thanks.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
