### ISSUE TITLE
roslaunch turtlebot3_slam turtlebot3_slam.launch slam_methods:=frontier_exploration fails

### ISSUE THREAD

**Issue by florianspy** [ROBOTIS-GIT/turtlebot3#213]
When starting roslaunch turtlebot3_slam turtlebot3_slam.launch slam_methods:=frontier_exploration the following error as shown in the screenshot occurs

![bildschirmfoto vom 2018-05-25 13-33-48](https://user-images.githubusercontent.com/39183098/40542450-824be2d0-6020-11e8-8ffc-18d89da7a0fd.png)

Going to /home/admini/catkin_ws/src/turtlebot3/turtlebot3_navigation/launch and renaming the file amcl.launch to amcl.launch.xml solves the issue

**Comment by robotpilot** [comment]
Yeah! You are right.
I've fixed what you said.
https://github.com/ROBOTIS-GIT/turtlebot3/blob/438d6ae877eb0f05b2129e77a1e1646d254e781d/turtlebot3_slam/launch/turtlebot3_frontier_exploration.launch#L15
Thank you for your consideration and supports. :+1:
