### ISSUE TITLE
OpenCR1.0 12v wire to board housing

### ISSUE THREAD

**Issue by jrjennings** [ROBOTIS-GIT/turtlebot3#214]
Hi, I am also looking for the terminal assembly to use on the 12V output supplied on the OpenCR1.0 board.  I found this datasheet http://pdf1.alldatasheet.com/datasheet-pdf/view/148129/YEONHO/SMH250.html but having problems finding a place to purchase it.  Can anyone point me in the right direction or a substitute maybe?

**Comment by ROBOTIS-Will** [comment]
@jrjennings 
Thank you for your inquiry.
Currently, the connector seems to be available in Korea via http://www.icbanq.com or http://www.devicemart.co.kr.
However, these sites are not English friendly, so I'll request sales department whether they can prepare these OpenCR parts.
Thank you.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
