### ISSUE TITLE
Referred by tech support, what is What is the minimum resolution of position X, Y that can be used in 2D point operation?

### ISSUE THREAD

**Issue by atgidev** [ROBOTIS-GIT/turtlebot3#225]
I am working on a project where a TurtleBot3 Burger will be moved to X Y coordinates, where those coordinates expressed in millimeters (mm).
 
The documentation for Point Operation  in the Example section of the e-manual may be what I need:
http://emanual.robotis.com/docs/en/platform/turtlebot3/example/#point-operation
 
(Note: I am ignoring Z coordinate in the remainder of this discussion, assume it will always have a value of 0)
 
When I look at the underlying source code, it appears the X Y coordinates are input in terms of meters:
https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_example/nodes/turtlebot3_pointop_key
 
My question is this:  what is the minimum resolution of X Y coordinates that can be used? For example, if I wanted to move to point (X=5mm, Y=5mm) from the origin, can that be input as (.005, .005) to the Point Operation  example?

**Comment by kijongGil** [comment]
Hi @atgidev :)
In this example, the minimum resolution is 0.05m. But, if you want to smaller resolution, you can change value in https://github.com/ROBOTIS-GIT/turtlebot3/blob/c2e272faf915e6cb416d50fa16ef971c6f402d9a/turtlebot3_example/nodes/turtlebot3_pointop_key#L73

Thanks.
Gilbert

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
