### ISSUE TITLE
TurtleBot3 LDS-01

### ISSUE THREAD

**Issue by garinalham** [ROBOTIS-GIT/turtlebot3#230]
Hi, I'm totally new to electronics and programming. My question is, is there any way to change pwm and/or the rpm of the LIDAR from the TurtleBot3 kit? Thank you.

**Comment by kijongGil** [comment]
Hi, @garinalham :)
Unfortunately, the speed of the LDS-01 can not be changed. Because this function is in firmware.
Could you tell me that why you want to change the speed of the LDS? I will help you if I can.

**Comment by garinalham** [comment]
Thanks for the respond! Yeah, I need to see how different scanrate affect the mapping result. Or do you have any alternative to this? Or should I just update the map_update_interval?

**Comment by kijongGil** [comment]
Yes... To control the map_update_interval is best way. But, now I have a idea. 
How about change map_metadata topic rate? This link will help you.
http://wiki.ros.org/gmapping

Thanks,
Gilbert

**Comment by garinalham** [comment]
Thanks! That was quick :). Can you elaborate what parameters is there in the map_metadata to tinker with? Perhaps a close replacement to the LIDARS rotational speed.

**Comment by kijongGil** [comment]
I am glad that the problem has been solved.
Please, let me know if you have any questions on this issues.

Thanks,
Gilbert

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
