### ISSUE TITLE
ERROR at roslaunch turtlebot3_bringup turtlebot3_remote.launch

### ISSUE THREAD

**Issue by oxidation99** [ROBOTIS-GIT/turtlebot3#238]
Hi 
When I use command roslaunch turtlebot3_bringup turtlebot3_remote.launch 
It not work as you can see at picture. I use turtlebot3 burger Ubuntu Mate 16.04.2(xenial) ROS kinetic on my pc I use ROS kinetic and install  Dependent ROS Packages.
How can I solved this problem.
Thank you

![screenshot from 2018-06-17 16-36-27](https://user-images.githubusercontent.com/40113004/41506744-d5243f0e-724d-11e8-88dc-42c050a8a685.png)

**Comment by robotpilot** [comment]
Hi @oxidation99,

The execution of turtlebot3_remote.launch should be done on your Remote PC, not on your TurtleBot3 PC (Raspberry Pi 3).
http://emanual.robotis.com/docs/en/platform/turtlebot3/bringup/#bringup-a-turtlebot3-burger

**Comment by oxidation99** [comment]
I run this command on my remote PC, not on Raspberry Pi and encounter the problem as pictured above.

**Comment by kijongGil** [comment]
Hi @oxidation99 :)

Could you install ROS?
Run the roscore and tell me the result.

`$ roscore`

**Comment by tunai** [comment]
Hi @oxidation99 

The launcher is looking for the model of your bot and failing to find it.

If this is the first time bringing up the robot, edit the "~/.bashrc" file on the remote PC and include this last line on it: “export TURTLEBOT3_MODEL = burger”. 

`$ sudo nano ~/.bashrc` (you can use your preferred text editor to do that, but let's consider the nano)

After the insertion of the new last line, hit CTRL+O to save the new file, and CTRL+X to exit (again, this is for the nano editor). Then, source the new bash file:

`$ source ~/.bashrc`

Now your workspace should know the model of your robot. **For every new terminal of the remote PC**, source the _devel_ folder in the catkin workspace:  

`$ source devel/setup.bash`

That should solve your problem.

**Comment by oxidation99** [comment]
Thank you for all the help.
Hi @kijongGil  
I install step by step ROS based on ROS.org/Tutorials website.
This picture show when I run roscore.
![screenshot from 2018-06-23 09-33-51](https://user-images.githubusercontent.com/40113004/41804876-9721277e-76c8-11e8-8007-44394a97ca30.png)

And when I run command roslaunch turtlebot3_bringup turtlebot3_remote.launch after I run roscore command. This error show in picture two.

![screenshot from 2018-06-23 09-42-47](https://user-images.githubusercontent.com/40113004/41804967-5130314a-76ca-11e8-9bd2-0a8e8f133aab.png)

**Comment by kijongGil** [comment]
Hi, @oxidation99. I'm sorry to reply late.
I think that your ROS installation have a problem.
Could you reinstall again?
