### ISSUE TITLE
Questions about base mesh files

### ISSUE THREAD

**Issue by Affonso-Gui** [ROBOTIS-GIT/turtlebot3#241]
Hello all,

I am doing some modifications on the Turtlebot3 Waffle frames to have space for some more sensors, as you can see below. I am working at a forked workspace on Onshape, and exporting it to use as a base mesh in the urdf.

![waffle_third](https://user-images.githubusercontent.com/20625381/41888480-a40227f2-7940-11e8-87f3-44b811e9e3a0.png)

So here are my questions:
-  Why are the meshes in this directory (e.g. `waffle_base.stl`) different from the ones exportable by the Onshape workspace (plates have less holes on it, etc)? Is it to make the files smaller? If so can we have access to editables for such plates?
- Is there any reasons for the files being .stl rather than .dae? When exporting from Onshape collada files appear to be smaller on size, preserve color and do not need the `scale` or `material` tags in the urdf.

**Comment by routiful** [comment]
Hi @Affonso-Gui :)

Thank you for your inquiry about TurtleBot3!
The origin of waffle_base has too many surface to load on Rviz or Gazebo even size is too big. So we uploaded modified waffle_base to Github. Unfortunately, we don't have provided editable version of it.

We already know .dae file is recommended by OSRF. We have a plan to support it near future.

Thanks

**Comment by Affonso-Gui** [comment]
Hello @routiful,

Thank you for clarifying. Looking forward for .dae support.

**Comment by routiful** [comment]
Nice. If you need any help, please feel free to open issue :)
