### ISSUE TITLE
realsense show nothing

### ISSUE THREAD

**Issue by jishaa** [ROBOTIS-GIT/turtlebot3#243]
Hello

my ros has some problem about realsense and camera
i succeeded slam operating by following emanual.
and try to using realsense but it have some problem.

first. host pc cannot get message type for each theora values.(like below error code)
second. when i scan topic by rqt about realsense_camera r200 nodelet default in waffle. it cannot appear these message.(i modify host ip and ran roscore, rqt, r200 nodelet at turtlebot3) 
and rqt_image_view show nothing
i applied some tips and opinion in internet but it was not successful.

TopicInfo.__init__(): topic "/camera/color/image_raw/theora": can not get message class for type "theora_image_transport/Packet"
TopicInfo.__init__(): topic "/camera/depth/image_raw/theora": can not get message class for type "theora_image_transport/Packet"
TopicInfo.__init__(): topic "/camera/ir/image_raw/theora": can not get message class for type "theora_image_transport/Packet"
TopicInfo.__init__(): topic "/camera/ir2/image_raw/theora": can not get message class for type "theora_image_transport/Packet"

**Comment by kijongGil** [comment]
Hi :) @jishaa

I tested realsense with TB3_waffle and it is working well.

I recommend that clearly remove your turtlebot3 pkgs, librealsense pkg and reinstall it.


http://emanual.robotis.com/docs/en/platform/turtlebot3/appendix_realsense/#intel-realsense-r200-for-turtlebot3

Thanks,
Gilbert.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
