### ISSUE TITLE
bringup checksum error and publish error (have update messages and firmware (shell scripted update, successful)and all others here said

### ISSUE THREAD

**Issue by angrysword** [ROBOTIS-GIT/turtlebot3#261]
ISSUE TEMPLATE ver. 0.1.0

1. Which TurtleBot3 you have?

    - [ X] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ X] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ X] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ X] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

3. Write down software version and firmware version

    - Software version: pc[1.12.12], turtlebot:[1.12.13]
    - Firmware version: [x.x.x]
 
4. Write down the commands you used in order

    [Remote PC] roscore
    [SBC] roslaunch turtlebot3_bringup turtlebot3_robot.launch

 
5. Copy and Paste your error message on terminal

  roslaunch turtlebot3_bringup turtlebot3_robot.launch
... logging to /home/pi/.ros/log/5be4951c-8ab2-11e8-9c27-000c29c08b01/roslaunch-raspberrypi-948.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.86.114:45935/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.12
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_lds/frame_id: odom
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://192.168.86.123:11311

process[turtlebot3_core-1]: started with pid [957]
process[turtlebot3_lds-2]: started with pid [958]
process[turtlebot3_diagnostics-3]: started with pid [959]
[INFO] [1531935538.696228]: ROS Serial Python Node
[INFO] [1531935538.849822]: Connecting to /dev/ttyACM0 at 115200 baud
[ERROR] [1531935541.137422]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f
[INFO] [1531935541.241896]: Note: publish buffer size is 1024 bytes
[INFO] [1531935541.249434]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531935541.303643]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531935541.335118]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1531935541.435899]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1531935541.552832]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1531935541.589040]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1531935541.637533]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1531936148.674006]: Setup publisher on /tf [tf/tfMessage]
**[ERROR] [1531936148.677219]: Lost sync with device, restarting...
[INFO] [1531936150.080580]: Calibration End
[ERROR] [1531936150.090864]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f**
[INFO] [1531936150.097261]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531936150.103793]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531936150.110164]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1531936150.116996]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1531936150.123319]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1531936150.130058]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1531936150.136468]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1531936150.143040]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1531936150.221866]: Note: subscribe buffer size is 1024 bytes
[INFO] [1531936150.224826]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
[INFO] [1531936150.305771]: Setup subscriber on sound [turtlebot3_msgs/Sound]
[INFO] [1531936150.430880]: Setup subscriber on motor_power [std_msgs/Bool]
[INFO] [1531936150.515101]: Setup subscriber on reset [std_msgs/Empty]
[ERROR] [1531936150.523830]: Tried to publish before configured, topic id 125
[ERROR] [1531936150.546721]: Mismatched protocol version in packet: lost sync or rosserial_python is from different ros release than the rosserial client
[INFO] [1531936150.549855]: Protocol version of client is unrecognized, expected Rev 1 (rosserial 0.5+)
[ERROR] [1531936150.616131]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f
[INFO] [1531936150.620164]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531936150.624245]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531936150.628227]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1531936150.632148]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1531936150.636193]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1531936150.640280]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1531936150.644530]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1531936150.648541]: Setup publisher on /tf [tf/tfMessage]
**[ERROR] [1531936150.661293]: Tried to publish before configured, topic id 125
[ERROR] [1531936150.719103]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f**
[INFO] [1531936150.723150]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531936150.727255]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531936150.731219]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1531936150.735344]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1531936150.739362]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1531936150.743644]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1531936150.747827]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1531936150.751858]: Setup publisher on /tf [tf/tfMessage]
**[ERROR] [1531936150.764619]: Tried to publish before configured, topic id 125
[ERROR] [1531936150.789046]: Tried to publish before configured, topic id 125
[ERROR] [1531936150.801361]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f**
[INFO] [1531936150.805413]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531936150.809365]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531936150.813659]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1531936150.817781]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1531936150.821967]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1531936150.826421]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1531936150.830538]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1531936150.834638]: Setup publisher on /tf [tf/tfMessage]
[ERROR] [1531936150.856827]: Tried to publish before configured, topic id 125
[ERROR] [1531936150.895145]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f
[INFO] [1531936150.899234]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531936150.903222]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531936150.907468]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1531936150.911602]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1531936150.915785]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1531936150.919759]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1531936150.924155]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1531936150.929945]: Setup publisher on /tf [tf/tfMessage]
**[ERROR] [1531936150.952582]: Tried to publish before configured, topic id 125
[ERROR] [1531936150.983277]: Tried to publish before configured, topic id 125
[ERROR] [1531936151.028752]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f**
[INFO] [1531936151.032938]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531936151.037027]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531936151.041006]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1531936151.045335]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1531936151.049706]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1531936151.054034]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1531936151.058484]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1531936151.062529]: Setup publisher on /tf [tf/tfMessage]
[ERROR] [1531936151.080259]: Tried to publish before configured, topic id 125
[ERROR] [1531936151.130999]: Tried to publish before configured, topic id 125
[ERROR] [1531936151.158246]: Tried to publish before configured, topic id 125
[ERROR] [1531936151.242376]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f
[INFO] [1531936151.246666]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531936151.250703]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531936151.254785]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1531936151.258764]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1531936151.262758]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1531936151.266865]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1531936151.270952]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1531936151.275000]: Setup publisher on /tf [tf/tfMessage]
[ERROR] [1531936151.306376]: Tried to publish before configured, topic id 125
[ERROR] [1531936151.330698]: Tried to publish before configured, topic id 125
[ERROR] [1531936151.339339]: Creation of publisher failed: Checksum does not match: d537ed7b8d95065b6c83830430b93911,7250c1dc0b61c4190e78f528f599285f
[INFO] [1531936151.343573]: Setup publisher on version_info [turtlebot3_msgs/VersionInfo]
[INFO] [1531936151.347560]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1531936151.351830]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]

**Comment by routiful** [comment]
Hi :)

Because the version between software and firmware has crashed, the error is occurred.
Update all the latest version and try launch again. I attached reference for installation instruction.

https://discourse.ros.org/t/announcing-turtlebot3-software-v1-0-0-and-firmware-v1-2-0-update/4888

**Comment by angrysword** [comment]
works like a charm. thank you very much.

**Comment by routiful** [comment]
Thanks, If you have any further questions, please feel free to open new issue page.

**Comment by tehnanmanna** [comment]
Hi,

though I have updated both software and firmware. I keep getting this error and then goes on in a loop.



roslaunch turtlebot3_bringup turtlebot3_robot.launch
... logging to /home/ubuntu/.ros/log/84f26836-9e9a-11eb-907b-c83dd43d6ebb/roslaunch-ubuntu-3151.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.0.3:38501/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://192.168.0.10:11311

process[turtlebot3_core-1]: started with pid [3160]
process[turtlebot3_lds-2]: started with pid [3161]
process[turtlebot3_diagnostics-3]: started with pid [3162]
[INFO] [1618567492.198433]: ROS Serial Python Node
[INFO] [1618567492.235257]: Connecting to /dev/ttyACM0 at 115200 baud
[INFO] [1618567494.356556]: Requesting topics...
[INFO] [1618567494.415237]: Note: publish buffer size is 1024 bytes
[INFO] [1618567494.423652]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1618567494.444378]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1618567495.035184]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1618567495.058103]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[ERROR] [1618567495.138581]: Creation of publisher failed: nav_msgs
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
[INFO] [1618567495.159651]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1618567495.179594]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1618567495.203986]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1618567498.116951]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1618567498.144873]: Note: subscribe buffer size is 1024 bytes
[INFO] [1618567498.155490]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
[INFO] [1618567498.181052]: Setup subscriber on sound [turtlebot3_msgs/Sound]
[INFO] [1618567498.207696]: Setup subscriber on motor_power [std_msgs/Bool]
[INFO] [1618567498.231552]: Setup subscriber on reset [std_msgs/Empty]
[INFO] [1618567498.255811]: Setup TF on Odometry [odom]
[INFO] [1618567498.266555]: Setup TF on IMU [imu_link]
[INFO] [1618567498.276867]: Setup TF on MagneticField [mag_link]
[INFO] [1618567498.286379]: Setup TF on JointState [base_link]
[INFO] [1618567498.302020]: --------------------------
[INFO] [1618567498.311337]: Connected to OpenCR board!
[INFO] [1618567498.320980]: This core(v1.2.2) is compatible with TB3 Burger
[INFO] [1618567498.334510]: --------------------------
[INFO] [1618567498.345775]: Start Calibration of Gyro
[INFO] [1618567500.818804]: Calibration End
[ERROR] [1618567500.841298]: Tried to publish before configured, topic id 129
[INFO] [1618567500.852438]: Requesting topics...
[INFO] [1618567500.869723]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1618567500.881724]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1618567500.899354]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1618567500.911653]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[ERROR] [1618567500.925351]: Creation of publisher failed: nav_msgs
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
[INFO] [1618567500.938445]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1618567500.951913]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1618567500.963860]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1618567500.975694]: Setup publisher on /tf [tf/tfMessage]
[ERROR] [1618567501.025573]: Tried to publish before configured, topic id 129
[INFO] [1618567501.032640]: Requesting topics...
[ERROR] [1618567501.104685]: Tried to publish before configured, topic id 129
[INFO] [1618567501.113985]: Requesting topics...
[ERROR] [1618567501.154256]: Tried to publish before configured, topic id 129
[INFO] [1618567501.163307]: Requesting topics...
[ERROR] [1618567501.199294]: Tried to publish before configured, topic id 129
[INFO] [1618567501.208329]: Requesting topics...
[INFO] [1618567501.290566]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1618567501.306500]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
^C[INFO] [1618567501.318116]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1618567501.328666]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[ERROR] [1618567501.339870]: Creation of publisher failed: nav_msgs
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
[INFO] [1618567501.350452]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1618567501.361133]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1618567501.371494]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[turtlebot3_diagnostics-3] killing on exit
[INFO] [1618567501.384824]: Setup publisher on /tf [tf/tfMessage]
[turtlebot3_lds-2] killing on exit
[turtlebot3_core-1] killing on exit
[INFO] [1618567501.398437]: Send tx stop request
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by ROBOTIS-Will** [comment]
@tehnanmanna 
Please make sure that your Raspberry Pi has correctly installed nav-msgs package during ROS installation.
```
$ sudo apt install ros-melodic-nav-msgs
```
