### ISSUE TITLE
TB3 burger is going opposite direction when I move forward by andriod app (the picture say it all)

### ISSUE THREAD

**Issue by angrysword** [ROBOTIS-GIT/turtlebot3#262]
ISSUE TEMPLATE ver. 0.1.0

1. Which TurtleBot3 you have?

    - [x ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ x] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ ] Ubuntu MATE 16.04 or later
    - [ X] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ X] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

3. Write down software version and firmware version

    - Software version: [1.12.12]
    - Firmware version: [x.x.x]
 
4. Write down the commands you used in order

    [Remote PC] roscore
    [SBC] roslaunch turtlebot3_bringup turtlebot3_robot.launch
 Hi Team

 I use android teleop app. and when I ask turtlebot move foreward. however turtle bot going backward. 

Please refer the picture. When I click blue circle in the phone, it suppose move foreward, however it move backward.  This problem will leads the slam  follower app can not work correctly. 

Thanks guys

![turtlebot3 wrong direction](https://user-images.githubusercontent.com/3065257/42923631-59656cd4-8adb-11e8-98db-c41f70a7b4cd.jpg)

**Comment by kijongGil** [comment]
Hi @angrysword :)
Could you check your DXL's ID? Letf DXL is 1, right DLS is 2.
Thanks,
Gilbert.

**Comment by angrysword** [comment]
Thanks Gilbert, you are right, you save me a day and a day ahead and .... big thanks.  Works now

**Comment by kijongGil** [comment]
Thanks, If you have any further questions, please feel free to open new issue page.
