### ISSUE TITLE
Navigation tutorial: amcl problem ?

### ISSUE THREAD

**Issue by DoNck** [ROBOTIS-GIT/turtlebot3#266]
Hi there !

1. Which TurtleBot3 you have?

    - [X] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [X] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [X] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [X] Xenial 16.04 + Kinetic, native on the TB3, inside a docker container (FROM osrf/ros:kinetic-desktop-full) on my Fedora 27 laptop

5. Write down software version and firmware version

    - Software version: [1.12.13 on both the TB3 and the docker container on my laptop]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

    - following the robotis tutorials:

      [laptop]
      roscore

      [tb3]
      roslaunch turtlebot3_bringup turtlebot3_robot.launch

      [laptop]
      roslaunch turtlebot3_slam turtlebot3_slam.launch slam_methods:=gmapping

      I move the robot using the android app and when the map is complete I run:

      rosrun map_server map_saver -f ~/map
    
      Then I kill stop the former gmapping task, move the robot by hand to a reference place in the room, and launch the navigation task:

      roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=/home/ros/map.yaml

 
7. Copy and Paste your error message on terminal

    I get the following warnings from the navigation task:
    - "could not get robot pose, cancelling reconfiguration"
    - "Costmap2DROS transform timeout. Current time: 153253596.3332, global_pose_stamp: 1532353713.8062, tolerance: 0.5000"
  
8. Please, describe detailedly what difficulty you are in 

    - Then in RViz I click to set the 2D Pose Estimate, I iterate to align laserscan dots with the occupancy map. The problem is that when I set a nav goal or move the robot by teleoperation, the robot does not move on the map.
And I get warning over and over in the console.

I'm pretty new to ROS but as the robot does not move on the map, I feel like the amcl is not working for some reason.
How to troubleshoot and fix ? I'm starting to feel like a turtle without salad !

DoNcK

---

Some screenshots and extra info:

Screenshot of RViz after manual aligning:
![2d pose estimate](https://user-images.githubusercontent.com/4924969/43081142-9f6d034a-8e91-11e8-808b-bc37a09e0725.png)

Screenshot of RViz after waiting 1 minute (no visible changes except warning in console) and then moving the robot:
![screenshot from 2018-07-23 16-04-00](https://user-images.githubusercontent.com/4924969/43081322-0da422d0-8e92-11e8-909a-d2f3517b95d0.png)

Strange stuffs I noticed:

rostopic hz /amcl_pose
=> no new messages

and on roswtf:

```
WARNING The following nodes are unexpectedly connected:
 * /robot_state_publisher->/rqt_gui_py_node_13192 (/tf_static)


Found 1 error(s).

ERROR The following nodes should be connected but aren't:
 * /move_base->/move_base (/move_base/global_costmap/footprint)
 * /move_base->/move_base (/move_base/local_costmap/footprint)
```

![rosgraph_teleop_nav](https://user-images.githubusercontent.com/4924969/43082916-82aa6014-8e95-11e8-937c-a81231b298f8.png)

**Comment by robotpilot** [comment]
Hi @DoNck
I think you are sending two `cmd_vel` topics. In the last picture of the post you uploaded, you are sending `cmd_vel` on each of the `move_base` and `turtlebot3_teleop_keyboard` nodes. In particular, the `turtlebot3_teleop_keyboard` node sends a `cmd_vel` value of zero. Shutting down the `turtlebot3_teleop_keyboard` node seems to solve your problem.

Maybe you have not chekc it yet, we explained why we should terminate `turtlebot3_teleop_keyboard` in the `tip` of the manual below.
http://emanual.robotis.com/docs/en/platform/turtlebot3/navigation/#estimate-initial-pose

**Comment by DoNck** [comment]
As you suggested, I terminated the teleop node.

```
$ rostopic info /cmd_vel
Type: geometry_msgs/Twist

Publishers: 
 * /move_base (http://172.24.1.60:33955/)

Subscribers: 
 * /turtlebot3_core (http://172.24.1.129:46539/)
```

Then I restarted the navigation task (at that point one initial message was published on `/amcl_pose`), set the 2D pose estimate (a second message is published, then after some time I get the warning).

Still I have the warnings and I can't see any other improvement: map is not getting auto-aligned, as soon as I set a goal, the robot starts to move forward, the lidar and map aligment gets worst and worst...

Regarding the manual, that is the one I've been trying to follow (my only "deviation" is that I'm using Docker on he Remote PC). Could that be a problem ?

From my understanding of the guide:
1) Run `roscore` on Remote PC
2) Run `turtlebot3_robot.launch` from `turtlebot3_bringup` on the TB3
3) Run `turtlebot3_slam` on Remote PC and save the map
4) Terminate the `turtlebot3_slam` and run `turtlebot3_navigation` instead (using the saved map).
5) Set the 2D pose estimate in RViz
6) Run teleop on Remote PC to move back and forth using until the amcl magick works
    (I guessed it should improve the lidar/map aligment in RViz and send regular position updates to `/amcl_pose`)
7) As soon as amcl is working, quit teleop (tip), set a 2D nav goals and have some fun

Is my understanding correct ? Or what did I do wrong ?
Did I forget to run others nodes ?

**Comment by robotpilot** [comment]
Hi @DoNck
I think you are perfect. I have never seen SLAM work without problems but Navigation does not work. Both must be good or not both. Can you send me your bag data? I think we should look into what is wrong.

**Comment by routiful** [comment]
Hello :)

Did you reset your turtlebot3 before you launch navigation?
If not, you are supposed to reset odometry and imu data to use `/reset` topic
or re-launch bringup.

**Comment by DoNck** [comment]
OK well I even restarted the rosrecore on remote PC and rebooted the raspberry pi on the robot, it did not improve.
I also tried what you said: not better either.
And then I saw this big reset button on the OpenCR: I terminated the bringup, unplug/plug the OpenCR, pressed reset, restarted the bringup: everything is now working as exepected.
Thanks a lot for your support !
I let you close the issue unless you want some more information about my setup.

**Comment by routiful** [comment]
Thank you for sharing your experiences. If you have any further issues, please feel free to open issue.
Thanks

**Comment by timdori** [comment]
Hello :)
I have a short question. Im exactly in the same situation.  Why the reset is so important? does the robot kind of save the odom before?

**Comment by hansenmaster** [comment]
![2d-nav](https://user-images.githubusercontent.com/36762228/46326609-bce5c880-c627-11e8-8490-5cd34e4d5ef8.png)

Hi I wanna ask, in initial pose set. You said you move the robot forward and backward until the AMCL do the magic? what's the indicator the AMCL works and we're good to set the 2d nav goal?
Please help, me i have exact problem with you, but still the robot doesn;t move

**Comment by DoNck** [comment]
Hi, my two cents:

The indicator that AMCL works is that the green particle cloud around the robot should get closer and closer around the robot actual position.
The cloud should update if you move the robot. If it does not, try moving the robot slower and along a longer path.

Hint: In my setup, I noticed that I can get good results faster, by slowly turning the robot right/left instead of moving back/forth.

Also, since I press the reset buton of the OpenCR board before running the bringup, and reset+restart bringup after battery hotpswaps, I got rid of the "robot not moving correctly on the map" problem.

**Comment by hansenmaster** [comment]
Hi DoNock

I really appreciate your fast response, i still don't know if my AMCL is working or not, if you see my picture in my first comment. Do you think from the green points that line up around the wall is good enough to start 2d nav goal? Does it even already have green particle cloud?

Could you kindly show me some pics or even a video that show how the good initial pose when AMCL is working by making the progress in green particle cloud?

I tried to the reset button on OpenCR, restart the Turtlebot and relaunch bringup. But still after 2d nav goal set the robot do nothing. I'll try the battery hotswap too.

**Comment by hansenmaster** [comment]
Hi timdori, thanks for the response

I tried the android teleop when initial pose setting, the command velocity is good and the robot move. Then i kill the teleop node, send the 2d nav goal, but the robot doesn't move.
I checked the rostopic info /cmd_vel is published by node (move_base) , the topic  /move_base_simple/goal is updated every time i set the 2d-nav-goal , but still like the command velocity not updated.

**Comment by DoNck** [comment]
[youtube video with particle cloud  (in red) updating and converging to robot position](https://www.youtube.com/watch?v=uwWHK90bK8I)

**Comment by hansenmaster** [comment]
> [youtube video with particle cloud (in red) updating and converging to robot position](https://www.youtube.com/watch?v=uwWHK90bK8I)

Hi DoNck
the trick to rotate slowly and AMCL did it magic :D , 
![image](https://user-images.githubusercontent.com/36762228/46388768-63999a00-c6f8-11e8-8c0d-8862fc6950cd.png)

I tried to hotswap and reset openCR , but still the 2d nav goal set doesn't seem to update the cmd_vel :(

**Comment by hansenmaster** [comment]
Hi DoNcK and timdori. I've solved my problem by timesync the turtlebot and my pc with timedatectl on same timezone, the robot move when i set the 2d nav goal. The problem was Costmap always timeout , because the dfferent time set, once it set right the costmap defined and the robot can move :D

Thank you very much

**Comment by DoNck** [comment]
Good that you spotted the time issue, they are not obvious when they occur...
In case your clock was not synced because you work on a network that filters out UDP, you can update your clock using this simple HTTP based python [script](https://github.com/DoNck/set-time) I wrote.

**Comment by florianspy** [comment]
Furthermore when you use the rviz to set an inital pose check if your Fixed Frame setting in rviz is set to "map", otherwise the inital pose message send out by rviz will be wrong
