### ISSUE TITLE
Advice on obstacle detection

### ISSUE THREAD

**Issue by Hellsgone** [ROBOTIS-GIT/turtlebot3#270]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [x] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ ] Ubuntu MATE 16.04 or later
    - [x] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

8. Please, describe detailedly what difficulty you are in 

    - Hello again ROBOTIS team, I don't have an issue but just a question about turtlebot 3 and hoping you could give me some guidance. I want to know if I can implement a PID control system on the robot speed aka dynamixels using the lidar to avoid collision with obstacles. The idea is the turtlebot would follow a line using the IR sensors I attached and while following the line it would use lidar sensor to detect anything in front of it and it would slow down or stop according to the distance in between. While doing this the object in front can move too but the turtlebot must move accordingly. 

Question: How can I use the Obstacle Detection [Here](http://emanual.robotis.com/docs/en/platform/turtlebot3/basic_examples/#obstacle-detection) to adjust the speed of the dynamixels rather than stopping immediately. I want to use Arduino IDE for this and vary the speed of dynamixels according to the distance detection made from lidar. I found in the machine learning section about this however there is no such information. I am looking forward to your help and would gladly answer questions to clear any confusion.

**Comment by kijongGil** [comment]
Hi again @Hellsgone :)
You can control the speed according to the value of LDS. I recommend that modified this code.
https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_example/nodes/turtlebot3_obstacle#L43

This code is simple. The value of front LDS is less than 0.2m, the speed is 0 m/s. Otherwise the speed is 0.05 m/s. For example, if you want to add that the value of front LDS is 0.2 to 0.5, the speed is 0.02 m/s.

 elif 0.2 < min(self.scan_filter) < 0.5:
                self.twist.linear.x = 0.02
                self.twist.angular.z = 0.0
                self._cmd_pub.publish(self.twist)

Thanks,
Gilbert

**Comment by Hellsgone** [comment]
Hello, thank you for taking the time to reply.
Yes this is perfectly what I needed, I have modified the degree and distance speed parameters and it is working all good. I have another question. Can I use the library used in this application for arduino IDE? I want the turtlebot to follow a line and scan for obstacles at the same time and I need to implement a PID control to the speed of the turtlebot but I don't know how to adjust the motor speed apart from using dxl_wb.goalSpeed which is only static speed. Also I have both programs but how can I make them into one. I also want to know the code for the LDS and dynamixels for arduino IDE that is of course if my idea can be possible. Thank you so much you are so helpful. Looking forward to this reply as now this is the most important part I am stuck with. 
Kind Regards,
Arda

**Comment by routiful** [comment]
Hi :)

You can find the example of LDS in OpenCR library.
`File` -> `Examples` -> `OpenCR` -> `Etc` -> `LDS` -> `drawLDS`

And I recommend `PWM Control Mode` with PID control. You can get an idea how to use this in `turtlebot3_segway` example.
`File` -> `Examples` -> `TurtleBot3` -> `turtlebot3_friends` -> `turtlebot3_segway`

**Comment by Hellsgone** [comment]
Thank you for the help I really appreciate it. Managed to do both goals I wanted the robot to achieve.
:)

**Comment by routiful** [comment]
Nice! If you have any further questions, please feel free to open issue.

**Comment by GokulEpiphany** [comment]
Could you please link, File -> Examples -> TurtleBot3 -> turtlebot3_friends -> turtlebot3_segway ? Where Can I find this folder?
