### ISSUE TITLE
Turtlebot3 and stage simulator

### ISSUE THREAD

**Issue by pitosalas** [ROBOTIS-GIT/turtlebot3#285]
Is there a package to use stage as the tb3 simulator? I am running in VMWare and Gazebo can't do it.

**Comment by routiful** [comment]
Sorry, we didn't provide other simulator for tb3. We highly recommend dual-boot or isolate install Ubuntu. If you can't, you can use ROS Development Studio in Web browser.

http://emanual.robotis.com/docs/en/platform/turtlebot3/learn/#the-construct

**Comment by pitosalas** [comment]
Hi! Thanks… That Studio isn’t free is it? I think it’s pretty expensive to use! Or did I miss a link? Thanks

Pito Salas
Brandeis Computer Science
Volen 134

**Comment by routiful** [comment]
The Construct provides free version.

http://www.theconstructsim.com/rds-ros-development-studio/

**Comment by pitosalas** [comment]
Thanks
