### ISSUE TITLE
Turtlebot 3 angular velocity commands sign change in real world

### ISSUE THREAD

**Issue by varunvp** [ROBOTIS-GIT/turtlebot3#287]
ISSUE TEMPLATE ver. 0.2.0

1. - [x] Burger
2. - [ ] Raspberry Pi 3

3. - [ ] Raspbian

4. - [ ] Ubuntu 14.04 LTS

5. Write down software version and firmware version
    - Software version: [1.0.0]
    - Firmware version: [1.2.0]
 6. Write down the commands you used in order

    -roslaunch turtlebot3_bringup turtlebot3_robot.launch

I've noticed that I have to change the signs of the angular velocity commands whenever I switch between simulations, and the turtlebot. Is this a bug?

**Comment by kijongGil** [comment]
Hi @varunvp :)
Could you tell me more about you said 'switch between simulations and the turtlebot'?

**Comment by varunvp** [comment]
I meant switching between turtlebot simulations on gazebo, and the real life turtlebot.

**Comment by kijongGil** [comment]
Could you check your DXL's ID? Letf DXL is 1, right DXL is 2.
Thanks,
Gilbert.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
