### ISSUE TITLE
Turtlebot3 Weight Distribution

### ISSUE THREAD

**Issue by pitosalas** [ROBOTIS-GIT/turtlebot3#296]
As mentioned in answers.ros.com, my TB3 exhibits a "bucking" or "stuttering" behavior when moving backwards. I am investigating whether somehow the TB3 is getting contradictory cmd_vel messages as we think might be the case.

I have a specific question for Robotis tough: Would balance or center of gravity affect this? Or would the condition of the caster ball? The caster ball does move freely. But I notice that the caster ball side is a little bit lower than the wheel side. Is that normal?

**Comment by robotpilot** [comment]
For differential-drive mobile, a caster ball is used. This position, height, and center of gravity of the whole are very important. We tested the casters slightly lower through various tests. This is a proven part, so no problem.

**Comment by robotpilot** [comment]
I have never seen you. If you think it is a hardware problem, please have it repaired by your dealer.

**Comment by pitosalas** [comment]
I don't know exactly what you mean :) I am giving you information that I thought would be useful in case others have these problems. And also looking for help diagnosing the behavior.
