### ISSUE TITLE
Setting up RC-100b with TB3 Burger

### ISSUE THREAD

**Issue by marksaaron** [ROBOTIS-GIT/turtlebot3#302]
For the TB3 Burger with RasPi3 running Ubuntu, what additional hardware is needed for setup and operation of the RC-100b controller (either for IR or Bluetooth)?

**Comment by kijongGil** [comment]
Hi @marksaaron :)
If you want to use RC-100, you have to need a BT-410.
http://emanual.robotis.com/docs/en/parts/communication/bt-410/

Gilbert,
Thanks.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
