### ISSUE TITLE
Support Waffle(Pi) with ROS2

### ISSUE THREAD

**Issue by nwesthoff** [ROBOTIS-GIT/turtlebot3#314]
1. Which TurtleBot3 you have?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [x] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ ] Ubuntu MATE 16.04 or later
    - [x] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)
  
5. Please, describe detailedly what difficulty you are in 

 Hi! I've currently installed ROS2 on my Remote PC, and installed the prebuilt raspbian image on my Turtlebot 3. Unfortunately, the OpenCR firmware is only available for burger config right now. Are you working on [OpenCR Binaries](https://github.com/ROBOTIS-GIT/OpenCR-Binaries) for Waffle and Waffle Pi to use with ROS2?

I'm able to move the turtlebot using teleop. And I'm able to run real-time SLAM with cartographer, which returns data in rviz2, but as soon as I move the turtlebot, the odom and map get disconnected (which I guess is an issue with the OpenCR binaries that I installed).

**Comment by routiful** [comment]
Hi again :)

We have a plan to develop firmware for Waffle and Waffle Pi for ROS2 near future.
We will announce that including new applications.

And disconnected issue can be solved `ntpdate` sync between SBC and PC.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
