### ISSUE TITLE
SLAM on turtlebot3 using ToF sensor(pcd data format)

### ISSUE THREAD

**Issue by archana-l** [ROBOTIS-GIT/turtlebot3#317]
Hi,
I wanted to replace  lidar sensor with ToF sensor(OPT8241)in turtlebot 3 burger and implement slam on it. Is it possible? and how can i do that?

**Comment by kijongGil** [comment]
Hi @archana-l :)
I'm not sure It is possible. Maybe this link will be help you.
https://e2e.ti.com/support/sensors/f/1023/t/495486?OPT8241-API-ROS

Thanks,
Gilbert.

**Comment by archana-l** [comment]
Thank you @kijongGil 
I will ckeck it.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by asad889** [comment]
Hi,

Did you find the solution?
