### ISSUE TITLE
Cannot control Dynamixel Motors due to OpenCR board issues

### ISSUE THREAD

**Issue by salla23** [ROBOTIS-GIT/turtlebot3#322]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ ] Burger
    - [ ] Waffle
    - [X] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [X] Raspberry Pi 3 (For controlling the OpenCR board)
    - [ ] Intel Joule 570x
    - [X] etc (Jetson TX2 as the ROS MASTER)

3. Which OS you installed in SBC?

    - [X] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [X] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version
    -> _ROS Kinetic_

My turtlebot setup was working last week but I cannot get any results from publishing to the /cmd_vel node and am thus stuck. I am trying to get the dynamixel motors working with the TB3 and I am running into some very cumbersome issues, as documented below. I've followed the instructions for troubleshooting that I was provided and while the OpenCR board seems to be working properly, I am not able to get the motors working. I have ensured the LiPO is fully charger (12.45 V) and I was able to follow instructions to upload arduino code and test the board (for example, by executing the BLINK example code). However, when I tried to run the turtlebot3_setup_motor code or the turtlebot3_core codes, I keep receiving an error message reading "cmd_read_board_name fail : 0xF020" and errors about not being able to open the location /dev/ttyACM0.

![image 3](https://user-images.githubusercontent.com/32280929/46116299-47ee3b00-c1b0-11e8-8f84-9e3af37b0a8a.png)

The OpenCR board (STMicroelectronics STM32F407) is only detected after holding the boot and reset buttons (entering DFU mode) for a couple of seconds and then running a second lsusb command.

![image 2](https://user-images.githubusercontent.com/32280929/46116305-53416680-c1b0-11e8-8d80-ad005587e0e0.png)

![image 1](https://user-images.githubusercontent.com/32280929/46116313-5a687480-c1b0-11e8-867e-ebf07a1fd200.png)

***Additional:** 
I've also tried to burn the bootloader so that I could essentially "reset" the OpenCR board and then be able to reflash it with a new firmware (currently 1.2.3) but i cannot do so because the Arduino throws an error that it cannot burn the bootloader. Its an intriguing issue that I cannot seem to deal with, so please let me know if you can help at all.

![image](https://user-images.githubusercontent.com/32280929/46116368-a1ef0080-c1b0-11e8-8a9b-ac334dbd6823.png)

The goal of the troubleshooting was that I would be able to manually/more directly determine if the motors are working before using 'turtlebot3_robot.launch' roslaunch file to launch the main TB3 functionalities. However, after attempting the troubleshooting steps described above, I am not even able to launch this 'turtlebot3_robot.launch' file because of the errors seen.

**Comment by routiful** [comment]
Hi :)

Sorry for late reply. You don't need to re-upload bootloader.
I think below attached link help you 

http://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#faq

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. 
You can reopen this issue to show this issue to the users whenever. 
Thanks.
