### ISSUE TITLE
Melodic install for onboard Pi for Turtlebot3 WafflePi, or mixing RemotePC and Robot versions?

### ISSUE THREAD

**Issue by kulakovich** [ROBOTIS-GIT/turtlebot3#327]
The e-manual takes you through installing Kinetic, not Melodic
http://emanual.robotis.com/docs/en/platform/turtlebot3/raspberry_pi_3_setup/#raspberry-pi-3-setup

1. Is there any way to install Melodic on the Turtlebot3 WafflePi? 

2. Can I run Melodic on the Remote PC to drive a Kinetic Turtlebot3?

Thanks

ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ ] Burger
    - [ ] Waffle
    - [√ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [√] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [√] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [√] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

    - HERE
 
7. Copy and Paste your error message on terminal

    - HERE
  
8. Please, describe detailedly what difficulty you are in 

    - HERE

**Comment by kijongGil** [comment]
Hi @kulakovich :)
I'm sorry for late reply.
I'm really sorry, but it does not support the melodic version yet. I will let you know when I release ros-melodic.

Thanks,
Gilbert

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
