### ISSUE TITLE
teleoperating Turtlebot3 burger with LeapMotion

### ISSUE THREAD

**Issue by stevensu1838** [ROBOTIS-GIT/turtlebot3#333]
In the user manual, you have the following instructions: 

```
LEAP Motion
[Remote PC] Connect LEAP motion to the remote PC via Bluetooth.

[Remote PC] Install packages for teleoperation using LEAP motion.

LEAP Setup
Download SDK
$ leapd
$ LeapCommandPanel
$ git clone git@github.com:warp1337/rosleapmotion.git
[Remote PC] Run teleoperation package for LEAP motion.

$ rosrun leap_motion sender.py
```
But I bet these steps only get Leap Motion work on the Remote PC. How about the communication?
Can you please show me more details on how to accomplish this task? Don't I need a package to build up the communication between Leap Motion and turtlebot3?

**Comment by routiful** [comment]
No, you are supposed to launch turtlebot3_bringup. 

http://emanual.robotis.com/docs/en/platform/turtlebot3/bringup/#bringup-a-turtlebot3

**Comment by stevensu1838** [comment]
Hi,
First, I'd love to make some comments on this Leap Motion instructions.
When $ leapd doesn't work, please try $sudo leapd.
Command $ LeapCommandPanel doesn't work anymore, you need $LeapControlPanel(another terminal) instead.
Secondly, after trying it out, I still can't teleoperate the turtlebot3 burger with the leap motion as you accomplished in your e-manual.
In rqt graph, there is no comunication between gazebo and leap motion.
I bet there is something missing in your e-manual, can you please try to run it on your side to make sure your example is doable and feasible?
![image](https://user-images.githubusercontent.com/25648734/47205447-72639a80-d3e2-11e8-98b7-f5ff2c3c873c.png)
![image](https://user-images.githubusercontent.com/25648734/47205478-88715b00-d3e2-11e8-8de8-1246c618c81e.png)
Thank you so much for your great support

**Comment by stevensu1838** [comment]
Btw, it works fine if I use the keyboard to teleoperate the robot. Thanks.
![image](https://user-images.githubusercontent.com/25648734/47205708-2cf39d00-d3e3-11e8-83cc-f0d955f0b84c.png)

**Comment by routiful** [comment]
I tested it over one years ago.
I searched the related manual. And I found that the code was changed 4 months ago.(I assume that you already know that)

https://github.com/warp1337/rosleapmotion

It looks like doesn't support /cmd_vel topic anymore. I think you are supposed to make node that subscribes data from leapmotion and publishes /cmd_vel yourself.

**Comment by stevensu1838** [comment]
Hi buddy,
May I please ask how you notice it doesn't support /cmd_vel topic anymore? In which file can we see the details? Cheers.

**Comment by stevensu1838** [comment]
Hi buddy,
Thanks a lot. First, I also checked the old version of rosleapmotion. I don't any msg related /cmd_vel header like Twist, either.

Secondly, I've checked another two github ROS packages for ROS teleoperation. They all have a python file to publish cmd_vel topics. Do you think we need something similar for turtlebot3. If so, do you have it or a template that I could take refer to? Thanks a lot. It is way to challenging for me to do it myself. Cheers

[https://github.com/qboticslabs/ros_robotics_projects/blob/master/chapter_11_codes/vr_leap_teleop/scripts/vr_leap_teleop.py](url)
[https://github.com/madratman/youbot_leapmotionteleop/blob/master/scripts/youbot_leap.py](url)

**Comment by routiful** [comment]
Yes, I can't remember that but I had to make other node to publish /cmd_vel.
TurtleBot3 meta packages include teleop package. (https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_teleop/nodes/turtlebot3_teleop_key)

References you attached is good example of interconnect between leapmotion and turtlebot3.

**Comment by stevensu1838** [comment]
Hi Buddy, do you have any documents which can do nterconnection between leapmotion and turtlebot3?  Cheers. 

Steven

**Comment by routiful** [comment]
This issue are re-opened #345
