### ISSUE TITLE
Issue with the turtlebot3 follower demo

### ISSUE THREAD

**Issue by Rookieteam4** [ROBOTIS-GIT/turtlebot3#335]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ *] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [* ] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [* ] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [* ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

    - the follower demo instruction on the website
 
7. Copy and Paste your error message on terminal

    - none
  
8. Please, describe detailedly what difficulty you are in 

    - Recently I just wanna do the follower demo to test whether it works or not, and when I followed the instructions and everything goes normal, no error occur with the codes. However, when everything is done, the turtlebot follower just like running itself with following nothing.I provided like 4*4 m^2 open space for the robot.

**Comment by kijongGil** [comment]
Hi @Rookieteam4 :)
I'm sorry. I don't understand that "the turtlebot follower just like running itself with following nothing". Could you explain a little more?

Thanks,
Gilbert

**Comment by Rookieteam4** [comment]
sometime there is nothing around the turtlebot, the robot just move itself ,like it move towards the wall without stopping, or maybe move a little and then stop.
and sometime, when we stand before it and move forward, the turtlebot does not follow us, it just idle in the original place.
We dont know what is wrong with this robot, looks like the code for robot follower does not function in the right way.

**Comment by Rookieteam4** [comment]
the motor of the robot may even continue running even the robot is touching the wall or some obstacles.

**Comment by kijongGil** [comment]
I understand your situation. I think that your robot and the code is no problem. Just follow code use basic [scikit-learn](http://scikit-learn.org/stable/). This is machine learning. So, If you want to more performance, you need to know scikit.
