### ISSUE TITLE
Wheels turning with different speeds

### ISSUE THREAD

**Issue by lukaskern** [ROBOTIS-GIT/turtlebot3#336]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [x] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [x] Ubuntu MATE 16.04.5 LTS
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [x] Windows 10, but it isn't involved in the problem that I'm facing: I'm connected to Ubuntu on the TurtleBot via SSH, and I'm issuing the commands below (see 8.) directly on the TurtleBot.

5. Write down software version and firmware version

    - TurtleBot: ROS kinetic 1.12.13
    - OpenCR board core v1.2.2
 
6. Write down the commands you used in order

    - See 8.
 
7. Copy and Paste your error message on terminal

    - No error message
  
8. Please, describe detailedly what difficulty you are in 

    - Although I'm sending the robot a simple geometry_msgs/Twist with linear part (0.3,0,0) and angular part (0,0,0), it very slightly drifts to the left instead of driving straight forward. When setting up the OpenCR board I used the shell script and not the Arduino IDE (shell script being the way recommended in the Turtlebot3 e-manual).
Do I need to install the Arduino IDE in order to calibrate the Dynamixels (using Dynamixel workbench?) or have they been calibrated with the abovementioned shell script? Do I even need to calibrate them? Thank you for any suggestions.

**Comment by kijongGil** [comment]
Hi @lukaskern :)
I'm sorry for late reply.
Could you tell me how much drift? 
And then, actually you don't need to calibration the DXL. I doubt this is a problem with the DXL itself, or a problem with the hardware.

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
