### ISSUE TITLE
Releasing to rosdistro in melodic

### ISSUE THREAD

**Issue by SteveMacenski** [ROBOTIS-GIT/turtlebot3#341]
This meta package is released fully in kinetic but missing in melodic's rosdep distribution file. Can you run bloom over the melodic release?

https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml

**Comment by kijongGil** [comment]
Hi @SteveMacenski :)
We will release the melodic version next year.
Thanks,
Gilbert.

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by routiful** [comment]
Sorry, we will let you know after release.

**Comment by robotpilot** [comment]
http://repositories.ros.org/status_page/ros_melodic_default.html?q=turtlebot3
