### ISSUE TITLE
Segmentation fault (core dumped)  when I use rosrun joy joy_node 

### ISSUE THREAD

**Issue by stevensu1838** [ROBOTIS-GIT/turtlebot3#346]
ROS kinetic Ubuntu 16.04   Xbox360 controller    Turtlebot3 Burger

I am trying to use a Xbox 360 to teleoperate my turtlebot3 burger.
I followed this tutorial: http://wiki.ros.org/joy/Tutorials/ConfiguringALinuxJoystick to set up. However, I get the following errors when I run rosrun joy joy_node 
```

user@mech1349:~$ sudo apt-get install ros-kinetic-joy
user@mech1349:~$ sudo chmod a+rw /dev/input/js0
user@mech1349:~$ roscore
user@mech1349:~$ rosparam set joy_node/dev "/dev/input/js0"
user@mech1349:~$ rosrun joy joy_node
Segmentation fault (core dumped)
```

Can anyone help me out???

**Comment by kijongGil** [comment]
Hi @stevensu1838 :)
I'm sorry, but The joy package is not our package. I don't know well this problem.
I think it would be better for you to go [joystick](https://github.com/ros-drivers/joystick_drivers/issues).

Thanks,
Gilbert.
