### ISSUE TITLE
catkin_make failed  (turtlebot3, turtlebot3_msgs)

### ISSUE THREAD

**Issue by coh1211** [ROBOTIS-GIT/turtlebot3#347]
ISSUE TEMPLATE ver. 0.2.0

- Which OS you installed in Remote PC?
    - [o ] Ubuntu 16.04 LTS (Xenial Xerus)
 
- Write down the commands you used in 

    `cd src`
    `git clone https://github.com/ROBOTIS-GIT/turtlebot3.git`
    `git clone https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git`
    `cd .. && catkin_make`

- Copy and Paste your error message on terminal
`[ 96%] Building CXX object turtlebot3/turtlebot3_bringup/CMakeFiles/turtlebot3_diagnostics.dir/src/turtlebot3_diagnostics.cpp.o`
`//usr/lib/x86_64-linux-gnu/libapr-1.so.0: undefined reference to 'uuid_generate@UUID_1.0'
collect2: error: ld returned 1 exit status`
`turtlebot3/turtlebot3_slam/CMakeFiles/flat_world_imu_node.dir/build.make:113: recipe for target '/home/coh/condatest4/catkin_ws/devel/lib/turtlebot3_slam/flat_world_imu_node' failed`
`make[2]: *** [/home/coh/condatest4/catkin_ws/devel/lib/turtlebot3_slam/flat_world_imu_node] Error 1`
`CMakeFiles/Makefile2:3741: recipe for target 'turtlebot3/turtlebot3_slam/CMakeFiles/flat_world_imu_node.dir/all' failed`
`make[1]: *** [turtlebot3/turtlebot3_slam/CMakeFiles/flat_world_imu_node.dir/all] Error 2`
`make[1]: *** Waiting for unfinished jobs...`
     
- Please, describe detailedly what difficulty you are in 
  Hi. This will not be the problem in turtlebot but just my laptop and its libraries, but I'm posting a question, hoping that there might be someone who experienced same problem during installing the turtlebot.
 I'm trying to run the turtlebot in Gazebo environment but faced with the error above during building turtlebot and turtlebot_msgs. If any suggestions, please do let me know.

**Comment by kijongGil** [comment]
Hi @coh1211 :)
It looks like your catkin_ws path is not ~/home/[USER]/catkin_ws and you use anaconda.
Please try reinstalling ROS in the correct path without using anaconda.

Thanks,
Gilbert
