### ISSUE TITLE
Intel RealSens R200 camera not available on line any more. Any other 3D cameras can replace it?

### ISSUE THREAD

**Issue by stevensu1838** [ROBOTIS-GIT/turtlebot3#356]
Hi,
I am buying an Intel RealSens R200 camera for my Turtlebot 3  but can't find it anywhere online. Can you help? If not, is there any other 3D camera you've tested that can replace Intel RealSens R200?

How about Intel SR300, Intel ZR300, Intel Euclid, Asus?
Thanks

Specifically, I wanna build Octomap with the camera.

**Comment by routiful** [comment]
I heard that Realsens R200 is not sale anymore.
You can find another camera in [intel store](https://click.intel.com/realsense.html)

**Comment by yoshimalucky** [comment]
D435i is the best!
https://click.intel.com/intel-realsense-depth-camera-d435i-imu.html

**Comment by stevensu1838** [comment]
@yoshimalucky
Hi buddy, do you have any documents or tutorial on how to use D435i in ROS? Thanks a lot

**Comment by kijongGil** [comment]
Sorry. We don't have experiment with D435i.
