### ISSUE TITLE
Unable to upload code in OpenCR

### ISSUE THREAD

**Issue by anwaybose** [ROBOTIS-GIT/turtlebot3#359]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ ] Burger
    - [ ] Waffle
    - [ 1] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ 1] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ 1] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [1 ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

    - HERE
 
7. Copy and Paste your error message on terminal

    - HERE
  
8. Please, describe detailedly what difficulty you are in 

    
**Hello,
I'm facing a problem with uploading code to OpenCR.
the error is** 

Board OpenCR (platform OpenCR, package OpenCR) is unknown

Error compiling for board OpenCR Board.

**I have tried to set up the USB port again and to recover the firmware following these links:**
http://emanual.robotis.com/docs/en/parts/controller/opencr10/#usb-port-settings
http://emanual.robotis.com/docs/en/parts/controller/opencr10/#firmware-recovery-mode

**But still I'm facing an error as follow:**
anway@simpl:~/Dev/OpenCR/arduino/opencr_arduino/tools/opencr_tools_1.0.0/linux64$ ./opencr_ld /dev/ttyACM0 115200 ./turtlebot3_core.ino.OpenCR.bin 1
opencr_ld ver 1.0.4
opencr_ld_main 
>>
file name : ./turtlebot3_core.ino.OpenCR.bin 
file size : 177 KB
Open port OK
Clear Buffer Start
Clear Buffer End
cmd_read_board_name fail : 0xF020

_I've also tried to reinstall the driver and burnt the bootloader again 
Still I'm unable to upload my code. The error is as follow_
![clipboard-image](https://user-images.githubusercontent.com/44193774/50279725-92f6b200-0470-11e9-9603-ed3e39d1a789.png)

**Can you help me to detect whether this is a hardware problem or not? Do I need to change my OpenCR board?**

**Comment by OpusK** [comment]
duplicated #240.
