### ISSUE TITLE
Problem Bringing up TB3 Burger

### ISSUE THREAD

**Issue by mickpmack** [ROBOTIS-GIT/turtlebot3#363]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ x] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] openCR
3. Which OS you installed in SBC?

    - [ x] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] 

4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

If this refers to openrCR i'm not sure I have initialised the card with the 6.3.1.1 Shell Script
method.

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

On step 7.3:
Load a TurtleBot3 on Rviz
[Remote PC] Launch robot state publisher and Run RViz.

TIP: Before executing this command, you have to specify the model name of TurtleBot3. The ${TB3_MODEL} is the name of the model you are using in burger, waffle, waffle_pi. If you want to permanently set the export settings, please refer to Export TURTLEBOT3_MODEL page.

$ export TURTLEBOT3_MODEL=${TB3_MODEL}
$ roslaunch turtlebot3_bringup turtlebot3_remote.launch
 
7. Copy and Paste your error message on terminal

michael@Turtlebot3:~/catkin_ws$ roslaunch turtlebot3_bringup turtlebot3_remote.launch
... logging to /home/michael/.ros/log/cba245aa-0e3f-11e9-a581-b827eb892c16/roslaunch-Turtlebot3-2341.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

while processing /home/michael/catkin_ws/src/turtlebot3/turtlebot3_bringup/launch/includes/description.launch.xml:
Invalid <arg> tag: xacro
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/michael/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share. 

Arg xml is <arg default="$(find xacro)/xacro --inorder '$(find turtlebot3_description)/urdf/turtlebot3_$(arg model).urdf.xacro'" name="urdf_file"/>
The traceback for the exception was written to the log file

  
8. Please, describe detailedly what difficulty you are in 

    -As this is my first foray into ROS, I have only my nose above the water. I tried editing the file based on some other seeming related issues but this was hit/miss= miss. I assume I have done something, or not done something and I hope you can help me understand and move forward.

**Comment by kijongGil** [comment]
Hi @mickpmack :)
Could you tell me more about your problem? what did you run command? in Turtlebot3 or Remote PC? 
I understand when you are a beginner, you may not know what you have modified. So, I recommend remove and reinstall turtlebot3 packages.

Thanks,
Gilbert
