### ISSUE TITLE
My robot do not move with cmd_vel sent

### ISSUE THREAD

**Issue by angrysword** [ROBOTIS-GIT/turtlebot3#365]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [x] up board

3. Which OS you installed in SBC?

    - [X ] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [1.12.14]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

    1. roslaunch turtlebot3_bringup turtlebot3_robot.launch
    2. rostopic pub -r 10 /cmd_vel geometry_msgs/Twist  '{linear:  {x: 0.1, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.0}}'
    3. robot suppose to move but did not. So I checked the cmd_vel. rostopic echo /cmd_vel. I do saw a lot of message are receiving.
    4. I checked rostopic echo /diagnostics. I found something wired like this, I guess something wrong. because I remember it suppose show some useful things. 

"
header:
  seq: 20
  stamp:
    secs: 1546578630
    nsecs: 546103237
  frame_id: ''
status:
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []
""
       5.  I then update firmware base on this page http://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-firmware-upload-for-tb3. still not move
     6. Then I go this step  Setup Dynamixels for TurtleBot3:  please refer the error at the png file. http://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#setup-dynamixels-for-turtlebot3

    7. when I go back to bringout. I found some new error. I guess it does not matter" the major error is the step 6. 

"ERROR] [1546578809.571690]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
[ERROR] [1546578824.575145]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
[ERROR] [1546578839.579704]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino"

   
![setup motor error](https://user-images.githubusercontent.com/3065257/50674740-d3d8e580-0f9d-11e9-99e8-68d880763ad1.png)

**Comment by routiful** [comment]
I can't help you.
Please write down the issue sheet in detail.

**Comment by kijongGil** [comment]
Hi @angrysword :)
I think that this issue is OpenCR firmware. Could you try to update OpenCR using Arduino?
Refer to [this](http://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#arduino-ide).

Thanks,
Gilbert.

**Comment by angrysword** [comment]
Hi @kijongGil , 

     I have updated the firmware, bringout is good now as it was. However, the problem is still there. It did not move the robot after I pub some cmd_vel. The below is diagnostics info . I think it did not find the motor. 

header:
  seq: 42
  stamp:
    secs: 1546639673
    nsecs: 170895867
  frame_id: ''
status:
  -
    level: 0
    name: "IMU Sensor"
    message: "Good Condition"
    hardware_id: "MPU9250"
    values: []
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []
  -
    level: 0
    name: ''
    message: ''
    hardware_id: ''
    values: []

**Comment by angrysword** [comment]
Hi, 
     I have tested the problem one to let it drive another openCR board turtle3_robot. I found it works very well.    Now it is very clear, the problem is openCR board. However, what I did wrong for the opencr board. Please Help me out. thanks

**Comment by angrysword** [comment]
@routiful @kijongGil any update?

**Comment by routiful** [comment]
Sorry for late reply.
Would you try to scan all Dynamixels after upload DYNAMIXEL-WORKBENCH example?
I attached reference how to upload the firmware.
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/#o_find_dynamixel

**Comment by angrysword** [comment]
did find any thing.
![can not find dynamixel](https://user-images.githubusercontent.com/3065257/51290916-1943dc80-19ba-11e9-9f3e-96d7340c082d.png)

**Comment by kijongGil** [comment]
I think your OpenCR is broken. Please contact to our customer service.
contactus2@robotis.com

Thanks.

**Comment by angrysword** [comment]
thank you very much

**Comment by kijongGil** [comment]
I'm going to close this issue. If you have any question, please ask me.
Thanks.
