### ISSUE TITLE
cartographer installation problem

### ISSUE THREAD

**Issue by extrasleepy** [ROBOTIS-GIT/turtlebot3#367]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [X ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [X ] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ ] Ubuntu MATE 16.04 or later
    - [X ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [1.12.13]
    - Firmware version: [1.2.3]
 
6. Write down the commands you used in order

 sudo apt-get update
sudo apt-get install -y python-wstool python-rosdep ninja-build
mkdir catkin_ws
cd catkin_ws
wstool init src
wstool merge -t src https://raw.githubusercontent.com/googlecartographer/cartographer_ros/master/cartographer_ros.rosinstall
wstool update -t src
src/cartographer/scripts/install_proto3.sh
sudo rosdep init
rosdep update
rosdep install --from-paths src --ignore-src --rosdistro=$kinetic -y
catkin_make_isolated --install --use-ninja
 
7. Copy and Paste your error message on terminal

    ==> Processing plain cmake package: 'cartographer'
==> Building with env: '/home/parallels/catkin_ws/install_isolated/env.sh'
build.ninja exists, skipping explicit cmake invocation...
==> ninja build.ninja in '/home/parallels/catkin_ws/build_isolated/cartographer/install'
ninja: no work to do.
==> ninja -j2 -l2 in '/home/parallels/catkin_ws/build_isolated/cartographer/install'
[7/21] Building CXX object CMakeFiles/car...pping/internal/2d/pose_graph_2d_test.cc.o
FAILED: /usr/bin/c++    -I/home/parallels/catkin_ws/src/cartographer/cartographer -isystem /usr/src/gmock/gtest/include -isystem /usr/include/eigen3 -isystem /usr/include/lua5.2 -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -isystem /usr/local/include -I. -I/home/parallels/catkin_ws/src/cartographer -O3 -DNDEBUG    -pthread -std=c++11 -fPIC  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -pthread -std=c++11 -fPIC  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MMD -MT CMakeFiles/cartographer.mapping.internal.2d.pose_graph_2d_test.dir/cartographer/mapping/internal/2d/pose_graph_2d_test.cc.o -MF CMakeFiles/cartographer.mapping.internal.2d.pose_graph_2d_test.dir/cartographer/mapping/internal/2d/pose_graph_2d_test.cc.o.d -o CMakeFiles/cartographer.mapping.internal.2d.pose_graph_2d_test.dir/cartographer/mapping/internal/2d/pose_graph_2d_test.cc.o -c /home/parallels/catkin_ws/src/cartographer/cartographer/mapping/internal/2d/pose_graph_2d_test.cc
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[7/21] Building CXX object CMakeFiles/cartographer.mapping.internal.2d....apher/mapping/internal/2d/scan_matching/ceres_scan_matcher_2d_test.cc.o
ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer': 
  Command '['/home/parallels/catkin_ws/install_isolated/env.sh', 'ninja', '-j2', '-l2']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/parallels/catkin_ws/build_isolated/cartographer && /home/parallels/catkin_ws/install_isolated/env.sh ninja -j2 -l2

 
8. Please, describe detailedly what difficulty you are in 

I can't seem to install cartographer based on the provided instructions. I've tried these:
http://emanual.robotis.com/docs/en/platform/turtlebot3/slam/#run-slam-nodes
and these:
https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html

Thank you for advice!!

**Comment by routiful** [comment]
We recommanded and tested with below instruction to cartographer install

```
$ sudo apt-get install ninja-build libceres-dev libprotobuf-dev protobuf-compiler libprotoc-dev
$ cd ~/catkin_ws/src
$ git clone https://github.com/googlecartographer/cartographer.git
$ git clone https://github.com/googlecartographer/cartographer_ros.git
$ cd ~/catkin_ws
$ src/cartographer/scripts/install_proto3.sh
$ rm -rf protobuf/
$ rosdep install --from-paths src --ignore-src -r -y --os=ubuntu:xenial
$ catkin_make_isolated --install --use-ninja
```
We've not tested using .rosintall file yet.
Please follow that instructions and re-build it.

**Comment by extrasleepy** [comment]
I gave that a shot but still getting errors. 

[13/51] Building CXX object CMakeFiles...her_ros.dir/cartographer_ros/node.cc.o
FAILED: /usr/bin/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"cartographer_ros\" -isystem /usr/include/lua5.2 -isystem /usr/include/pcl-1.7 -isystem /usr/include/eigen3 -isystem /home/parallels/catkin_ws/install_isolated/include -isystem /opt/ros/kinetic/include -isystem /opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I. -I/home/parallels/catkin_ws/src/cartographer_ros/cartographer_ros -I/usr/src/gmock/gtest/include -isystem abseil/src/abseil -O3 -DNDEBUG    -DEIGEN_USE_NEW_STDVECTOR -DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET -pthread -std=c++11 -fPIC  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MMD -MT CMakeFiles/cartographer_ros.dir/cartographer_ros/node.cc.o -MF CMakeFiles/cartographer_ros.dir/cartographer_ros/node.cc.o.d -o CMakeFiles/cartographer_ros.dir/cartographer_ros/node.cc.o -c /home/parallels/catkin_ws/src/cartographer_ros/cartographer_ros/cartographer_ros/node.cc
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[13/51] Building CXX object CMakeFiles...ir/cartographer_ros/assets_writer.cc.o
ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer_ros': 
  Command '['/home/parallels/catkin_ws/install_isolated/env.sh', 'ninja', '-j2', '-l2']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/parallels/catkin_ws/build_isolated/cartographer_ros && /home/parallels/catkin_ws/install_isolated/env.sh ninja -j2 -l2

Command failed, exiting.

**Comment by extrasleepy** [comment]
Both times it's the same error:
<== Failed to process package 'cartographer_ros':
Command '['/home/parallels/catkin_ws/install_isolated/env.sh', 'ninja', '-j2', '-l2']' returned non-zero exit status 1

**Comment by extrasleepy** [comment]
Actually, I think I have this working now. It turns out that I didn't have enough RAM allocated to my virtual machine and the compiler was crashing. Once I allocated more memory, I was able to compile and run the ros cartographer. Thank you!

**Comment by routiful** [comment]
Great, if you have any futher issues, please feel free to open again.
