### ISSUE TITLE
Version for Melodic and Ubuntu 18.04 timeline.

### ISSUE THREAD

**Issue by BowenY** [ROBOTIS-GIT/turtlebot3#369]
1. Which TurtleBot3 you have?
    - Burger

2. Which SBC(Single Board Computer) is working on TurtleBot3?
    - Raspberry Pi 3

3. Which OS you installed in SBC?
    - Raspbian

4. Which OS you installed in Remote PC?
Two:
    - Ubuntu 18.04 LTS (Bionic Beaver)

//5. Write down software version and firmware version
//6. Write down the commands you used in order
//7. Copy and Paste your error message on terminal
  
8. Please, describe detailedly what difficulty you are in:
    I saw someone asked similar question in Oct, 2018. In this case, I just would love to know is there a good timeline or possible release time of TB3 for Melodic and Ubuntu 18.04 support? Thanks.

**Comment by routiful** [comment]
Hi, Thank you for your inquery.
We are ready to release Melodic support. It will be end up to this month.

**Comment by BowenY** [comment]
@routiful Got it, Thanks for the reply:)

**Comment by mkhuthir** [comment]
@routiful Great News, Thank you very much to all ROBOTIS team.

**Comment by robotpilot** [comment]
FYI, https://github.com/ros/rosdistro/pull/20016

**Comment by robotpilot** [comment]
Released for ROS Melodic
http://repositories.ros.org/status_page/ros_melodic_default.html?q=turtlebot3
