### ISSUE TITLE
Docker container for Turtlebot3

### ISSUE THREAD

**Issue by pitosalas** [ROBOTIS-GIT/turtlebot3#377]
Has anyone created and tested a Docker image for ROS + Turtlebot3?

**Comment by routiful** [comment]
Sorry, we haven't tested a docker yet.

**Comment by pitosalas** [comment]
Ok I have been spending a lot of time trying to get it to work. I am currently stuck with the graphics parts (rviz and gazebo.)

**Comment by jwdinius** [comment]
Has anyone made any progress on this?  I am testing a Dockerfile now that builds an image for the remote PC.  It doesn't really make sense to deploy docker+ROS on the Pi...
