### ISSUE TITLE
ros2 support for turtlebot3_cartographer

### ISSUE THREAD

**Issue by mkhansen-intel** [ROBOTIS-GIT/turtlebot3#382]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ ] Burger
    - [x ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 3
    - [x ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [x ] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

6. Write down the commands you used in order
```
robot@NUC1804:~/turtlebot3_ws/src/turtlebot3/turtlebot3_cartographer$ ros2 launch `ros2 pkg prefix turtlebot3_cartographer`/share/turtlebot3_cartographer/launch/turtlebot3_cartographer.py
 ```
7. Copy and Paste your error message on terminal
```
[ERROR] [launch.LaunchService]: Caught exception in launch (see debug for traceback): executable 'occupancy_grid_node' not found on the libexec directory '/home/robot/cartographer_ws/install/cartographer_ros/lib/cartographer_ros' 
[INFO] [launch]: process[cartographer_node-1]: started with pid [29031]
[INFO] [launch]: sending signal 'SIGINT' to process[cartographer_node-1]
```
  
8. Please, describe detailedly what difficulty you are in 

 
I have teleop working on my turtlebot3 running ROS2 now. So now I want to run cartographer. I see you recently made commits to add occupancy_grid_node to the launch file. When I try to run I get errors. It looks like occupancy_grid_node is not yet ported. Is there any way to run turtlebot3_cartographer yet? If not, what is the status and when do you expect that to work?

**Comment by routiful** [comment]
For now, turtlebot3_cartographer is not working yet. 
I have being ported the cartographer_ros code from ROS to ROS2.
It might be done this week.
I will let you know when it merged and released.

**Comment by mkhansen-intel** [comment]
Thank you for the reply, I will check for an update later this week.

**Comment by routiful** [comment]
@mkhansen-intel 
I've tested cartographer and navigation2 on TurtleBot3 and Gazeob.
If you want to test this, please following attached link
http://emanual.robotis.com/docs/en/platform/turtlebot3/ros2/#ros2

**Comment by routiful** [comment]
@mkhansen-intel 
I try to make map to run map_saver in nav2_map_server package.
However, when I ran that node, it couldn't make map. 

```
$ ros2 run nav2_map_server map_saver -f /map
[INFO] [map_saver]: Waiting for the map
```

**Comment by mkhansen-intel** [comment]
@routiful - I found the same issue. The problem was that cartographer is publishing with different QOS settings than map_saver is subscribing with (map_saver is using default). I manually changed the cartographer_ros code to use the default QOS settings and then I can save the map.

**Comment by routiful** [comment]
@mkhansen-intel 
I've updated the node to modifed QOS settings
https://github.com/ROBOTIS-GIT/cartographer_ros/commit/87464b75115583885477b451b379f033642bbf68

Thank you for your review!

**Comment by mkhansen-intel** [comment]
Looks OK to me, does map_saver work for you now?

**Comment by routiful** [comment]
@mkhansen-intel 
Yes, it worked for my PC.
qos in which `map` subscriber in map_generator.cpp was set default. So I modified qos of map publisher to be set default. 

https://github.com/ros-planning/navigation2/blob/3f65576a98330de0cb832d2c344474b2b604142d/nav2_map_server/src/map_generator.cpp#L55

**Comment by mkhansen-intel** [comment]
Works now, thanks!
