### ISSUE TITLE
Error attempting to launch rviz after bringup successful

### ISSUE THREAD

**Issue by AidanMech** [ROBOTIS-GIT/turtlebot3#395]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ ] Burger
 2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 3
   
3. Which OS you installed in SBC?

    - [ ] Ubuntu MATE 16.04 or later
  
4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
   
5. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order
(launched on remote PC to run Rviz)
  
 $ roslaunch turtlebot3_bringup turtlebot3_remote.launch
$ rosrun rviz rviz -d `rospack find turtlebot3_description`/rviz/model.rviz
 
7. Copy and Paste your error message on terminal

   while processing 
Error Message displayed on Remote PC:

/home/aidanmarch17/catkin_ws/src/turtlebot3/turtlebot3_bringup/launch/includes/description.launch.xml:
Invalid <arg> tag: turtlebot3_description
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/aidanmarch17/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share. 

Arg xml is <arg default="$(find xacro)/xacro --inorder '$(find turtlebot3_description)/urdf/turtlebot3_$(arg model).urdf.xacro'" name="urdf_file"/>
The traceback for the exception was written to the log file
  
8. Please, describe detailedly what difficulty you are in 

  when i attempt to run Rviz, it launches, however many of the directories are absent, and i cannot see a render of the turtlebot in the space. this error message launches when i attempt to launch rviz. i am following th exact steps from http://emanual.robotis.com/docs/en/platform/turtlebot3/bringup/#bringup

I have no errors in previous states and Catkin runs without errors on both te remote PC and turtlebot.

**Comment by ROBOTIS-Kayman** [comment]
Hello, 
I think you did not set the TB3 model for rviz.
If you are using a burger, type the following in terminal.
```
export TURTLEBOT3_MODEL=burger
```

[robotis emanual](http://emanual.robotis.com/docs/en/platform/turtlebot3/bringup/#load-a-turtlebot3-on-rviz) has details.

Thank you.
