### ISSUE TITLE
use deprecated parameter of dwa_local_planner on ROS Melodic

### ISSUE THREAD

**Issue by atinfinity** [ROBOTIS-GIT/turtlebot3#414]
1. Which TurtleBot3 you have?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [x] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [x] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version:
       - base: [melodic-devel](https://github.com/ROBOTIS-GIT/turtlebot3/tree/melodic-devel) branch https://github.com/ROBOTIS-GIT/turtlebot3/commit/73bba8eb1e5348d30905e0e121b2e809e84fa88d
       - apply https://github.com/ROBOTIS-GIT/turtlebot3/commit/69b4563d754ad539d2b2c71fe6f968b3419fb3fb
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

At firtst, I launched gazego simulator.

```shell
$ export TURTLEBOT3_MODEL=waffle_pi
$ roslaunch turtlebot3_gazebo turtlebot3_world.launch
```

And, I launched turtlebot3_navigation package.

```shell
$ export TURTLEBOT3_MODEL=waffle_pi
$ roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=$HOME/maps/world_map.yaml
```
 
7. Copy and Paste your error message on terminal

```
[ WARN] [1557028641.565586073, 8.117000000]: Parameter max_trans_vel is deprecated (and will not load properly). Use max_vel_trans instead.
[ WARN] [1557028641.565840623, 8.117000000]: Parameter min_trans_vel is deprecated (and will not load properly). Use min_vel_trans instead.
[ WARN] [1557028641.566104451, 8.117000000]: Parameter max_rot_vel is deprecated (and will not load properly). Use max_vel_theta instead.
[ WARN] [1557028641.566468154, 8.118000000]: Parameter min_rot_vel is deprecated (and will not load properly). Use min_vel_theta instead.
```

I think that `dwa_local_planner_params_<TURTLEBOT3_MODEL>.yaml` should use appropriate parameters.

**Comment by Daviesss** [comment]
[ WARN] [1557028641.565586073, 8.117000000]: Parameter max_trans_vel is deprecated (and will not load properly). Use max_vel_trans instead.
[ WARN] [1557028641.565840623, 8.117000000]: Parameter min_trans_vel is deprecated (and will not load properly). Use min_vel_trans instead.
[ WARN] [1557028641.566104451, 8.117000000]: Parameter max_rot_vel is deprecated (and will not load properly). Use max_vel_theta instead.
[ WARN] [1557028641.566468154, 8.118000000]: Parameter min_rot_vel is deprecated (and will not load properly). Use min_vel_theta instead.


i also have this error for my simulated robot , please guys how did you solve / fix this issue ?
