### ISSUE TITLE
Total reset of openCR board

### ISSUE THREAD

**Issue by Bwlee605** [ROBOTIS-GIT/turtlebot3#417]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ ] Burger
    - [ ] Waffle
    - [o] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [o] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ ] Ubuntu MATE 16.04 or later
    - [o] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [o] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

    - roslaunch turtlebot3_bringup turtlebot3.robot_roslaunch
 
7. Copy and Paste your error message on terminal

    - could not open port /dev/ttyACM0
  
8. Please, describe detailedly what difficulty you are in 

    1. Is it any way to totally reset the openCR board?

     2. There is an issue that can't find ACM0 port, and we think that it happen if we use power supply from openCR. So we are try to find why, and one possibility is about board problem and it head us to find way of initialize openCR board.

**Comment by RyanJaehyunShim** [comment]
@Bwlee605 

Check out the following link to reset your openCR board.
(http://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup)

As to the second question, it has nothing to do with where you get power from. Please explain in more detail (e.g., photos showing how you connected the robot to pc, error message, etc.) to help us understand what mistakes you made.

Regards,
Ryan
