### ISSUE TITLE
http://emanual.robotis.com/docs/en/platform/turtlebot3/basic_examples/#patrol

### ISSUE THREAD

**Issue by liusanchuan** [ROBOTIS-GIT/turtlebot3#421]
i find the demo  [patrol](http://emanual.robotis.com/docs/en/platform/turtlebot3/basic_examples/#patrol) is not very precision, So i want to combine with move_base to patrol, but i don‘t know how to send the my costumed trajectory path to move_base。

**Comment by RyanJaehyunShim** [comment]
@liusanchuan 

If you would like to know how to use move_base, please refer to the link below.
(http://wiki.ros.org/move_base)

Also, the following link might give you a clue about how you should make modifications to your program.
(https://github.com/ROBOTIS-GIT/turtlebot3/issues/405)

Regards,
Ryan

**Comment by ROBOTIS-Kayman** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
