### ISSUE TITLE
How to reboot OpenCR?

### ISSUE THREAD

**Issue by xingguang95** [ROBOTIS-GIT/turtlebot3#425]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

  Burger

2. Which SBC(Single Board Computer) is working on TurtleBot3?

 Raspberry Pi 3

3. Which OS you installed in SBC?

Ubuntu MATE 16.04 or later

4. Which OS you installed in Remote PC?

 Ubuntu 16.04 LTS (Xenial Xerus)

5. Write down the commands you used in order

    - ROS_NAMESPACE=tb3_0 roslaunch turtlebot3_bringup turtlebot3_robot.launch multi_robot_name:="tb3_0" set_lidar_frame_id:="tb3_0/base_scan"
 
6. Copy and Paste your error message on terminal

Turtlebot3:
    - Failed to get param: timeout expired  
<img width="515" alt="Screen Shot 2019-04-24 at 10 18 49 AM" src="https://user-images.githubusercontent.com/33260768/57722238-fec1fd00-7653-11e9-909e-374585b68fdc.png">

7. Please, describe detailedly what difficulty you are in 

    - I am working on multi-robot mapping. When the turtlebot3 has the error:" Failed to get param: timeout expired" and I run the gmapping in my remote PC, the error below will occur:
<img width="729" alt="Screen Shot 2019-05-14 at 2 27 55 PM" src="https://user-images.githubusercontent.com/33260768/57722915-7ba1a680-7655-11e9-833c-5f331a1489f6.png">
     I found a way to solve this problem from routiful's comment:
<img width="667" alt="Screen Shot 2019-05-14 at 2 38 54 PM" src="https://user-images.githubusercontent.com/33260768/57723178-169a8080-7656-11e9-8a53-827ecda41cd2.png">
   The problem is how to reboot OpenCR?

**Comment by RyanJaehyunShim** [comment]
@xingguang95 

BOOT0(DFU) + PUSH SW1 buttons. Refer to the picture at the link below.
(http://emanual.robotis.com/docs/en/parts/controller/opencr10/#burn-bootloaderwindows)

Regards,
Ryan
