### ISSUE TITLE
Waffle plate on OnShape mismatch real plate

### ISSUE THREAD

**Issue by MattMgn** [ROBOTIS-GIT/turtlebot3#437]
Hi,

CAD on onshape are partially different from actual Turtlebot3 plates. Precise mechanical design of custom parts that can be mounted is not possible without detailed parts.

![bottom_view_tb3_plate_cad](https://user-images.githubusercontent.com/23123503/59381988-f9dc9000-8d5c-11e9-8e7b-a7b4ae6dbcee.JPG)

![bottom_view_tb3_plate_real](https://user-images.githubusercontent.com/23123503/59381841-b8e47b80-8d5c-11e9-92a7-3806737f7ada.JPG)

Could you please upload them?

Regards

Matt

**Comment by RyanJaehyunShim** [comment]
@MattMgn 

As it is our own property, the actual part file is not open to the public. Instead, I suggest you download that part file from Onshape, print it out with the 3D printer, and assemble your turtlebot with it if you need your robot to be exactly the same as the robot model on Onshape.

Regards,
Ryan
