### ISSUE TITLE
Error using gmapping

### ISSUE THREAD

**Issue by gutilacerda** [ROBOTIS-GIT/turtlebot3#441]
I'm trying to open my turtlebot3 burguer in RVIZ with gmapping but I found this:
![gmapping](https://user-images.githubusercontent.com/51960604/60004503-0d48fe80-966d-11e9-840b-52f5cf2c55c6.png)
![warn](https://user-images.githubusercontent.com/51960604/60004507-0d48fe80-966d-11e9-9a03-530303ac5703.png)

And when I follow the guide tutorial:
![map](https://user-images.githubusercontent.com/51960604/60010339-daf0ce80-9677-11e9-8807-d1a650e9623b.png)
![gmapp](https://user-images.githubusercontent.com/51960604/60010340-daf0ce80-9677-11e9-9847-bb0035a08fca.png)

**Comment by nonso1234** [comment]
Try expanding global options and select "Odometry" to generate laser scan. That should probably fix it

**Comment by ROBOTIS-Kayman** [comment]
It is assumed to be a TF problem.
But it's hard to figure out what the problem is exactly.
Please attach the executed command or terminal log.

Regards,
Kayman

**Comment by ROBOTIS-Kayman** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by Adel-kn** [comment]
Hello,
I think the problem is that you have no internet access in your router. Try to connect your router to the internet and the problem will be solved
