### ISSUE TITLE
i want to know how to make 4wheels turtlebot3

### ISSUE THREAD

**Issue by gorangji** [ROBOTIS-GIT/turtlebot3#453]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [ ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [o] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ ] Ubuntu MATE 16.04 or later
    - [o] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [o] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]
 
6. Write down the commands you used in order

    - $ rostopic echo /joint_states
 
7. Copy and Paste your error message on terminal

    - 

![aejfio](https://user-images.githubusercontent.com/53170970/61619294-85750500-aca9-11e9-8384-f185c4d16227.png)

8. Please, describe detailedly what difficulty you are in 
    - i want to make 4wheels robot similar to turtlebot3. and I set the ID of the left, right front wheel to 1, 2. also I set the ID of the left, right behind wheel to 1, 2. 
as a result, i can move this robot with teleop, but i can't get encoder value when i move this robot. Please let me know how i can get the encoder value correctly. or with examples related to 4wheels turtlebot3.

p.s. when i set two wheels, i can get encoder value correctly....

**Comment by rjshim** [comment]
@gorangji 

There is a reference ([TB3 mecanum](https://github.com/Seunghooon/turtlebot3_mecanum)) you might be interested in.

Regards,
Ryan
