### ISSUE TITLE
turtlebot3_simulations now has a transitive dependency on dynamixel_sdk

### ISSUE THREAD

**Issue by ruffsl** [ROBOTIS-GIT/turtlebot3#481]
https://github.com/ROBOTIS-GIT/turtlebot3/blob/a40408994890a40c065930b4ca7233ed29e9dee8/turtlebot3_node/package.xml#L18

Was this necessary? Requiring the dynamixel_sdk is making it a lot harder to using the tb3 for simulation and demos and as a flagship robot with gazebo and ROS2. Could whatever needs the dynamixel_sdk be broken out into its own package, so that turtlebot3_simulations doesn't require an entire embedded sdk? This would make CI a lot easier downstream. cc @mikaelarguedas

**Comment by routiful** [comment]
@ruffsl 
Thank you for your comments. I agreed your opinions.
I've modified turtlebot3_simulation dependency from `turtlebot3` to `turtlebot3_description`.
https://github.com/ROBOTIS-GIT/turtlebot3_simulations/commit/6348394a43bf200bc9679a262a76981eb36db5bc
It will be merged to ros2 branch soon.

**Comment by mikaelarguedas** [comment]
Thanks @ruffsl for the mention, I commented on the PR directly

**Comment by mikaelarguedas** [comment]
@ruffsl can you confirm if https://github.com/ROBOTIS-GIT/turtlebot3_simulations/pull/86 will fix the issue faced on https://github.com/ros-swg/turtlebot3_demo? (It seems we would need to colcon_ignore some turtlebot3 packages if this dependency cannot be satisfied)
