### ISSUE TITLE
Robot goes crazy when running the pointop_key twice

### ISSUE THREAD

**Issue by Pablowally** [ROBOTIS-GIT/turtlebot3#496]
ISSUE TEMPLATE ver. 0.3.0

1. Which TurtleBot3 you have?

    - [ x Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] etc (PLEASE, WRITE DOWN YOUR ROS VERSION HERE)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ x] Gazebo

4. Which OS you installed in SBC?

    - [ ] Raspbian
    - [ ] Ubuntu MATE 16.04 or later
    - [ ] Ubuntu Server 18.04 or later
    - [ x] Ubuntu 16.04

5. Which OS you installed in Remote PC?

    - [ x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] Linux Mint 19.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

6. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Write down the commands you used in order

    - I run the pointop_key node. It asks for coordinates, I input them. As soon as it finishes, it asks again, so I input new coordinates.
The robot starts spinning around and goes out of control.

Coordinates are: 
14,420
15,1,0

8. Copy and Paste your error message on terminal

    - No error message... The robot just spins around.

**Comment by rjshim** [comment]
https://github.com/ROBOTIS-GIT/turtlebot3/issues/497#issue-501065903
