### ISSUE TITLE
Turtlebot3, pass parameters from web server to a python code (Node)

### ISSUE THREAD

**Issue by Adel-kn** [ROBOTIS-GIT/turtlebot3#511]
-Robot: waffle Pi
-SBC: Raspberry Pi 3

OS installed in SBC: Raspbian
OS installed in Remote PC: Ubuntu 16.04 LTS (Xenial Xerus)
ROS version: 1.12.14

hello everyone,
I created a web application that enables the user to enter some parameters from a web page. These parameters will be received (posted) by the webserver.
The web server used in this app was created using a Flask.
The question is how can I use these parameters and pass them as arguments to a python program (code) which drives the robot in a specific way?
OR: 
How can I use my program (code) within the webserver?
Thank in advance

**Comment by ROBOTIS-Will** [comment]
@Adel-kn 
Hi,
The Issues page is intended to discuss the problems or improvements on TurtleBot3 packages.
I recommend you to use [ROS Answers](https://answers.ros.org/questions/) for general questions.
Thank you.
