### ISSUE TITLE
TurtleBot 3 Waffle Pi STL File

### ISSUE THREAD

**Issue by ChDillmann** [ROBOTIS-GIT/turtlebot3#524]
Hello everybody,
why do the stl files (waffle_pi_base.stl and waffle_base.stl) show differences regarding the mounting (position of pcb support) of the laser scanner?
(see following pictures)
    
![waffle_pi_base_stl](https://user-images.githubusercontent.com/54023429/71595117-bc91f100-2b3a-11ea-9914-5dcfc3940f7e.JPG)

![waffle_base_stl](https://user-images.githubusercontent.com/54023429/71595110-b69c1000-2b3a-11ea-83a1-c8510d7ad725.JPG)

**Comment by ROBOTIS-Will** [comment]
@ChDillmann 
Hi, the LIDAR is repositioned to attach OpenMANIPULATOR-X on TurtleBot3 Waffle Pi.

**Comment by master-chrise** [comment]
@ROBOTIS-Will 
Thanks for your answer. It looks like the two file names (waffle_pi_base.stl and waffle_pi_base_for_open_manipulator.stl) on github have been swapped.

**Comment by ChDillmann** [comment]
@ROBOTIS-Will
Thanks for your answer. It looks like the file names (waffle_pi_base.stl and waffle_pi_base_for_open_manipulator.stl) on github have been swapped.

**Comment by ROBOTIS-Will** [comment]
@ChDillmann 
Thank you for reporting the issue. We'll fix the filename correctly.
