### ISSUE TITLE
ROS1 Release with the python 3 fix. 

### ISSUE THREAD

**Issue by bionade24** [ROBOTIS-GIT/turtlebot3#542]
Hello, I'm one of the ROS melodic AUR maintainers. Please make a release with @acxz  python3 patch. If you don't want to do this, please tell us, so that we can patch it.

**Comment by acxz** [comment]
I think this is the specific commit: https://github.com/ROBOTIS-GIT/turtlebot3/commit/ddca617172a3549a3077682cd2cf7dc377616e01

**Comment by ROBOTIS-Will** [comment]
@bionade24 @acxz 
Hi, it had been updated to the most recent ROS1 master branch only, and had not been applied to Melodic branch yet. 
I'll apply this commit on Melodic.
Thank you.

**Comment by bionade24** [comment]
We still don't have a release. When will it come?

**Comment by ROBOTIS-Will** [comment]
@bionade24 
Hi, the change has been applied to melodic branch, so please allow some time to be applied in the binary package.
You can also clone the source and use melodic-devel branch.

**Comment by bionade24** [comment]
We are already patching the files during the build process,
