### ISSUE TITLE
ROS1 or ROS2

### ISSUE THREAD

**Issue by robotiscustomer** [ROBOTIS-GIT/turtlebot3#544]
Hi, 

I am new to ROS. I plan to buy TurtleBot3 (probably Burger but could be Waffle Pi) and OpenManipulator-X. Perhaps OP3 later. In the emanual for both TurtleBot3 and OpenManipulator-X, there is a section on ROS 1 Setup and another section on ROS 2 Setup. Which section am I supposed to follow? Can you let me know which version of ROS is OP3 using?

Also, which version of Ubuntu should I install on my remote PC? From the ROS 2 Setup, the links to Download Ubuntu 18.04 points to 18.04.4 LTS (Bionic Beaver) but Ubuntu 19.10 (Eoan Ermine) has been released. Is it recommended to stay with 18.04.4 LTS or get the latest version of Ubuntu?

**Comment by ROBOTIS-Will** [comment]
@robotiscustomer 
Sorry that I missed this thread. I'll try to catch up on this instead of below forum.
http://en.robotis.com/service/forum_view.php?slg=&page_type=&bbs_no=2407774
