### ISSUE TITLE
Gazebo stereo camera data

### ISSUE THREAD

**Issue by nathangeorge1** [ROBOTIS-GIT/turtlebot3#557]
ISSUE TEMPLATE ver. 0.3.0

1. Which TurtleBot3 you have?

    - [x ] Burger simulated
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [x ] ROS 1 Melodic Morenia
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] etc (PLEASE, WRITE DOWN YOUR ROS VERSION HERE)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

simulated

4. Which OS you installed in SBC?

    - [ ] Raspbian
    - [ ] Ubuntu MATE 16.04 or later
    - [ x] Ubuntu Server 18.04 or later
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] Linux Mint 19.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

6. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

N/A

7. Write down the commands you used in order

    - HERE

N/A

8. Copy and Paste your error message on terminal

    - HERE

N/A

9. Please, describe detailedly what difficulty you are in

    Will the Turtlebot 3 have a launch file that launches a xacro with stereo camera data instead of Lidar?

**Comment by ROBOTIS-Will** [comment]
@nathangeorge1 
Hi, unfortunately we do not provide source code for a customized application unless it is requested as an official project.
You can refer to Waffle Pi to replace the Raspberry Pi cam with a stereo camera.
Thank you for your understanding.

**Comment by nathangeorge1** [comment]
thanks
