### ISSUE TITLE
Inquiry in changing motor

### ISSUE THREAD

**Issue by SJoyTheHawk** [ROBOTIS-GIT/turtlebot3#56]
Hello. I'm a newbie in robot building, I'm afraid the question may seem stupid. 
Can we change the motor in the TurtleBot 3 in order to enhance the maximum velocity in travel? If it is, do we need to configure it in the ROS environment?

**Comment by robotpilot** [comment]
@SJoyTheHawk 

Needs more torques of the Dynamixel? 
You can change it into the higher model, XM430 from XL430. 
Their size and assembly method are the same.

XL430-W350 (Stall Torque = 1.4N.m (at 11.1V, 1.3A))
XM430-W350 (Stall Torque = 3.8N.m (at 11.1V, 2.1A))
