### ISSUE TITLE
Turtlebot 3 Navigation Issue

### ISSUE THREAD

**Issue by tehnanmanna** [ROBOTIS-GIT/turtlebot3#565]
After saving the mapping when I launch navigation in the Rviz I am getting the following errors. Please let me know how to solve it. Check the attachment

![Screenshot from 2020-04-09 03-21-59](https://user-images.githubusercontent.com/61650111/78889577-95698a80-7a6c-11ea-9626-2a72cba25e10.png)

**Comment by roboticslab-fr** [comment]
Did you check the Timesync between TurtleBot3 and Remote PC ?
I had the same issue. It has been solved once I did the synchronization to NTP server on both TurtleBot and Remote PC :
http://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#timesync-between-turtlebot3-and-remote-pc

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there wasn't recent activity. Please feel free to reopen this when needed.
