### ISSUE TITLE
Simulation with Navigation Tutorial - Odometry and Relative Position of the Robot

### ISSUE THREAD

**Issue by ozangungortuhh** [ROBOTIS-GIT/turtlebot3#569]
ISSUE TEMPLATE ver. 0.3.0

1. Which TurtleBot3 you have?

    - [x] Burger Simulation
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [x] ROS 1 Melodic Morenia
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] etc (PLEASE, WRITE DOWN YOUR ROS VERSION HERE)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

4. Which OS you installed in SBC?

    - [ ] Raspbian
    - [ ] Ubuntu MATE 16.04 or later
    - [ ] Ubuntu Server 18.04 or later
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] Linux Mint 19.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

6. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Write down the commands you used in order

- roslaunch turtlebot3_gazebo turtlebot3_world.launch
- roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=$HOME/map.yaml

8. Copy and Paste your error message on terminal

[ WARN] [1587301388.239094507]: Request for map failed; trying again...
[ WARN] [1587301388.408921807, 331.467000000]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 331.467 timeout was 0.1.
[ WARN] [1587301389.071870437, 332.129000000]: global_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1587301389.072218122, 332.130000000]: global_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1587301389.072792353, 332.130000000]: global_costmap: Using plugin "static_layer"
[ INFO] [1587301389.077796208, 332.135000000]: Requesting the map...
[ INFO] [1587301389.280235713, 332.337000000]: Resizing costmap to 384 X 384 at 0.050000 m/pix
[ INFO] [1587301389.380003368, 332.437000000]: Received a 384 X 384 map at 0.050000 m/pix
[ INFO] [1587301389.382628392, 332.439000000]: global_costmap: Using plugin "obstacle_layer"
[ INFO] [1587301389.385791493, 332.442000000]:     Subscribed to Topics: scan
[ INFO] [1587301389.397858572, 332.455000000]: global_costmap: Using plugin "inflation_layer"
[ WARN] [1587301389.429684765, 332.487000000]: local_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1587301389.429928199, 332.487000000]: local_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided

9. Please, describe in detail what difficulty you are in

 - What I am trying to do: Running SLAM and Navigation tutorials successfully with turtlebot3_simulations package using Gazebo and turtlebot3_world
 - I successfully created the map by moving teleop_keyboard and saved it.
 - When I run the the navigation task with turtlebot3_navigation.launch, I get the warning messages I copy-pasted above.
 - When rviz shows up after running turtlebot3_navigation.launch, I initially get this.

![Screenshot from 2020-04-19 15-07-36](https://user-images.githubusercontent.com/43760324/79688596-898d7d80-824f-11ea-8a1e-01c7fed03cac.png)
  
 - At this point, I would like to understand whether it's normal or not. Is the robot suppose to appear in a random point after the initial launch or should the laser scan and the loaded map should be more or less matching? Am I getting this weird match because of the errors displayed while launching the node?

 - When I select 2D Pose Estimate and click on the place where the robot actually is on Gazebo simulation,  and moving/rotating it around a little to let it localize itself, I get the following result, which actually looks accurate.

![Screenshot from 2020-04-19 12-46-06](https://user-images.githubusercontent.com/43760324/79688698-3b2cae80-8250-11ea-96ac-ed92ecfd82ca.png)
 
 - At this point, I would like to understand what should the correct /odom publish values be. Since this it the inital position that we estimated, should it be 0 0 0? In my case, the map looks correct but my odom publishes something like position.x = -2 and position.y = -0.5 which is exactly the distances between the position of the robot from my first image above, where the robot initially appears after running the navigation node for the first time.

header: 
  seq: 31440
  stamp: 
    secs: 1048
    nsecs: 427000000
  frame_id: "odom"
child_frame_id: "base_footprint"
pose: 
  pose: 
    position: 
      x: -2.00012834414
      y: -0.499377554506
      z: -0.00100139400472
    orientation: 
      x: -2.59687525772e-05
      y: 0.00385302931369
      z: 0.00490783327682
      w: 0.999980533142

- I have read through similar issues with the same warning messages, that's why I created this issue to understand if something is wrong at all about my results. Thanks for the help in advance.

**Comment by ROBOTIS-Will** [comment]
@ozangungortuhh 
Hi, I'm sorry for the late response. Your navigation window seems okay. In order to properly run the Navigation, you should set the actual pose of the robot in the map using `2D Pose Estimate` button. When setting the robot pose, it will help amcl algorithm to estimate the current robot location which is described as small green arrows around the robot. As the robot travels further, these arrows will getting closer to the actual location of the robot with better accuracy.
When setting the 2D Pose Estimate, you should click at the actual robot location and drag to the direction where the robot is facing.
Thank you.
