### ISSUE TITLE
ERROR: cannot launch node of type [hls_lfcd_lds_driver/hlds_laser_publisher]: hls_lfcd_lds_drive

### ISSUE THREAD

**Issue by janith29** [ROBOTIS-GIT/turtlebot3#575]
![image](https://user-images.githubusercontent.com/34189753/80152815-fb602100-85d9-11ea-93dc-b7e69b35e545.png)

**Comment by ROBOTIS-Will** [comment]
@janith29 
Could you give us more details on this? such as how you run the code and how we can reproduce this issue on our side, your development environment and so on.

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there wasn't recent activity. Please feel free to reopen this when needed.
