### ISSUE TITLE
How can I get the same map size for all SLAM algorithms?

### ISSUE THREAD

**Issue by Dhaour9x** [ROBOTIS-GIT/turtlebot3#595]
ISSUE TEMPLATE ver. 0.3.0

1. Which TurtleBot3 you have?
    - [x ] Waffle

2. Which ROS is working with TurtleBot3?

    - [ x] ROS 1 Kinetic Kame

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ x] Raspberry Pi 3

4. Which OS you installed in SBC?

    - [ x] Ubuntu MATE 16.04 or later

5. Which OS you installed in Remote PC?

    - [ x] Ubuntu 16.04 LTS (Xenial Xerus)

I 'm currently trying to compare the maps of SLAM algorithms for Alignment, Therefor The SLAM maps size must be the same to get meaningful results.
   I have tried to create maps of the gazebo Environment with the following SLAM Algorithms (gmapping, hector, karto and cartographer) on TB3 waffle.
I got very different map size of the generated SLAM maps. Although resolution value is 0.05 for all SLAM algorithms.
here the size of SLAM maps:

SLAM |Gmapping SLAM | Hector SLAM | karto SLAM | Cartographer
----------- | ------------ | ------------- | ------------- | ---------------
Width | 384| 2048 | 71 | 61
Height | 384| 2048 | 82 | 99
Maps | ![gmap](https://user-images.githubusercontent.com/47638846/83330659-ed648680-a290-11ea-8d89-ab86cbdea87b.jpg) | ![hmap](https://user-images.githubusercontent.com/47638846/83330667-f6edee80-a290-11ea-9780-a7689f4e22ee.jpg) | ![kmap](https://user-images.githubusercontent.com/47638846/83330671-0705ce00-a291-11ea-8d6f-1925b95bf0f7.jpg) |  ![cmap](https://user-images.githubusercontent.com/47638846/83330672-0f5e0900-a291-11ea-8b25-aaf1f2fde4f4.jpg)

how can I get  the same Maps size of all SLAM algorithms. for example like this 
![map_hector](https://user-images.githubusercontent.com/47638846/83332119-99aa6b00-a299-11ea-85b9-b799db77befa.jpg)

I have used a Image editor such as **ImageMagik** to resize the maps, but it has bad impact on the shape of the Environment. 

I have used the following commands for each SALM.
    - roslaunch turtlebot3_gazebo navibot.launch
![gazeboEnvi](https://user-images.githubusercontent.com/47638846/83329798-bcce1e00-a28b-11ea-8da8-32da4d515ff6.png)#
    - roslaunch turtlebot3_slam turtlebot3_slam slam_methods:=gmapping
    - roslaunch turtlebot3_slam turtlebot3_slam slam_methods:=hector
    - roslaunch turtlebot3_slam turtlebot3_slam slam_methods:=karto
    - roslaunch turtlebot3_slam turtlebot3_slam slam_methods:=cartographer

I hope you can help me :)

**Comment by ROBOTIS-Will** [comment]
Hi,
The map images are created by their own SLAM algorithm and I don't think we can make them to give us the same result for the identical environment. 
I could be wrong as I'm not an expert on SLAM.
It looks like we can easily manipulate the size of Hector map by adjusting the `map_size` parameter in the `turtlebot3_hector.launch` file. 
However, this will not allow us to have a rectangular map image like the Cartographer as the map size of Hector mapping is already defined [here](http://wiki.ros.org/hector_mapping/#Parameters) with map_size * map_size square grid.
Thank you.

**Comment by Dhaour9x** [comment]
In this situation, where the maps that I got are not having the same size, I have to perform "Image registration" https://github.com/Dhaour9x/Image-Registration. The assumption is, I try to align map2, map3 and map4, with the same scale as Ground truth map.

my question is, does this method make sense to solve the problem and is the comparison between ground truth map and registered (edited) maps reliable?? 

Thank you

**Comment by ROBOTIS-Will** [comment]
I'm sorry for the late reply.
As long as you can keep the map resolution same as original file, modifying the image should be fine.
Each pixel is defined to represent certain distance in each algorithm.
Thank you.

**Comment by Dhaour9x** [comment]
Thank you @ROBOTIS-Will
