### ISSUE TITLE
Foxy Release

### ISSUE THREAD

**Issue by spragunr** [ROBOTIS-GIT/turtlebot3#599]
I'm just wondering when there will be an official Foxy release?  I see that there is a foxy_devel branch.  I just received several TB3 that I will be using for a course in the fall.  Working with our sysadmin will be simplified if there are deb packages available. I see #561 is open, but Eloquent is EOL in just a few months.

**Comment by ROBOTIS-Will** [comment]
Hi,
We're expecting that the Foxy support will be available from August.
As you already know, Eloquent will not be supported while we are focusing on Foxy.

**Comment by rafaelhuang-intel** [comment]
Hi ,

Doed any update of foxy release ? 

Currently, Yocto only found dashing version (.0.2.6) under Yocto Dunfell, and I also hope to know what time we can use foxy version on Yocto?

**Comment by ruffsl** [comment]
Looks like the turtlebot3 packages are still missing from the foxy release, making it tricky to support ROS2 Foxy for the upcoming fall semester:

http://repo.ros2.org/status_page/compare_dashing_foxy.html

Indeed, it would be helpful to have an educational robot platform released into the current ROS2 LTS.

**Comment by ROBOTIS-Will** [comment]
Hi @rafaelhuang-intel @ruffsl ,
Thank you all for the interest in this issue.
We're currently working/testing on Foxy with Raspberry Pi3B+, but having some issues with Ubuntu crashing(#593).
I'll try to release the Foxy as soon as possible.
We'll review to release on Yocto.

**Comment by andrestoga** [comment]
@ROBOTIS-Will Did you guys already test it with the kernel fixed in Focal?

**Comment by SebO-L** [comment]
Hi, 
I'm a ROS2 newcomer and I was waiting for the foxy release. I'd like to report a successful installation (burger bot)
- PC and raspberry on focal &ros2 foxy 
- Turtlebot packages install with the foxy-devel branch.

So far the navigation is up. I have been able to save the map and navigate (odometry ok)
Thanks for our work

**Comment by DLu** [comment]
It might be worthwhile to do a release of the parts that are working (i.e. the description) so things like the navigation tutorials can be used in Foxy, even if the real robot cannot.

**Comment by DLu** [comment]
This is probably closed via https://github.com/ros/rosdistro/pull/26975, right?

**Comment by ROBOTIS-Will** [comment]
@DLu Yes, TurtleBot3 Foxy package has been released.
We've tested it with the latest Ubuntu 20.04 preinstalled server image for Raspberry Pi 3B+ and preparing to support RPi 4B in the next year.

**Comment by rafaelhuang-intel** [comment]
I meet a issue of turtlebot3 navigaiton & Rviz (https://github.com/ROBOTIS-GIT/turtlebot3/issues/677 ), does anyone meet same?

**Comment by ROBOTIS-Will** [comment]
This issue thread will be closed as TurtleBot3 Foxy has been released. Please feel free to reopen if needed.
