### ISSUE TITLE
Teleop Not working/ Turtlebot not moving

### ISSUE THREAD

**Issue by ishaanmht** [ROBOTIS-GIT/turtlebot3#617]
ISSUE TEMPLATE ver. 0.3.0

1. Which TurtleBot3 you have?

    - [ x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] etc (PLEASE, WRITE DOWN YOUR ROS VERSION HERE)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [x ] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

4. Which OS you installed in SBC?

    - [x ] Raspbian
    - [ ] Ubuntu MATE 16.04 or later
    - [ ] Ubuntu Server 18.04 or later
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Which OS you installed in Remote PC?

    - [x ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] Linux Mint 19.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

6. Write down software version and firmware version

    - Software version: [x.x.x]
    - Firmware version: [1.2.3]

7. Write down the commands you used in order

    - roscore (remote pc)
    - turtlebot3_bringup.launch (turtlebot3)
    - export TURTLEBOT3_MODEL=burger, turtlebot3_remote.launch (remote pc)
    - export TURTLEBOT3_MODEL=burger, turtlebot3_teleop.launch (remote pc)

8. Copy and Paste your error message on terminal

    - HERE

9. Please, describe detailedly what difficulty you are in

    - The values to move turtlebot are being published on /cmd_vel but the turtlebot doesnt move. ALthough if you press SW! and SW2 on the opencr board the turtleboard displays desired motion.

**Comment by ashekim** [comment]
@ishaanmht 
hello @ishaanmht 

Please refer to the shown in the eManual.
https://emanual.robotis.com/docs/en/platform/turtlebot3/pc_setup/#network-configuration

ROS 1 requires IP addresses in order to communicate between TurtleBot PC and the remote PC. 
The remote PC and TurtleBot PC should be connected to the same wifi router.

Thank you.

**Comment by ishaanmht** [comment]
I did follow these steps. Turns out that somehow I need to export ROS_MASTER_URI on my remote PC even though its on my ~/.bashrc
