### ISSUE TITLE
question on building TurtleBot3 Friend Conveyor?

### ISSUE THREAD

**Issue by stevensu1838** [ROBOTIS-GIT/turtlebot3#638]
Hi team,

I am a user of turtlebot3 and I am trying to build a TurtleBot3 Friends: Conveyor. However, the instruction on how to assembly it is not enough for me. Like I don't exactly know **how to connect 8 motors to one OpenCR board**. Could you please send me some details instructions on building TurtleBot3 Friends Conveyor? Thanks a lot.

Looking forward to hearing from you soon. Cheers.

**Comment by ashekim** [comment]
@stevensu1838 
Hi @stevensu1838 . Thank you for your questions.

Probably, I know that my colleague sent you an answer. 
If you need additional answers, please comment again.

Thank you.

**Comment by stevensu1838** [comment]
Hi Team,
Just checked the email and I got the following answer:

To connect wheels to OpenCR Board, please see the following image. You can adopt a daisy chain to connect between DYNAMIXEL and OpenCR 1.0. 
![image](https://user-images.githubusercontent.com/25648734/93078316-653eab80-f6de-11ea-9c64-1189f4dd98bd.png)

I just want to double check that do I really connect all the eight XL430-W250-T motor in a chain like this? Any chance you can share a pic of your Conveyor robot?

OpenCR_Monster.png

My last question is the two motors come with turtlebot kit are already set up and assigned ID 1 and ID 2. May I please ask what shall I do with the extra six XL430-W250-T motors I bought from you and make them work with OpenCR for TurtleBot3 Friend Conveyor?

**Comment by ashekim** [comment]
@stevensu1838 
Hi, again.

1. Please refer to this image

-front
![image](https://user-images.githubusercontent.com/61770300/93154489-b1b9d380-f73e-11ea-8cac-f1d4a8b5dcf5.png)

-back
![image](https://user-images.githubusercontent.com/61770300/93154463-9e0e6d00-f73e-11ea-8c6d-2217263b06ba.png)


2. Please refer to the link for Dynamixel ID setting.
[2.4.1.1 Dynamixel2Arduino Class](https://emanual.robotis.com/docs/en/popup/arduino_api/setID/)
[5.2 OpenCR and OpenCM Tutorials](https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/#opencr-and-opencm-tutorials)

Thank you.

**Comment by ROBOTIS-Will** [comment]
@stevensu1838 You can also distribute the DYNAMIXEL as evenly as possible for available OpenCR DYNAMIXEL ports.

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
