### ISSUE TITLE
Could not open file turtlebot3_burguer.urdf for parsing

### ISSUE THREAD

**Issue by andrestoga** [ROBOTIS-GIT/turtlebot3#640]
ISSUE TEMPLATE ver. 0.3.0

1. Which TurtleBot3 you have?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [x] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] etc (PLEASE, WRITE DOWN YOUR ROS VERSION HERE)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [x] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

4. Which OS you installed in SBC?

    - [ ] Raspbian
    - [x] Ubuntu MATE 16.04 or later
    - [ ] Ubuntu Server 18.04 or later
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] Linux Mint 19.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

6. Write down software version and firmware version

    - Software version: [ros2 branch commit fb6b9ac]
    - Firmware version: [0.0.3] for ROS2

7. Write down the commands you used in order

ros2 launch turtlebot3_bringup robot.launch.py

8. Copy and Paste your error message on terminal

andrestoga@andrestoga-pi:~/turtlebot3_ws$ ros2 launch turtlebot3_bringup robot.launch.py
[INFO] [launch]: All log files can be found below /home/andrestoga/.ros/log/2020-09-19-13-16-32-654675-andrestoga-pi-10298
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : turtlebot3_burguer.urdf
[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: /home/andrestoga/turtlebot3_ws/install/turtlebot3_bringup/share/turtlebot3_bringup/param/burguer.yaml
[INFO] [robot_state_publisher-1]: process started with pid [10308]
[INFO] [hlds_laser_publisher-2]: process started with pid [10309]
[INFO] [turtlebot3_ros-3]: process started with pid [10310]
[robot_state_publisher-1] Initialize urdf model from file: /home/andrestoga/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_burguer.urdf
[robot_state_publisher-1] Could not open file [/home/andrestoga/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_burguer.urdf] for parsing.
[robot_state_publisher-1] Unable to initialize urdf::model from /home/andrestoga/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_burguer.urdf
[ERROR] [robot_state_publisher-1]: process has died [pid 10308, exit code 255, cmd '/opt/ros/dashing/lib/robot_state_publisher/robot_state_publisher /home/andrestoga/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_burguer.urdf __node:=robot_state_publisher __params:=/tmp/launch_params_yqolkdni'].
[turtlebot3_ros-3] terminate called after throwing an instance of 'std::runtime_error'
[turtlebot3_ros-3]   what():  Failed to parse parameters from file '/home/andrestoga/turtlebot3_ws/install/turtlebot3_bringup/share/turtlebot3_bringup/param/burguer.yaml': Error opening YAML file, at /tmp/binarydeb/ros-dashing-rcl-yaml-param-parser-0.7.9/src/parser.c:1387
[ERROR] [turtlebot3_ros-3]: process has died [pid 10310, exit code -6, cmd '/home/andrestoga/turtlebot3_ws/install/turtlebot3_node/lib/turtlebot3_node/turtlebot3_ros -i /dev/ttyACM0 __params:=/home/andrestoga/turtlebot3_ws/install/turtlebot3_bringup/share/turtlebot3_bringup/param/burguer.yaml'].

9. Please, describe detailedly what difficulty you are in

I can't bring up turtlebot3 from the e-manual step 2:
https://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_bringup/

**Comment by ROBOTIS-Will** [comment]
Hi, I'm sorry for the confusion. We're currently undergoing some changes in the manual.
Could you try using `dashing-devel` branch instead of `ros2`?
Also, for Dashing, it is recommended to use Ubuntu 18.04, but please be aware that there is an ongoing issue (#593) with Ubuntu 18.04 and 20.04.
Thank you.

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't recent activity. Please feel free to reopen when necessary.
