### ISSUE TITLE
Turtlebot3 Omni with ROS: turtlebot3_core OpenCR code missing

### ISSUE THREAD

**Issue by zack-research** [ROBOTIS-GIT/turtlebot3#661]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [x] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed in SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] etc (Please specify your OS here)

---

I have successfully run the OpenCR example code turtlebot3_omni via https://github.com/ROBOTIS-GIT/OpenCR/tree/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/examples/turtlebot3_friends/turtlebot3_omni to control my turtlebot omni via the RC100 bluetooth remote.

However, I need to use ROS for my application and see that the burger and waffle variants have turtlebot3_core_(variant) code that runs with ROS. Does a turtlebot_core_omni exist for ROS support with the omni? I have been unable to successfully integrate the files from turtlebot3_omni with the existing turtlebot3_core_waffle files.

**Comment by ROBOTIS-Will** [comment]
Hi @zack-research ,
Unfortunately, TB3 friends examples are not provided as ROS examples and you will need to modify the TurtleBot3 core example.
Thank you.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
