### ISSUE TITLE
Really big bag file

### ISSUE THREAD

**Issue by allenh1** [ROBOTIS-GIT/turtlebot3#68]
In the turtlbot3_slam package, there's a really large bag file (68 MB) that makes it into the debian packages. It would be really great if that could be avoided, and replaced with a `catkin_download` instead.

**Comment by routiful** [comment]
Hi :)

We changed STL files are more smaller than before.
Thank you to your advice.

Thanks
Darby

**Comment by allenh1** [comment]
Could you remove the bag file too please? The `turtlebot_slam` package has a large bag file that gets included in the system binaries. You could change that to a `catkin_download_test_data` and host the file elsewhere.

**Comment by robotpilot** [comment]
We removed large bag file in SLAM package. Thank you! :)
https://github.com/ROBOTIS-GIT/turtlebot3/releases/tag/0.2.0

**Comment by allenh1** [comment]
Thanks! :tada:

**Comment by allenh1** [comment]
Thanks! :tada:
