### ISSUE TITLE
Creating SLAM in Rviz2

### ISSUE THREAD

**Issue by sfx-takei** [ROBOTIS-GIT/turtlebot3#688]
I'm sorry if it's a poor sentence.
We would appreciate it if you could read the question and answer it.

### Your enviroment
* Ubuntu MATE 18.04 
* ROS2 Dashing
* Gazebo9
* Rviz2

### Subject of the issue
I'm trying to validate SLAM with Rviz2.
However, the map cannot be displayed at the stage of forming the map with Cartographer.

### Steps to reproduce
You need to have the official ROS Turtlebot3 package installed / set up in advance.
First, start Gazebo of Tutrlebot3.
```
$ ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
```
Then start Cartographer.
```
$ ros2 launch turtlebot3_cartographer cartographer.launch.py use_sim_time:=True
```

### Expected behaviour
Within Rviz2, form the map acquired by Tutrlebot3.
![スクリーンショット 2020-12-22 112532](https://user-images.githubusercontent.com/76137365/102841514-6e12ec00-4448-11eb-93cf-604e57e96b9b.png)

### Actual behaviour
No map is formed and Map always returns "No map received".
![スクリーンショット 2020-12-22 112823](https://user-images.githubusercontent.com/76137365/102841800-f1ccd880-4448-11eb-828d-0021eec80075.png)

### Log
```
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]:  submap_slices and last_frame_id id empty
```

**Comment by ROBOTIS-Will** [comment]
Hi @sfx-takei 
Thank you for reporting the issue.
I'll take a look at it and get back to you soon.

**Comment by kantengri** [comment]
added these remappings to cartographer.launch.py from turtlebot3_cartographer:
    remappings=[
            ('/scan', '/turtlebot3_laserscan/out'),
            ('/imu', '/turtlebot3_imu/out'),
    ]
for each node: rviz, cartographer_node,
now it works

**Comment by ROBOTIS-Will** [comment]
@sfx-takei 
Could you test this with the latest code in `dashing-devel` of turtlebot3 and turtlebot3_simulations package?
Updated pacakage will be released within a couple week.

**Comment by sfx-takei** [comment]
@kantengri 
Thank you for your reply.
When I tried remapping as you said,
The cartographer has started successfully!
Much obliged. Thank you!

**Comment by sfx-takei** [comment]
@ROBOTIS-Will 
Thank you for your reply.
I also tested in the same environment as you.
As a result it worked fine!

**Comment by ROBOTIS-Will** [comment]
@sfx-takei 
Thank you for the update. Please don't forget to close the issue if it is resolved.
Happy New Year!
