### ISSUE TITLE
Turtlebot3 motors not working

### ISSUE THREAD

**Issue by mdevlieg** [ROBOTIS-GIT/turtlebot3#693]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ X] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.

   I am following the getting started tutorial from https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/ and when it gets to where I upload firmware to the OpenCR this is done without any errors, but when I test the robot using SW1 and SW2 nothing happens. I am brand new to Ubuntu and raspberry pi so I was wondering if I could get some pointers. Thanks!

**Comment by ashekim** [comment]
@mdevlieg 
Hi. Thank you for your questions.

Did you run [3.5 Bring up](https://emanual.robotis.com/docs/en/platform/turtlebot3/bringup/#bringup) and [3.6 Teleoperation](https://emanual.robotis.com/docs/en/platform/turtlebot3/basic_operation/#basic-operation) ?

Could you please copy and paste each terminal output so that I can check if all process is running correctly?

Thank you. 
And Happy New Year~! :)

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
