### ISSUE TITLE
Error in cartographer installation for jackal robot

### ISSUE THREAD

**Issue by rkd1995** [ROBOTIS-GIT/turtlebot3#696]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [X] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [X] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [1.02]

7. Specify the commands or instructions to reproduce the issue.

    https://github.com/jackal/jackal_cartographer_navigation/tree/master
I have used the instructions provided for the master branch to install the jackal robot cartographer.

8. Copy and Paste the error messages on terminal.

    -- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found GMock: gmock_main;-lpthread  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   regex
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/include
-- Found Ceres version: 1.11.0 installed in: /usr/local
-- Found Lua: /usr/local/lib/liblua.a;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.3.4") 
-- Found Protobuf: /home/rkd1995/catkin_ws/cartographer_ws/protobuf/install/lib/libprotobuf.a (Required is at least version "3.0.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'cairo>=1.12.16'
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rkd1995/catkin_ws/cartographer_ws/build_isolated/cartographer/install
==> ninja -j12 -l12 in '/home/rkd1995/catkin_ws/cartographer_ws/build_isolated/cartographer/install'
[203/298] Linking CXX executable carto...r.common.lua_parameter_dictionary_test
FAILED: : && /usr/bin/c++   -O3 -DNDEBUG   CMakeFiles/cartographer.common.lua_parameter_dictionary_test.dir/cartographer/common/lua_parameter_dictionary_test.cc.o  -o cartographer.common.lua_parameter_dictionary_test  -rdynamic libcartographer.a gmock/libgmock_main.a -lpthread /usr/local/lib/libceres.a -lglog -lspqr -ltbb -ltbbmalloc -lcholmod -lccolamd -lcamd -lcolamd -lamd -llapack -lf77blas -latlas -lsuitesparseconfig -lrt -llapack -lf77blas -latlas -lsuitesparseconfig -lrt -lgomp /usr/local/lib/liblua.a -lm -lboost_iostreams -lboost_regex -lglog -lgflags -lcairo /home/rkd1995/catkin_ws/cartographer_ws/protobuf/install/lib/libprotobuf.a -lpthread -lpthread && :
/usr/bin/ld: /usr/local/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[203/298] Building CXX object CMakeFil...ph/landmark_cost_function_2d_test.cc.o
ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer': 
  Command '['ninja', '-j12', '-l12']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/rkd1995/catkin_ws/cartographer_ws/build_isolated/cartographer && ninja -j12 -l12

Command failed, exiting.
source install_isolated/setup.bash
bash: install_isolated/setup.bash: No such file or directory

9. Please describe the issue in detail.

    I am trying to run cartographer with jackal robot. Initially I had issues with ceres solver and lua. I re-installed them and the cartographer installation process did start but it failed after a while. 

I followed the instructions provided in the github
https://github.com/jackal/jackal_cartographer_navigation/tree/master

Thank You for the advice!

**Comment by ROBOTIS-Will** [comment]
Hi,

Inquired package is not developed / maintained by ROBOTIS.
Please submit an issue ticket on [jackal's repository](https://github.com/jackal/jackal_cartographer_navigation/issues) if you need further assistant.
Thank you.
