### ISSUE TITLE
Installing a new motor

### ISSUE THREAD

**Issue by royito55** [ROBOTIS-GIT/turtlebot3#699]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [x] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [x] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.

    One of my motors broke so I bought a new one from ROBOTIS, same model. However, I noticed that they are not labeled with the ID indicator like the original ones. When I did the movement test by pushing the buttons on the OpenCR board to make the motors move, the new one didn't work. Is there anything specific to install this new motor?

**Comment by ROBOTIS-Will** [comment]
Hi @royito55 
Before replacing DYNAMIXEL, it has to be configured using DYNAMIXEL Setup Arduino example.
Please see below instructions and configure the DYNAMIXEL properly, then recover the OpenCR with TurtleBot3 firmware.
https://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#setup-dynamixels-for-turtlebot3
Thank you.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
