### ISSUE TITLE
Turtlebot Mecanum Remote Control Front wheels do not spin.

### ISSUE THREAD

**Issue by Mokiegmo** [ROBOTIS-GIT/turtlebot3#701]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi
    - [ x] Mecanum

2. Which ROS is working with TurtleBot3?

    - [ x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [x ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - Go through turtlebot quick start guide
    - Upload Mecanum eample code from Arduino IDE
    - Using Remote control RC100B Move Robot

8. Copy and Paste the error messages on terminal.

     None

9. Please describe the issue in detail.

    I went through the quick start guide (standard turtlebot3 first) and got Navigation and Slam to work to check everything is set up correct.
    Now, I went back using the Dynamixel Wizard application, and the usbtodxl arduino code, to set my front left and front right motors to ID's 3 and 4 and baud rates to 1mbs (as stated in the mecanum code). Then I upload the turtlebot3 friends example code Mecanum onto the OpenCR. I connect my remote control and only the back two motors spin. 

Is there anything else that would limit my front motors responding to input?

Side question, I can build my own ROS packages for mecanum to create something similar to the given SLAM, correct? I noticed I cannot run bring up when the Mecanum code is on the OpenCR. Would it be easier to adjust the Arduino code to make it work with the standard Turtlebot ROS packages, or create new ROS packages?

Thanks in advance,
Austin

**Comment by ROBOTIS-Will** [comment]
Hi @Mokiegmo 
You have correctly set the ID and the Baud rate, but you also have to set the `Operating Mode` to `Velocity Control` mode as below.
![image](https://user-images.githubusercontent.com/26239359/107895788-e513bf00-6f77-11eb-9225-c6c6ac04f496.png)

I think it would be easier to start with modifying the existing example.
Please also note when modifying the hardware design, you should take care of the URDF as well.
Thank you.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
