### ISSUE TITLE
TB3-Manipulation manual links to a deprecated library

### ISSUE THREAD

**Issue by goekce** [ROBOTIS-GIT/turtlebot3#705]
https://github.com/ROBOTIS-GIT/emanual/blob/master/_includes/en/platform/turtlebot3/manipulation/manipulation_software_setup_dashing.md contains a link to the repo https://github.com/ROBOTIS-GIT/open_manipulator_with_tb3.git which seems to be deprecated.

Is the new repository https://github.com/ROBOTIS-GIT/turtlebot3_manipulation?

If the new repo is included in the manual there would be less confusion for the user.

**Comment by ROBOTIS-Will** [comment]
Hi @goekce,
Sorry about the confusion and delayed response on this issue.
The `open_manipulator_with_tb3.git` contains ROS2 example of TurtleBot3 with OpenMANIPULATOR-X while `turtlebot3_manipulation` deals with ROS1 example.
Thank you.

**Comment by goekce** [comment]
@ROBOTIS-Will does this mean that OpenMANIPULATOR-X will not be supported for ROS2?

**Comment by ROBOTIS-Will** [comment]
@goekce 
The OpenMANIPULATOR currently supported in Dashing and will be updated to support the latest ROS2 including ROS1.
The exact schedule has not been confirmed yet, but I think it will begin in 2Q of this year.

**Comment by goekce** [comment]
@ROBOTIS-Will good to hear that!

I understand that `open_manipulator_with_tb3.git` supports ROS2 Dashing and will be updated to support the latest ROS2 distro.

Why did `open_manipulator_with_tb3.git` then got archived?

**Comment by ROBOTIS-Will** [comment]
@goekce 
The repository was once corrupted with improper branch merging in the past and I separated the usable commit for later work.
Most likely the update will be based on the archived source code.

**Comment by goekce** [comment]
Thanks Will!
