### ISSUE TITLE
unable to contact ROS master at [http://{10.0.0.xxx}:11311] The traceback for the exception was written to the log file

### ISSUE THREAD

**Issue by Paulino1956** [ROBOTIS-GIT/turtlebot3#706]
got this message:" unable to contact ROS (running on Melodic) master at [http://{10.0.0.xxx}:11311] The traceback for the exception was written to the log file" 
after running on shell 1  pi@raspberrypi:~ $ roslaunch turtlebot3_bringup turtlebot3_robot.launch

while open shell 2 (master) running $roscore

at screen:

NODES

auto-starting new master
process[master]: started with pid [14369]
ROS_MASTER_URI=http://10.0.0.xxx:11311/

setting /run_id to 6972849e-6bd0-11eb-9cce-d8c0a6261e0f
process[rosout-1]: started with pid [14380]
started core service [/rosout]
(STOPPED HERE)

Thanks in advance for you help !

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity.
