### ISSUE TITLE
Issues controlling OpenManipulator-X using Rviz or Robotics GUI Controller

### ISSUE THREAD

**Issue by Prajwalmj** [ROBOTIS-GIT/turtlebot3#712]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [v1.1.0]
    - Firmware version: [v2.0.1]

7. Specify the commands or instructions to reproduce the issue.

```bash
roslaunch turtlebot3_bringup turtlebot3_robot.launch     # warning message, [TurtleBot3 SBC]
roslaunch turtlebot3_manipulation_moveit_config move_group.launch     # error message
roslaunch turtlebot3_manipulation_moveit_config moveit_rviz.launch    # warning message
roslaunch turtlebot3_manipulation_gui turtlebot3_manipulation_gui.launch     # warning message
```

8. Copy and Paste the error messages on terminal.

    - Message from Rviz
    ```text
    process[rviz_larx_dell_3_12574_671864932024397051-1]: started with pid [12591]
    [ INFO] [1615494672.447645911]: rviz version 1.12.17
    [ INFO] [1615494672.447719651]: compiled against Qt version 5.5.1
    [ INFO] [1615494672.447741376]: compiled against OGRE version 1.9.0 (Ghadamon)
    [ INFO] [1615494673.405339469]: Stereo is NOT SUPPORTED
    [ INFO] [1615494673.405402698]: OpenGl version: 4.6 (GLSL 4.6).
    [ INFO] [1615494677.058774560]: Loading robot model 'turtlebot3_manipulation'...
    [ INFO] [1615494677.178108958]: Loading robot model 'turtlebot3_manipulation'...
    [ INFO] [1615494677.251028366]: Using position only ik
    [ INFO] [1615494678.045440080]: Starting scene monitor
    [ INFO] [1615494678.050857070]: Listening to '/move_group/monitored_planning_scene'
    [ WARN] [1615494678.068002098]: The STL file 'package://turtlebot3_description/meshes/bases/waffle_pi_base_for_open_manipulator.stl' is malformed. It starts with the word 'solid', indicating that it's an ASCII STL file, but it does not contain the word 'endsolid' so it is either a malformed ASCII STL file or it is actually a binary STL file. Trying to interpret it as a binary STL file instead.
    [ WARN] [1615494678.222174656]: The STL file 'package://turtlebot3_description/meshes/sensors/lds.stl' is malformed. It starts with the word 'solid', indicating that it's an ASCII STL file, but it does not contain the word 'endsolid' so it is either a malformed ASCII STL file or it is actually a binary STL file. Trying to interpret it as a binary STL file instead.
    [ INFO] [1615494678.540309554]: Constructing new MoveGroup connection for group 'arm' in namespace ''
    [ INFO] [1615494679.534870386]: Ready to take commands for planning group arm.
    [ INFO] [1615494679.534969697]: Looking around: no
    [ INFO] [1615494679.535007713]: Replanning: no
    [ WARN] [1615494679.562849546]: Interactive marker 'EE:goal_end_effector_link' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.
    ```
    - Message from move group
    ```text
    [ INFO] [1615495269.463042619]: RRTConnect: Created 1 states (1 start + 0 goal)
    [ INFO] [1615495269.463078131]: No solution found after 0.040732 seconds
    [ INFO] [1615495269.463135740]: Unable to solve the planning problem
    [ INFO] [1615495276.913255637]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
    [ INFO] [1615495276.914051234]: Planner configuration 'arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
    [ INFO] [1615495276.914382631]: RRTConnect: Starting planning with 1 states already in datastructure
    [ INFO] [1615495276.945591407]: Constraint satisfied:: Joint name: 'joint1', actual value: 0.000018, desired value: 0.000000, tolerance_above: 0.000100, tolerance_below: 0.000100
    [ INFO] [1615495276.945643830]: Constraint satisfied:: Joint name: 'joint2', actual value: 0.000066, desired value: 0.000000, tolerance_above: 0.000100, tolerance_below: 0.000100
    [ INFO] [1615495276.945662140]: Constraint satisfied:: Joint name: 'joint3', actual value: 0.999915, desired value: 1.000000, tolerance_above: 0.000100, tolerance_below: 0.000100
    [ INFO] [1615495276.945679417]: Constraint satisfied:: Joint name: 'joint4', actual value: 0.999985, desired value: 1.000000, tolerance_above: 0.000100, tolerance_below: 0.000100
    [ INFO] [1615495276.945761178]: Found a contact between 'gripper_link_sub' (type 'Robot link') and 'base_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
    [ INFO] [1615495276.945791154]: Collision checking is considered complete (collision was found and 0 contacts are stored)
    [ERROR] [1615495276.965027052]: RRTConnect: Unable to sample any valid states for goal tree
    ```
    - Message from bringup
    ```text
    process[turtlebot3_core-1]: started with pid [1215]
    process[turtlebot3_lds-2]: started with pid [1216] 
    process[turtlebot3_diagnostics-3]: started with pid [1217]
    [INFO] [1615494587.698131]: ROS Serial Python Node
    [INFO] [1615494587.728646]: Connecting to /dev/ttyACM0 at 115200 baud
    [INFO] [1615494589.879567]: Note: publish buffer size is 1024 bytes
    [INFO] [1615494589.882640]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
    [INFO] [1615494589.898436]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
    [INFO] [1615494590.126077]: Setup publisher on imu [sensor_msgs/Imu]
    [INFO] [1615494590.147262]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
    [INFO] [1615494590.221050]: Setup publisher on odom [nav_msgs/Odometry]
    [INFO] [1615494590.242527]: Setup publisher on joint_states [sensor_msgs/JointState]
    [INFO] [1615494590.265235]: Setup publisher on battery_state [sensor_msgs/BatteryState]
    [INFO] [1615494590.281715]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
    [INFO] [1615494596.733672]: Setup publisher on /tf [tf/tfMessage]
    [INFO] [1615494596.749821]: Note: subscribe buffer size is 1024 bytes
    [INFO] [1615494596.751411]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
    [INFO] [1615494596.767101]: Setup subscriber on joint_trajectory_point [std_msgs/Float64MultiArray]
    [INFO] [1615494596.783385]: Setup subscriber on joint_move_time [std_msgs/Float64]
    [INFO] [1615494596.800303]: Setup subscriber on gripper_position [std_msgs/Float64MultiArray]
    [INFO] [1615494596.816650]: Setup subscriber on gripper_move_time [std_msgs/Float64]
    [INFO] [1615494596.833801]: Setup subscriber on sound [turtlebot3_msgs/Sound]
    [INFO] [1615494596.850097]: Setup subscriber on motor_power [std_msgs/Bool]
    [INFO] [1615494596.865602]: Setup subscriber on reset [std_msgs/Empty]
    [WARN] [1615494596.879623]: Failed to get param: timeout expired
    [INFO] [1615494596.883070]: Setup TF on Odometry [odom]
    [INFO] [1615494596.886641]: Setup TF on IMU [imu_link]
    [INFO] [1615494596.890209]: Setup TF on MagneticField [mag_link]
    [INFO] [1615494596.893646]: Setup TF on JointState [base_link]
    [INFO] [1615494596.901542]: --------------------------
    [INFO] [1615494596.905014]: Connected to OpenCR board!
    [INFO] [1615494596.908465]: This core(v2.0.1) is compatible with TB3 with OpenManipulator
    [INFO] [1615494596.911897]: --------------------------
    [INFO] [1615494596.915311]: Start Calibration of Gyro
    [INFO] [1615494596.918825]: Calibration End
    [ WARN] [1615494597.180745387]: This firmware(v2.0.1) isn't compatible with this software (v1.1.0)
    [ WARN] [1615494597.181006895]: You can find how to update its in `FAQ` section(turtlebot3.robotis.com)
    ```
![Screenshot from 2021-03-11 15-36-06](https://user-images.githubusercontent.com/37709186/110856764-0b323380-8286-11eb-8929-f9d38b8d2164.png)
![Screenshot from 2021-03-11 15-42-58](https://user-images.githubusercontent.com/37709186/110856768-0bcaca00-8286-11eb-9a7b-8f03b269bdb7.png)
![Screenshot from 2021-03-11 15-49-43](https://user-images.githubusercontent.com/37709186/110856769-0c636080-8286-11eb-96c6-7e3354555721.png)

9. Please describe the issue in detail.

    - Not able to control OpenManipulator-X interface with Waffle Pi (turtlebot3) either from Rviz or Robotics GUI Controller.
    - When using GUI Controller, Set/Open Gripper command manipulates other motors instead of the gripper. We have made sure that the order of Motor IDs assembled are correct.
    - Motors with ID 13 and 14 are movable by hands even we execute the controller while rest of the motors of the arm are locked.
    - This issue is similar to Issue#21 closed earlier. We tried the solution suggested there, but it did not solve the issue.

**Comment by Prajwalmj** [comment]
- We assembled the arm according to the instructions in the official manual for OpenManipulator-X. We tested the working and control using Rviz, Robotics GUI controller. Motor with IDs 13, 14 could not be controlled by the commands from GUI controller and it could be moved by hand when it's turned ON, while other motors are locked. In addition to that, when we try to execute commands like "Set Gripper", base motor (ID - 11) moves instead of the gripper. Also, when we set joint angles and click send in the GUI controller, there is no response.
- We are currently using DYNAMIXEL XM430-W350-T.
- We follow the instructions from the following website: [assemble](https://emanual.robotis.com/docs/en/platform/openmanipulator_x/assembly/#assembly-manual). The motor IDs are from 11-15. And we choose the motor IDs and order according to the assembly manual.
- We followed the instructions on [openmanipulator-x](https://emanual.robotis.com/docs/en/platform/openmanipulator_x/quick_start_guide/#quick-start-guide) and [turtlebot3-manipulation](https://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation/#manipulation) to download and install all the code from Github. We did it recently and we think it should be the latest version.

Please let us know if you need more information.
![IMG-9198](https://user-images.githubusercontent.com/37709186/110989276-a5a27d80-833f-11eb-8834-e42afa90b608.jpg)

**Comment by ROBOTIS-Will** [comment]
DYNAMIXEL only operate with a digital packet and correctly transmitted signal does not affect to other joints.
If ID 11 joint operates instead of the gripper, make sure to check all ID so that each joint is correctly assembled.
It looks like you have installed ID 15 to the base roll joint.
Also, there should be only one ID for each DYNAMIXEL and they should NOT be duplicated.

**Comment by Prajwalmj** [comment]
- We have installed ID 11 only to the base joint, ID 12 for the 1st joint, ID 13 for the 2nd joint, ID 14 for the 3rd joint, ID 15 for the gripper as per the official manual. There are stickers on each DYNAMIXEL indicating and we have used them accordingly.
- We confirmed that all the IDs are different (based on stickers on DYNAMIXEL) and there aren't any duplicates.
- We have tested the gripper using GUI controller. We pressed different buttons many times, only a few times only motor ID 12 moves, rest of the time, nothing happens. We guess this is hardware issue. So we are planning to disassemble everything, replace jumper wires and test everything again.
- Could you suggest some other things that we could try? What about the firmware incompatibility issue and issues with Rviz?

**Comment by Prajwalmj** [comment]
@ROBOTIS-Will , there were hardware issues with wiring and connections. After disassembling and assembling everything again, we figured out this. Everything is working fine now. Thanks for your replies and help! So, I am closing the the issue.
