### ISSUE TITLE
No /dev/ttyACM0

### ISSUE THREAD

**Issue by kkenyoncit** [ROBOTIS-GIT/turtlebot3#713]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [X ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [X ] etc (Please specify your ROS Version here) Kinetic, the version that is on the image that we downloaded from the e-manual. 

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ X] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ X] etc (Please specify your OS here) the version that is downloaded when following the manual

5. Which OS you installed on Remote PC?

    - [X ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x] 
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - roslaunch turtlebot3_bringup turtlebot3_robot.launch 

8. Copy and Paste the error messages on terminal.

    - error1
    - 
![error1](https://user-images.githubusercontent.com/80595700/111226873-1ce24680-85b8-11eb-94da-f933cf2a0048.png)

    - error2
    - 
![error2](https://user-images.githubusercontent.com/80595700/111227500-08527e00-85b9-11eb-8bb0-ad04a3855c10.png)

    - error3
    - 
![error3](https://user-images.githubusercontent.com/80595700/111227519-11dbe600-85b9-11eb-9012-49f7c1fe18e3.png)

    - error4
    - 
![error4](https://user-images.githubusercontent.com/80595700/111227535-199b8a80-85b9-11eb-91eb-82ff7e1e94ee.png)

9. Please describe the issue in detail.

PC:
export ROS_MASTER_URI=http://10.42.0.1:11311
export ROS_HOSTNAME=10.42.0.1

Pi:
export ROS_MASTER_URI=http://10.42.0.1:11311
export ROS_HOSTNAME=10.42.0.213

    - Followed the PC and SBC setup procedures, on the Bringup page got to the roslaunch turtlebot3_bringup turtlebot3_robot.launch command and received error 1. Under the suggestion from a professor we attempted to run it directly from the pi so we commented out the rosmaster lines from the bash file and re-ran roscore and roslaunch turtlebot3_bringup turtlebot3_robot.launch on the pi and got error 2. 
    - In an issue we believed to be a separate issue but turned out not to be while running through the OpenCR setup procedures we ran into error 3 while running sudo apt-get update that we got past by a google search and running the command sudo apt-key adv --keyserver.ubuntu.com --recv-keys F42ED6FBAB17C654, next we get to ./update.sh $OPENCR_PORT $OPENCR_MODEL.opencr and get error 4.
    - We did a cd /dev and ls and there is no ttyACM0.

**Comment by sainavaneet** [comment]
i am also having same errors can anyone please help
