### ISSUE TITLE
How to reverse turtlebot to starting point without rotation?

### ISSUE THREAD

**Issue by judo0140** [ROBOTIS-GIT/turtlebot3#724]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ o ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ o ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ o ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ o ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ o ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.

    - I moved my turtlebot at ( 0.5, 0.5, 0) when it subscribed specific topics by using this code "https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_example/nodes/turtlebot3_pointop_key". Then, I want to move my turtlebot at starting point ( 0, 0, 0) without rotation. However I don't know how to. My turtlebot returns at starting point drawing a curved path. In the code, what should I fix? Here is my code.(Actually, just add pub and sub functions.  https://github.com/judo0140/judo/blob/master/turtlebot3_pointop_test2)

**Comment by ROBOTIS-Will** [comment]
Hi @judo0140 
Please understand that we do not review customers' source code.
To give you a general information to reverse the TurtleBot3, use a negative value for the `move_cmd.linear.x`.
Thank you.

**Comment by judo0140** [comment]
Thank you for your answer.
That's enough to solve my problem.
