### ISSUE TITLE
How can I control two turtlebots by giving point ?

### ISSUE THREAD

**Issue by judo0140** [ROBOTIS-GIT/turtlebot3#727]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ o ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ o ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ o ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ o ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ o ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.

    - Hi. I'm new to ROS and turtlebot3 control. Recently, I succeeded in driving one turtlebot and now I am trying to drive two turtlebots. I want to control them with 'turtlebot3_pointop' (move turtlebot by giving point (x, y, z)). I have already seen https://emanual.robotis.com/docs/en/platform/turtlebot3/basic_examples/#load-multiple-turtlebot3s but, I don't know what to do after loading two turtlebots. I think that I should use '/tb3_0 or 1/base_footprint or base_link'... is it right? I'm sorry my question is too abstract.

**Comment by ROBOTIS-Will** [comment]
Hi,

In order to control multiple robots on ROS, you should separate their nodes and messages with different namespace.
Not only the TF, but also should you separate nodes and messages so that they won't get affect to each other.
If you are new to ROS, I'd recommend to start with something simple such as [turtlesim](http://wiki.ros.org/turtlesim) first, then move on to the actual robot platform with decent understanding about how ROS works.
Thanks
