### ISSUE TITLE
Turtlebot3 Waffle Pi with Open Manipulator Melodic Not working

### ISSUE THREAD

**Issue by slavenpetkovic** [ROBOTIS-GIT/turtlebot3#735]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [x] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [x] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - Can't get Open Manipulator X with Turtlebot3 Waffle Pi to work with ROS Melodic. I tried section 7 (Manipulation) from Turtlebot3 Emanual for Kinetic but it doesn't work. It says something like Can't fetch current robot state.

8. Copy and Paste the error messages on terminal.

    - No instructions for Melodic.

9. Please describe the issue in detail.

    - HERE

**Comment by ROBOTIS-Will** [comment]
@slavenpetkovic 
The TB3 + OM-X package is currently supporting ROS1 Kinetic only and will be updated to support up to Noetic within 2Q.
Thank you.
