### ISSUE TITLE
turtlebot3_teleop

### ISSUE THREAD

**Issue by ZhaZhaJ** [ROBOTIS-GIT/turtlebot3#740]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [V] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [V] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [V] etc (simulation)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [V] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [1] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [V ] etc (VMware)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [HUAWEI_matebook 14]
    - Firmware version: [HUAWEI_matebook 14]

7. Specify the commands or instructions to reproduce the issue.

    -roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch

8. Copy and Paste the error messages on terminal.

    ERROR: cannot launch node of type [turtlebot3_teleop/turtlebot3_teleop_key]: can't locate node [turtlebot3_teleop_key] in package [turtlebot3_teleop]

9. Please describe the issue in detail.

    - I had tried "sudo apt-get install ros-kinetic-turtlebot3-teleop"
 
![image](https://user-images.githubusercontent.com/64353489/117747566-fe5b9d00-b240-11eb-8317-ccef65ef6a7b.png)

**Comment by ROBOTIS-Will** [comment]
@firstn01
Could you check if you have below setup configuration in your `.bashrc` file?
```
source /opt/ros/kinetic/setup.bash
```
What was the output of the command below?
```
$ sudo apt-get install ros-kinetic-turtlebot3-teleop
```
Does below command help you to resolve the issue?
```
$ rospack profile
```

**Comment by firstn01** [comment]
Thank you very much! @ROBOTIS-Will 
I have tried your answer,and the question also exist.

![image](https://user-images.githubusercontent.com/64353489/117754882-cc9d0300-b24d-11eb-8137-2a3d4ec13378.png)

![image](https://user-images.githubusercontent.com/64353489/117754981-fe15ce80-b24d-11eb-8e9d-f8c2dcf4922a.png)

![image](https://user-images.githubusercontent.com/64353489/117755087-2ac9e600-b24e-11eb-806b-54186cd0b88f.png)

**Comment by firstn01** [comment]
This is path of the turtlebot3_teleop pack.
![image](https://user-images.githubusercontent.com/64353489/117756055-01aa5500-b250-11eb-95bd-825de7e41061.png)

**Comment by ROBOTIS-Will** [comment]
Have you build the source after copying into the src folder of catkin_ws?
```
$ cd ~/catkin_ws && catkin_make
$ source ~/catkin_ws/devel/setup.bash
```

**Comment by sunghowoo** [comment]
We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
