### ISSUE TITLE
Turtlebot3 Description Files

### ISSUE THREAD

**Issue by sundyCoder** [ROBOTIS-GIT/turtlebot3#743]
I found that there only have turtlebot3 burger and waffle models for simulation in Gazebo in turtlebot3_description. So, I wonder if Gazebo models of other types of Turtlebot3 series, e.g., Turtlebot3 bike, Turtlebot3 car, Turtlebot3 mecanum, Turtlebot3 monster, ..., etc., will be provided.  Many thanks!

**Comment by ROBOTIS-Will** [comment]
Hi @sundyCoder 
The modeling files for those "friends" requires quite a lot of space and not being used by many developers.
Also it is not implemented for ROS, it has not been included in the package.
Thank you.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
