### ISSUE TITLE
How can I add velodyne-16 lidar when I use turtlebot3?

### ISSUE THREAD

**Issue by tdcsu** [ROBOTIS-GIT/turtlebot3#751]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [x] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.

    - HERE

**Comment by ashekim** [comment]
Hi @tdcsu :)
Thanks for your interest in Turtlebot3
I think you can use Velodyne by connecting it to Raspberry Pi 3B+.
Please refer to the link and photos below for more details

![image](https://user-images.githubusercontent.com/61770300/121866546-fc9e6100-cd39-11eb-9d78-fc09b9406aff.png)

[Getting Started with the Velodyne VLP16](http://wiki.ros.org/velodyne/Tutorials/Getting%20Started%20with%20the%20Velodyne%20VLP16)

Thank you.

**Comment by tdcsu** [comment]
thank&nbsp;you&nbsp;for&nbsp;your&nbsp;kind&nbsp;interpretation，I&nbsp;will&nbsp;try&nbsp;it&nbsp;as&nbsp;soon&nbsp;as&nbsp;possible!


---Original---
From: ***@***.***&gt;
Date: Mon, Jun 14, 2021 17:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ROBOTIS-GIT/turtlebot3] How can I add velodyne-16 lidar when I use turtlebot3? (#751)




 
Hi @tdcsu :)
 Thanks for your interest in Turtlebot3
 I think you can use Velodyne by connecting it to Raspberry Pi 3B+.
 Please refer to the link and photos below for more details
 

 
Getting Started with the Velodyne VLP16
 
Thank you.
 
&mdash;
