### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by w5688414** [ROBOTIS-GIT/turtlebot3#755]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Ubuntu MATE (16.04/18.04/20.04)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

```
➜  catkin_ws roslaunch turtlebot3_gazebo turtlebot3_simulation.launch
... logging to /home/eric/.ros/log/a6ed6da8-d196-11eb-85c4-0242323584ca/roslaunch-eric-ms-7a54-6486.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:43421/

SUMMARY
========

PARAMETERS
 * /cmd_vel_topic_name: /cmd_vel
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

NODES
  /
    turtlebot3_drive (turtlebot3_gazebo/turtlebot3_drive)

ROS_MASTER_URI=http://localhost:11311

process[turtlebot3_drive-1]: started with pid [6513]
[ INFO] [1624173179.591969078]: TurtleBot3 Simulation Node Init
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 30) >= this->size() (which is 24)
================================================================================REQUIRED process [turtlebot3_drive-1] has died!
process has died [pid 6513, exit code -6, cmd /home/eric/catkin_ws/devel/lib/turtlebot3_gazebo/turtlebot3_drive __name:=turtlebot3_drive __log:=/home/eric/.ros/log/a6ed6da8-d196-11eb-85c4-0242323584ca/turtlebot3_drive-1.log].
log file: /home/eric/.ros/log/a6ed6da8-d196-11eb-85c4-0242323584ca/turtlebot3_drive-1*.log
Initiating shutdown!
================================================================================
[turtlebot3_drive-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

9. Please describe the issue in detail.

    - HERE

**Comment by ROBOTIS-Will** [comment]
Hi @w5688414 

In order to run the collision avoidance example, you should first launch the simulation environment such as `turtlebot3_world.launch` or `turtlebot3_house.launch`.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
