### ISSUE TITLE
unable to contact ROS master 

### ISSUE THREAD

**Issue by markusmat97** [ROBOTIS-GIT/turtlebot3#758]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?
     Waffle Pi

2. Which ROS is working with TurtleBot3?
       ROS 1 Melodic Morenia
    

3. Which SBC(Single Board Computer) is working on TurtleBot3?
       Raspberry Pi 3B+
   

4. Which OS you installed on SBC?
      Raspberry Pi 3B+ ROS1 Melodic image(Ubuntu 18.04 based)
5. Which OS you installed on Remote PC?
      Windows 10
   

6. Specify the software and firmware version(Can be found from Bringup messages)

  
![git1](https://user-images.githubusercontent.com/71436802/123676911-c89c6300-d844-11eb-96bd-04ab0702bb83.PNG)

7. Specify the commands or instructions to reproduce the issue.

    roslaunch turtlebot3_bringup turtlebot3_robot.launch

8. Copy and Paste the error messages on terminal.
RLException: ERROR: unable to contact ROS master at [http://192.168.0.201:11311]
The traceback for the exception was written to the log file
    - HERE

**Comment by ashekim** [comment]
Hi @mathews997 . 
Please refer to the link below for network configuration.
[3.1.2 Network Configuration Windows](https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/#network-configuration-3)

And you can check the windows ip with 
`$ipconfig`

Thank you.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
