### ISSUE TITLE
User LED- USER3 is red 

### ISSUE THREAD

**Issue by hadarkam** [ROBOTIS-GIT/turtlebot3#763]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [x] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.

    - I had no problems until once I turned on the robot and the LED - USER3 turned on ( red light). As a result, the robot does not work at all (won't move...)! What might be the problem?

**Comment by ashekim** [comment]
Hi. @hadarkam. Thank you for your questions.

The Turtlebot3 stops when LED-USER3 turns on is caused by low voltage.
Therefore, please connecting the SMPS that can supply enough voltage.

Thank you.

**Comment by hadarkam** [comment]
Hi,
This problem still accrued with a charged battery. 
Additionally, it also happens while the robot is connected directly to a power source.
What else can we do?

Thanks,
Hadar

**Comment by ashekim** [comment]
Hi. @hadarkam. 
I'm sorry for the late reply.

USER-3 LED is lit when power is not applied normally.
If the light comes on even with a charged battery, Please refer to the link below and reinstall OpenCR.

[Dashing - OpenCR Setup](https://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup)

Thank you.

**Comment by hadarkam** [comment]
Thank you!

‫בתאריך יום ה׳, 5 באוג׳ 2021 ב-11:16 מאת ‪ROBOTIS-Ashe‬‏ <‪
***@***.***‬‏>:‬
