### ISSUE TITLE
May I know how we can obtain transforms of the bot? I want to obtain frame ids, similar to using hector_trajectory_server used in ROS

### ISSUE THREAD

**Issue by ROBOTIS-Will** [ROBOTIS-GIT/turtlebot3#766]
May I know how we can obtain transforms of the bot? I want to obtain frame ids, similar to using hector_trajectory_server used in ROS

_Originally posted by @akshay-30 in https://github.com/ROBOTIS-GIT/turtlebot3/issues/512#issuecomment-890928829_

**Comment by ROBOTIS-Will** [comment]
@akshay-30 

You can read a specific frame_id in `/tf` topic.
Some of the the transform of the hardware attached to the robot are published via the `/tf_static` topic.

**Comment by akshay-30** [comment]
I tried to read the odom frame and the base_link frame. And publish the frame ids , but I'm getting a error of invalid frame is passed in canTransform : odom frame (target frame) does not exist.

**Comment by akshay-30** [comment]
I'm using ubuntu 20.04 version on my laptop, and running ros2 foxy. I have tried to port hector_trajectory_server to ros2. Just want to test it on turtlebot3.

**Comment by ROBOTIS-Will** [comment]
While TurtleBot3 is running the Bringup node, you can read the `/tf` and will return both `odom` and `base_link` as below.
![image](https://user-images.githubusercontent.com/26239359/128660411-e5e5fb18-9876-4e23-8479-6a4f657236a5.png)

**Comment by akshay-30** [comment]
I'm trying to read the frame ids through tf2_ros::TransformListener, passing it into tf2_ros::Buffer. But canTransform and lookupTransform functions are not able to find the target frame ids. I get the error - frame does not exist

**Comment by akshay-30** [comment]
Also, turtlebot3_bringup - robot.launch.py isn't working. Process is dying. turtlebot3_node isn't building. 
![image](https://user-images.githubusercontent.com/86337391/128712625-34df2ab7-ee65-4939-9e7a-3d940d65194b.png)

**Comment by akshay-30** [comment]
Nevermind, I found the bug in my code and was able to debug it with some help. I wasn't passing the right parameters into lookuptransform. Now I am getting the right frame ids and their transforms. 
Thanks for the help @ROBOTIS-Will

**Comment by ROBOTIS-Will** [comment]
@akshay-30 
Looks like you haven't correctly installed the package or didn't source the correct working space.
Make sure to install all the necessary packages to run the TurtleBot3.

**Comment by akshay-30** [comment]
For installation I followed the tutorial itself. And have sourced it properly. 
turtlebot3_gazebo, turtlebot3_navigation, turtlebot3_teleop are all building properly except turtlebot3_bringup

**Comment by GyuH13** [comment]
This issue was raised so long ago that it is now challenging to address. 
Please refer to the updated manual, and if you have any further questions, feel free to open a new issue.

**Comment by sunghowoo** [comment]
We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
