### ISSUE TITLE
Lidar stops spinning on callind roslaunch turtlebot3_bringup turtlebot3_robot.launch

### ISSUE THREAD

**Issue by anirudhkochhar** [ROBOTIS-GIT/turtlebot3#770]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [x] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [x] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [x] Intel UPSquared

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [x] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - roslaunch turtlebot3_bringup turtlebot3_robot.launch

8. Copy and Paste the error messages on terminal.

there is no error message

    - roslaunch turtlebot3_bringup turtlebot3_robot.launch 
... logging to /home/tello/.ros/log/eac62d16-fa96-11eb-8d52-6b7b9b0ca69c/roslaunch-fha-4482.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.0.18:35387/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://192.168.0.16:11311

process[turtlebot3_core-1]: started with pid [4490]
process[turtlebot3_lds-2]: started with pid [4491]
process[turtlebot3_diagnostics-3]: started with pid [4492]
[INFO] [1628686126.646088]: ROS Serial Python Node
[INFO] [1628686126.690837]: Connecting to /dev/ttyACM0 at 115200 baud
[INFO] [1628686128.839200]: Requesting topics...
[INFO] [1628686128.982289]: Note: publish buffer size is 1024 bytes
[INFO] [1628686128.991776]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1628686129.010194]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1628686129.070334]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1628686129.090531]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1628686129.122790]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1628686129.144872]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1628686129.165936]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1628686129.187874]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1628686129.236636]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1628686129.263409]: Note: subscribe buffer size is 1024 bytes
[INFO] [1628686129.282927]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
[INFO] [1628686129.311093]: Setup subscriber on sound [turtlebot3_msgs/Sound]
[INFO] [1628686129.339177]: Setup subscriber on motor_power [std_msgs/Bool]
[INFO] [1628686129.370952]: Setup subscriber on reset [std_msgs/Empty]
[INFO] [1628686132.142252]: Setup TF on Odometry [odom]
[INFO] [1628686132.152488]: Setup TF on IMU [imu_link]
[INFO] [1628686132.163884]: Setup TF on MagneticField [mag_link]
[INFO] [1628686132.175849]: Setup TF on JointState [base_link]
[INFO] [1628686132.190595]: --------------------------
[INFO] [1628686132.200521]: Connected to OpenCR board!
[INFO] [1628686132.210562]: This core(v1.2.6) is compatible with TB3 Waffle or Waffle Pi
[INFO] [1628686132.220935]: --------------------------
[INFO] [1628686132.231435]: Start Calibration of Gyro
[INFO] [1628686134.704229]: Calibration End

9. Please describe the issue in detail.

    - whenever i run turtlebot3_bringup turtlebot3_launch - my lidar stops spinning (while it is spinning otherwise) - it leads to me not receiving any scan values in the rostopic /scan.
    - i looked further and found that the lidar precisely stops spinning when **hls_lfcd_lds_driver/hlds_laser_publisher** is called. i tried rosrun hls_lfcd_lds_driver hlds_laser_publisher - and the lidar stops spinning

**Comment by ROBOTIS-Will** [comment]
@anirudhkochhar 
How did you install the hlds_lfcd_lds_driver?
The sensor driver start up the motor when LFCDLaser object is created as below.
https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver/blob/noetic-devel/src/hlds_laser_publisher.cpp#L49

**Comment by GyuH13** [comment]
This issue was raised so long ago that it is now challenging to address. 
Please refer to the updated manual, and if you have any further questions, feel free to open a new issue

**Comment by sunghowoo** [comment]
@anirudhkochhar Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions.  We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
