### ISSUE TITLE
login username and passwd

### ISSUE THREAD

**Issue by sundyCoder** [ROBOTIS-GIT/turtlebot3#771]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - Burger

2. Which ROS is working with TurtleBot3?
    - ROS 2 Foxy Fitzroy
  
![image](https://user-images.githubusercontent.com/7138315/129446602-caf879ed-4c4e-4d11-baa1-8cbcf7863471.png)

What's the username and password of this image, I tray ubuntu/ubuntu and pi/raspberry, both are failed.

**Comment by nullbyte91** [comment]
Hi @sundyCoder , The Username is ubuntu and Password is turtlebot.
