### ISSUE TITLE
Cant Bringup turtlebot3 on VirtualBox

### ISSUE THREAD

**Issue by IdoSegal1234** [ROBOTIS-GIT/turtlebot3#774]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [ X] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ X] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [X ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ X] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [X ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

roslaunch turtlebot3_bringup turtlebot3_robot.launch

8. Copy and Paste the error messages on terminal.

ido@ido-VirtualBox:~$ roslaunch turtlebot3_bringup turtlebot3_robot.launch
... logging to /home/ido/.ros/log/476cb566-fda9-11eb-9dff-0800277fefa9/roslaunch-ido-VirtualBox-28319.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.100.102.42:46783/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.17
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://10.100.102.42:11311

process[turtlebot3_core-1]: started with pid [28336]
process[turtlebot3_lds-2]: started with pid [28337]
process[turtlebot3_diagnostics-3]: started with pid [28338]
[ERROR] [1629018924.260907861]: An exception was thrown: open: No such file or directory
[turtlebot3_lds-2] process has died [pid 28337, exit code 255, cmd /opt/ros/kinetic/lib/hls_lfcd_lds_driver/hlds_laser_publisher __name:=turtlebot3_lds __log:=/home/ido/.ros/log/476cb566-fda9-11eb-9dff-0800277fefa9/turtlebot3_lds-2.log].
log file: /home/ido/.ros/log/476cb566-fda9-11eb-9dff-0800277fefa9/turtlebot3_lds-2*.log
[INFO] [1629018924.903113]: ROS Serial Python Node
[INFO] [1629018924.911257]: Connecting to /dev/ttyACM0 at 115200 baud
[ERROR] [1629018924.916405]: Error opening serial: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
[turtlebot3_core-1] process has finished cleanly
log file: /home/ido/.ros/log/476cb566-fda9-11eb-9dff-0800277fefa9/turtlebot3_core-1*.log

9. Please describe the issue in detail.

    Get error when trying to bringup the robot, roscore and ssh worked well.

**Comment by ashekim** [comment]
Hi @IdoSegal1234 .

It is not find to '/dev/ttyACM0' port.
Please type following command to find the serial port number.
`ls /dev/ttyACM`

If the port exists, enter the command below to change the permission.
`sudo chmod a+rw /dev/ttyACM0`

thank you.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
