### ISSUE TITLE
Turtlebot3 Cmake Error: ROS NOETIC Installation 

### ISSUE THREAD

**Issue by ishaniis** [ROBOTIS-GIT/turtlebot3#775]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Noetic Ninjemys
    

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 4

4. Which OS you installed on SBC?

    - [ ] Ubuntu preinstalled server (18.04/20.04)

5. Which OS you installed on the Remote PC?

    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
  
6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    Followed the ROBOTIS Turtlebot ROS Noetic installation video on youtube. 

8. Copy and Paste the error messages on the terminal.

CMake Error at /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a configuration file for package "ignition-common3-graphics"
  that exactly matches requested version "3.13.1".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/ignition-common3-graphics/ignition-common3-graphics-config.cmake, version: 3.10.0
    /lib/x86_64-linux-gnu/cmake/ignition-common3-graphics/ignition-common3-graphics-config.cmake, version: 3.10.0

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/ignition-common3/ignition-common3-config.cmake:203 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:250 (find_package)
  turtlebot3_simulations/turtlebot3_gazebo/CMakeLists.txt:24 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/isharm2/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/isharm2/catkin_ws/build/CMakeFiles/CMakeError.log".

9. Please describe the issue in detail.

    I am not sure, How to work through this issue!

**Comment by ashekim** [comment]
Hi @ishaniis. 
This error seems to occur because the Ignition package is not installed.
Please Enter the command below to install the package

`apt install ignition-rendering3`

Additionally, there is a link below for a case similar to this issue.
Please also refer to the [link](https://github.com/PX4/PX4-Autopilot/issues/16386).
Thank you

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity.  if the issue persists, feel free to reopen it.
