### ISSUE TITLE
Some robots don't play sound when turned on

### ISSUE THREAD

**Issue by shayanaimi** [ROBOTIS-GIT/turtlebot3#776]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [X] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [X] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [X] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [X] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x] ??
    - Firmware version: [x.x.x] ??

7. Specify the commands or instructions to reproduce the issue.

        Turn on the robot using the switch on Raspberry Pi.

8. Copy and Paste the error messages on terminal.

    N/A

9. Please describe the issue in detail.

 My Turtlebot3  does not play the short sound that most of the other Turtlebots play when they are turned on. It is fully functional other than this; OpenCR setup was successful with no errors, SW1 and SW2 button tests worked, and we are able to launch the robot and run basic ros2 commands on it. Because the robot is functional outside of this issue, we are wondering if this issue should be an area of concern. Is there anything we can do to fix the sound?

**Comment by ROBOTIS-Will** [comment]
Hi @shayanaimi 
The OpenCR with ROS2 firmware plays doremi sound during initialization. 
This initialization is independent to ROS2.
If it is fully functional except the sound, I would assume that the buzzer is not functioning which isn't critical in operating the robot.
However, TurtleBot3 will alert the low battery voltage with buzzer alarm.
Please check the voltage regularly so that it doesn't get over discharged.
Thank you.

**Comment by sunghowoo** [comment]
We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
