### ISSUE TITLE
Sensor fusion

### ISSUE THREAD

**Issue by claudiosouzabrito** [ROBOTIS-GIT/turtlebot3#786]
Hello, I have been using this git a lot for my research and got to the question: The slam algorithms are using more than one sensor?
I mean I know that they use the RPlidar and the scan topic, but I want to know if he uses odom as well.

How do I know if he uses more than one sensor?

**Comment by ROBOTIS-Will** [comment]
Hi @claudiosouzabrito 
Please use this issue thread for reporting bugs and issues as there is a [ROS Answers](https://answers.ros.org/questions/) community where you can get abundant information.
In short, SLAM algorithms may use other sensors such as IMU or encoders to compensate the disadvantages of Lidar.
For example, [Gmapping](http://wiki.ros.org/gmapping#Required_tf_Transforms) requires odometry from the wheel.
Any required inputs(Subscribed Topics) for a specific SLAM algorithm will be described in its documentation.
Thank you.
