### ISSUE TITLE
Could not open file turtlebot3  waffle pi .urdf for parsing

### ISSUE THREAD

**Issue by srushtibobade** [ROBOTIS-GIT/turtlebot3#790]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    
    - [ ] ROS 2 Dashing Diademata
    

3. Which SBC(Single Board Computer) is working on TurtleBot3?

 
    - [ ] Raspberry Pi 4
   

4. Which OS you installed on SBC?

    
    - [ ] Ubuntu MATE (18.04)
  
5. Which OS you installed on Remote PC?

    
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    

7. Specify the commands or instructions to reproduce the issue.

  ros2 launch turtlebot3_bringup robot.launch.py

8. Copy and Paste the error messages on terminal.

  ubuntu@ubuntu:~$ export TURTLEBOT3_MODEL= waffle_pi
ubuntu@ubuntu:~$ ros2 launch turtlebot3_bringup robot.launch.py
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2021-10-08-12-19-16-423505-ubuntu-8029
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : turtlebot3_.urdf
[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: /home/ubuntu/turtlebot3_ws/install/turtlebot3_bringup/share/turtlebot3_bringup/param/.yaml
[INFO] [robot_state_publisher-1]: process started with pid [8039]
[INFO] [hlds_laser_publisher-2]: process started with pid [8040]
[INFO] [turtlebot3_ros-3]: process started with pid [8041]
[robot_state_publisher-1] Initialize urdf model from file: /home/ubuntu/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_.urdf
[robot_state_publisher-1] Could not open file [/home/ubuntu/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_.urdf] for parsing.
[robot_state_publisher-1] Unable to initialize urdf::model from /home/ubuntu/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_.urdf
[ERROR] [robot_state_publisher-1]: process has died [pid 8039, exit code 255, cmd '/opt/ros/dashing/lib/robot_state_publisher/robot_state_publisher /home/ubuntu/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_.urdf __node:=robot_state_publisher __params:=/tmp/launch_params_nqhukw00'].
[turtlebot3_ros-3] terminate called after throwing an instance of 'std::runtime_error'
[turtlebot3_ros-3]   what():  Failed to parse parameters from file '/home/ubuntu/turtlebot3_ws/install/turtlebot3_bringup/share/turtlebot3_bringup/param/.yaml': Error opening YAML file, at /tmp/binarydeb/ros-dashing-rcl-yaml-param-parser-0.7.10/src/parser.c:1387
[ERROR] [turtlebot3_ros-3]: process has died [pid 8041, exit code -6, cmd '/home/ubuntu/turtlebot3_ws/install/turtlebot3_node/lib/turtlebot3_node/turtlebot3_ros -i /dev/ttyACM0 __params:=/home/ubuntu/turtlebot3_ws/install/turtlebot3_bringup/share/turtlebot3_bringup/param/.yaml'].
[robot_state_publisher-1] Could not open file [/home/ubuntu/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_.urdf] for parsing.
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[hlds_laser_publisher-2] [INFO] [hlds_laser_publisher]: Init hlds_laser_publisher Node Main
[hlds_laser_publisher-2] [INFO] [hlds_laser_publisher]: port : /dev/ttyUSB0 frame_id : base_scan
[hlds_laser_publisher-2] [INFO] [rclcpp]: signal_handler(signal_value=2)
[ERROR] [hlds_laser_publisher-2]: process has died [pid 8040, exit code 255, cmd '/opt/ros/dashing/lib/hls_lfcd_lds_driver/hlds_laser_publisher __node:=hlds_laser_publisher __params:=/tmp/launch_params_6cdpad5_'].

9. Please describe the issue in detail.

    Not able to bring up TB3 waffle pi using ros2 launch turtlebot3_bringup robot.launch.py

**Comment by srushtibobade** [comment]
Hi @ROBOTIS-Will. 
Sorry for very late reply but the issue was also unstable voltage source to the TB3

**Comment by Dqiqi123** [comment]
cmd '/opt/ros/foxy/lib/turtlebot3_node/turtlebot3_ros -i /dev/ttyACM0 --ros-args --params-file /opt/ros/foxy/share/turtlebot3_bringup/param/waffle_pi.yaml'
