### ISSUE TITLE
ROS2 foxy "No map received" in Rviz2

### ISSUE THREAD

**Issue by stu00608** [ROBOTIS-GIT/turtlebot3#791]
1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [x] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [x] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    on SBC : 
    `ros2 launch turtlebot3_bringup robot.launch.py`
    on Remote PC : 
    'ros2 launch turtlebot3_cartographer cartographer.launch.py'

8. Copy and Paste the error messages on terminal.

Here is the log of running cartographer.

[INFO] [launch]: All log files can be found below /home/stu00608/.ros/log/2021-10-09-17-44-42-863008-stu00608-CILAB-34070
[INFO] [launch]: Default logging verbosity is set to INFO
/opt/ros/foxy/share/turtlebot3_cartographer/launch/cartographer.launch.py:56: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  Node(
/opt/ros/foxy/share/turtlebot3_cartographer/launch/cartographer.launch.py:56: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  Node(
/opt/ros/foxy/share/turtlebot3_cartographer/launch/cartographer.launch.py:81: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  Node(
/opt/ros/foxy/share/turtlebot3_cartographer/launch/cartographer.launch.py:81: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  Node(
/opt/ros/foxy/share/turtlebot3_cartographer/launch/occupancy_grid.launch.py:44: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  Node(
/opt/ros/foxy/share/turtlebot3_cartographer/launch/occupancy_grid.launch.py:44: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  Node(
[INFO] [cartographer_node-1]: process started with pid [34072]
[INFO] [occupancy_grid_node-2]: process started with pid [34074]
[INFO] [rviz2-3]: process started with pid [34076]
[cartographer_node-1] [INFO] [1633772682.948421801] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/turtlebot3_cartographer/config/turtlebot3_lds_2d.lua' for 'turtlebot3_lds_2d.lua'.
[cartographer_node-1] [INFO] [1633772682.948643621] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[cartographer_node-1] [INFO] [1633772682.948663428] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[cartographer_node-1] [INFO] [1633772682.948706724] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
[cartographer_node-1] [INFO] [1633772682.948722497] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
[cartographer_node-1] [INFO] [1633772682.948832601] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
[cartographer_node-1] [INFO] [1633772682.948853984] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
[cartographer_node-1] [INFO] [1633772682.948887247] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[cartographer_node-1] [INFO] [1633772682.948901006] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[cartographer_node-1] [INFO] [1633772682.948975157] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[cartographer_node-1] [INFO] [1633772682.948999941] [cartographer_ros]: I1009 17:44:42.000000 34072 configuration_file_resolver.cc:41] Found '/opt/ros/foxy/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[cartographer_node-1] [INFO] [1633772682.962312860] [cartographer_ros]: I1009 17:44:42.000000 34072 submap_2d.cc:187] Added submap 1
[cartographer_node-1] [INFO] [1633772682.962359870] [cartographer_ros]: I1009 17:44:42.000000 34072 map_builder_bridge.cc:132] Added trajectory with ID '0'.
[cartographer_node-1] [INFO] [1633772683.197696270] [cartographer_ros]: I1009 17:44:43.000000 34072 ordered_multi_queue.cc:172] All sensor data for trajectory 0 is available starting at '637693694832073997'.
[cartographer_node-1] [INFO] [1633772683.253851034] [cartographer_ros]: I1009 17:44:43.000000 34072 local_trajectory_builder_2d.cc:295] Extrapolator not yet initialized.
[cartographer_node-1] [INFO] [1633772683.253907953] [cartographer_ros]: I1009 17:44:43.000000 34072 local_trajectory_builder_2d.cc:138] Extrapolator is still initializing.
[rviz2-3] [INFO] [1633772683.652894702] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1633772683.653073992] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-3] [INFO] [1633772683.775757776] [rviz2]: Stereo is NOT SUPPORTED
[cartographer_node-1] [INFO] [1633772698.048022634] [cartographer_ros]: I1009 17:44:58.000000 34072 collated_trajectory_builder.cc:72] odom rate: 19.93 Hz 5.02e-02 s +/- 2.92e-03 s (pulsed at 99.36% real time)
[cartographer_node-1] [INFO] [1633772698.048059302] [cartographer_ros]: I1009 17:44:58.000000 34072 collated_trajectory_builder.cc:72] scan rate: 4.78 Hz 2.09e-01 s +/- 4.04e-02 s (pulsed at 99.95% real time)
[cartographer_node-1] [INFO] [1633772713.091671319] [cartographer_ros]: I1009 17:45:13.000000 34072 collated_trajectory_builder.cc:72] odom rate: 20.00 Hz 5.00e-02 s +/- 2.55e-05 s (pulsed at 100.02% real time)
[cartographer_node-1] [INFO] [1633772713.091830137] [cartographer_ros]: I1009 17:45:13.000000 34072 collated_trajectory_builder.cc:72] scan rate: 4.92 Hz 2.03e-01 s +/- 2.31e-02 s (pulsed at 100.01% real time)
[INFO] [rviz2-3]: process has finished cleanly [pid 34076]
[cartographer_node-1] [INFO] [1633772728.140846151] [cartographer_ros]: I1009 17:45:28.000000 34072 collated_trajectory_builder.cc:72] odom rate: 20.00 Hz 5.00e-02 s +/- 3.36e-05 s (pulsed at 100.01% real time)
[cartographer_node-1] [INFO] [1633772728.141031330] [cartographer_ros]: I1009 17:45:28.000000 34072 collated_trajectory_builder.cc:72] scan rate: 4.65 Hz 2.15e-01 s +/- 5.19e-02 s (pulsed at 100.00% real time)
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[cartographer_node-1] [INFO] [1633772729.112062232] [rclcpp]: signal_handler(signal_value=2)
[occupancy_grid_node-2] [INFO] [1633772729.112039054] [rclcpp]: signal_handler(signal_value=2)
[cartographer_node-1] [INFO] [1633772729.113336128] [cartographer_ros]: I1009 17:45:29.000000 34072 node.cc:545] Shutdown the subscriber of [scan]
[cartographer_node-1] [INFO] [1633772729.113414107] [cartographer_ros]: I1009 17:45:29.000000 34072 node.cc:545] Shutdown the subscriber of [odom]
[cartographer_node-1] [INFO] [1633772729.122393438] [cartographer_ros]: I1009 17:45:29.000000 34072 map_builder_bridge.cc:149] Finishing trajectory with ID '0'...
[cartographer_node-1] [INFO] [1633772729.122869022] [cartographer_ros]: I1009 17:45:29.000000 34072 map_builder_bridge.cc:158] Running final trajectory optimization...
[cartographer_node-1] [INFO] [1633772729.122985180] [cartographer_ros]: I1009 17:45:29.000000 34087 constraint_builder_2d.cc:281] 0 computations resulted in 0 additional constraints.
[cartographer_node-1] [INFO] [1633772729.123085523] [cartographer_ros]: I1009 17:45:29.000000 34087 constraint_builder_2d.cc:283] Score histogram:
[cartographer_node-1] Count: 0
[INFO] [occupancy_grid_node-2]: process has finished cleanly [pid 34074]
[cartographer_node-1] [INFO] [1633772729.153763852] [cartographer_ros]: I1009 17:45:29.000000 34087 pose_graph_2d.cc:382] Remaining work items in queue: 1
[cartographer_node-1] [INFO] [1633772729.155559882] [cartographer_ros]: I1009 17:45:29.000000 34090 constraint_builder_2d.cc:281] 0 computations resulted in 0 additional constraints.
[cartographer_node-1] [INFO] [1633772729.155641130] [cartographer_ros]: I1009 17:45:29.000000 34090 constraint_builder_2d.cc:283] Score histogram:
[cartographer_node-1] Count: 0
Optimizing: Done.     
[cartographer_node-1] [INFO] [1633772729.185986769] [cartographer_ros]: I1009 17:45:29.000000 34090 constraint_builder_2d.cc:281] 0 computations resulted in 0 additional constraints.
[cartographer_node-1] [INFO] [1633772729.186053366] [cartographer_ros]: I1009 17:45:29.000000 34090 constraint_builder_2d.cc:283] Score histogram:
[cartographer_node-1] Count: 0
Optimizing: Done.     
[cartographer_node-1] [INFO] [1633772729.189755717] [cartographer_ros]: I1009 17:45:29.000000 34089 constraint_builder_2d.cc:281] 0 computations resulted in 0 additional constraints.
[cartographer_node-1] [INFO] [1633772729.189821942] [cartographer_ros]: I1009 17:45:29.000000 34089 constraint_builder_2d.cc:283] Score histogram:
[cartographer_node-1] Count: 0
[INFO] [cartographer_node-1]: process has finished cleanly [pid 34072]

9. Please describe the issue in detail.

    ![Screenshot from 2021-10-09 17-45-18](https://user-images.githubusercontent.com/40068587/136653603-6466bec7-733e-481e-8c8e-32984b654d81.png)

    ![Screenshot from 2021-10-09 17-40-51](https://user-images.githubusercontent.com/40068587/136653642-1545abb6-1f30-444b-8066-7d0418c3c59a.png)

    ![Screenshot from 2021-10-09 17-57-57](https://user-images.githubusercontent.com/40068587/136653672-4923af10-6d09-4969-94be-64fa48dc4735.png)

    I'm new in ROS2 , and just received my turtlebot3 and follow the tutorial, when I'm using cartographer to do SLAM, in Rviz2 I got a "No map received" message like picture 1.
    I also echoed the data from `/scan` and it seems normal (picture 3), but doesn't show on rqt, also want to know how to fix this problem.
    I tried to search some similar issue but still can't fix it, please help me ><
    Thank you !

**Comment by LeonardBuhl** [comment]
This issue is also described in the official ROS2 issues:
https://github.com/ros2/rviz/issues/782

**Comment by EndlessLoops** [comment]
@LeonardBuhl Before I reply, I did not check the link you responded above. -_-!

**Comment by stu00608** [comment]
Thank for your help ! I'll close this issue.
