### ISSUE TITLE
Obstacle Detection does not start.

### ISSUE THREAD

**Issue by yuukinishi** [ROBOTIS-GIT/turtlebot3#792]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

     Burger
  

2. Which ROS is working with TurtleBot3?

    ROS 1 Kinetic Kame

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    Raspberry Pi 3B+

4. Which OS you installed on SBC?

    Raspbian distributed by ROBOTIS

5. Which OS you installed on Remote PC?

    Ubuntu 16.04 LTS (Xenial Xerus)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

   Turtlebot3 does not work even if I start the Obstacle Detection command listed in the e-Manual. Not only my machine, but my colleague's machine has similar symptoms. How should I solve it?

9. Please describe the issue in detail.

    - HERE

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
