### ISSUE TITLE
Can't configure motors with noetic adapted firmware (#define NOETIC_SUPPORT)

### ISSUE THREAD

**Issue by royito55** [ROBOTIS-GIT/turtlebot3#795]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [x] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [x] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [1.15.13]
    - Firmware version: [1.4.18]

7. Specify the commands or instructions to reproduce the issue.

    - Issue occurs while configuring motors according to Section 14.3 (FAQ) of Turtlebot3 Manual: https://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#faq.
    - I was able to configure them before (but with an Rtx error message) and test them, but when I used the special instructions for noetic on step 7 of OpenCR setup to upload firmware(https://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup-2), I am not able to configure them anymore.

8. Copy and Paste the error messages on terminal.

    - Sketch uses 117784 bytes (14%) of program storage space. Maximum is 786432 bytes.
Global variables use 40192 bytes of dynamic memory.
opencr_ld ver 1.0.2
opencr_ld_main 
>>
file name : /tmp/arduino_build_380048/turtlebot3_setup_motor.ino.bin 
file size : 116 KB
Open port OK
Clear Buffer Start
Clear Buffer End
>>
Board Name : OpenCR R1.0
Board Ver  : 0x17020800
Board Rev  : 0x00000000
>>
flash_erase : 0 : 0.994000 sec
flash_write : 0 : 1.323000 sec 
CRC OK B785A8 B785A8 0.004000 sec
[OK] Download 
jump_to_fw 
processing.app.SerialException: Error opening serial port '/dev/ttyACM0'.
	at processing.app.Serial.<init>(Serial.java:152)
	at processing.app.Serial.<init>(Serial.java:82)
	at processing.app.SerialMonitor$2.<init>(SerialMonitor.java:132)
	at processing.app.SerialMonitor.open(SerialMonitor.java:132)
	at processing.app.AbstractMonitor.resume(AbstractMonitor.java:132)
	at processing.app.Editor.resumeOrCloseSerialMonitor(Editor.java:2126)
	at processing.app.Editor.access$1300(Editor.java:116)
	at processing.app.Editor$UploadHandler.run(Editor.java:2095)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jssc.SerialPortException: Port name - /dev/ttyACM0; Method name - openPort(); Exception type - Port not found.
	at jssc.SerialPort.openPort(SerialPort.java:167)
	at processing.app.Serial.<init>(Serial.java:141)
	... 8 more
Error opening serial port '/dev/ttyACM0'.

9. Please describe the issue in detail.

    - I know that the issue is not the port ttyACM0, since I can see it in my PC, but maybe some of the port rules I updated from step 7. I did this step 7 because the communication between the rpi4 and the opencr was not working properly, and now it works but **only one motor moves, even though I configured them correctly and in the test it works**.
    - However, it has never worked by pushing the SW1 and SW2, only one motor works.
    - Now, with the new method to update the firmware from step 7, I can't even configure them again to try to make both motors move.
    - Again, it's not a motor or port issue, I've switched the motors to make sure, and not being able to configure the motors only happened after step seven.
    - I know it's a complicated setup and explanation, but what do you recommend? Should I start from scratch again? How can I configure the motors to work with noetic?

**Comment by sunghowoo** [comment]
Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. This issue will be closed due to prolonged inactivity. if the issue persists, feel free to reopen it.
