### ISSUE TITLE
Pi camera issues for ROS kinetic on Pi 3b+ 

### ISSUE THREAD

**Issue by stevensu1838** [ROBOTIS-GIT/turtlebot3#811]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.
Fail to install relevant Raspberry Pi Camera 
pi@raspberrypi:~ $ sudo apt-get install ros-kinetic-compressed-image-transport ros-kinetic-camera-info-manager
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-kinetic-compressed-image-transport
E: Unable to locate package ros-kinetic-camera-info-manager
pi@raspberrypi:~ $ 

8. Copy and Paste the error messages on terminal.
See above

9. Please describe the issue in detail.
After I installed the Raspbian ROS Kinetic OS for P 3b+, I did the following

Once logged in to the Raspberry Pi, execute the commands below to sync time.
$ sudo apt-get install ntpdate
$ sudo ntpdate ntp.ubuntu.com
Load Raspberry Pi configuration interface.
$ sudo raspi-config
Select Advanced Options > Expand Filesystem and exit.
 
And then I followed the following official document to activate and run the RPi camera, but no success. 
[Turtlebot3 Pi Camera Setup](https://emanual.robotis.com/docs/en/platform/turtlebot3/appendix_raspi_cam/#raspberry-pi-camera-for-turtlebot3) 
  
I can make sure the Pi camera is connected right and I've checked with different Pi 3b+ boards. same issues. Thanks a lot

**Comment by stevensu1838** [comment]
It turns out I can use the Pi camera without installing the following two package:

E: Unable to locate package ros-kinetic-compressed-image-transport
E: Unable to locate package ros-kinetic-camera-info-manager

When I run $ roslaunch turtlebot3_bringup turtlebot3_rpicamera.launch

Only a Warn message shows up and I can visualize the image on my remote PC. 

[ WARN] [1640498104.677588643]: Camera calibration file /home/pi/.ros/camera_info/camera.yaml not found.

The whole printout is shown as below:
pi@raspberrypi:~ $ roslaunch turtlebot3_bringup turtlebot3_rpicamera.launch
... logging to /home/pi/.ros/log/fef183dc-654c-11ec-a6ad-480fcf41d72a/roslaunch-raspberrypi-12191.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.0.108:38719/

SUMMARY
========

PARAMETERS
 * /raspicam_node/camera_frame_id: camera
 * /raspicam_node/camera_info_url: package://turtleb...
 * /raspicam_node/framerate: 15
 * /raspicam_node/height: 480
 * /raspicam_node/width: 640
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    raspicam_node (raspicam_node/raspicam_node)

ROS_MASTER_URI=http://192.168.0.104:11311

process[raspicam_node-1]: started with pid [12200]
[ INFO] [1640498104.496394676]: splitter component done

[ INFO] [1640498104.603253641]: camera calibration URL: package://turtlebot3_bringup/camera_info/turtlebot3_rpicamera.yaml
[ INFO] [1640498104.675481157]: Camera successfully calibrated from default file
[ INFO] [1640498104.676131205]: using default calibration URL
[ INFO] [1640498104.676628285]: camera calibration URL: file:///home/pi/.ros/camera_info/camera.yaml
[ INFO] [1640498104.677214427]: Unable to open camera calibration file [/home/pi/.ros/camera_info/camera.yaml]
[ WARN] [1640498104.677588643]: Camera calibration file /home/pi/.ros/camera_info/camera.yaml not found.
[ INFO] [1640498104.677889735]: No device specifc calibration found
[ INFO] [1640498104.819591295]: Starting video capture (640, 480, 80, 15)

[ INFO] [1640498104.821371961]: Video capture started

**Comment by ROBOTIS-Will** [comment]
Hi @stevensu1838 

Yes, the images are preinstalled with necessary packages to run TurtleBot3.
However, the provided Kinetic image is created before the ROS GPG Key incident, therefore, when trying to updating the package or installing a new package with `apt-get update` or `apt-get upgrade` commands will return such errors.
Please see below thread for more details and resolutions.
https://discourse.ros.org/t/ros-gpg-key-expiration-incident/20669/38

Thanks!

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
