### ISSUE TITLE
Teleop gives error on run

### ISSUE THREAD

**Issue by AmmarAlbakri** [ROBOTIS-GIT/turtlebot3#830]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ x] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [x ] etc (simulation)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ x] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch

8. Copy and Paste the error messages on terminal.

    Traceback (most recent call last):
  File "/home/ammar/catkin_ws/devel/lib/turtlebot3_teleop/turtlebot3_teleop_key", line 7, in <module>
    with open(python_script, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ammar/catkin_ws/src/turtlebot3/turtlebot3_teleop/nodes/turtlebot3_teleop_key'
[turtlebot3_teleop_keyboard-1] process has died [pid 46422, exit code 1, cmd /home/ammar/catkin_ws/devel/lib/turtlebot3_teleop/turtlebot3_teleop_key __name:=turtlebot3_teleop_keyboard __log:=/home/ammar/.ros/log/8d3bebdc-8ff0-11ec-983b-15a7f8611f80/turtlebot3_teleop_keyboard-1.log].

**Comment by ashekim** [comment]
Hello. Thank you for your question.

It seems the Turtlebot3 package is not installed properly.
Please refer to the link below and reinstall the Turtlebot3 package.
[Noetic version] [PC Setup](https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/#pc-setup-2)

Thank you.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
