### ISSUE TITLE
How to fix turtlebot3_gazebo building error?

### ISSUE THREAD

**Issue by nikboy111** [ROBOTIS-GIT/turtlebot3#840]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [x] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    I've been trying to setup the Turtlebot3 simulation using the [e-manua](https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/) for several days now, but I'm still running into the same problem over and over again.
Following the instruction of the manual made me install Gazebo for ROS using the debian package:

> sudo apt-get install ros-foxy-gazebo-*

After i follow the [manual](https://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/) for the installation of the simulation I run into the following error when building the workspace:

8. Copy and Paste the error messages on terminal.

> CMake Error at CMakeLists.txt:19 (find_package): By not providing "Findgazebo_ros_pkgs.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by
>     "gazebo_ros_pkgs", but CMake did not find one.
> 
>     Could not find a package configuration file provided by "gazebo_ros_pkgs" with any of the following names:
> 
>     gazebo_ros_pkgsConfig.cmake
>     gazebo_ros_pkgs-config.cmake
> 
>     Add the installation prefix of "gazebo_ros_pkgs" to CMAKE_PREFIX_PATH or set "gazebo_ros_pkgs_DIR" to a directory containing one of the above files. If "gazebo_ros_pkgs" provides a separate development package or SDK, be sure it has been installed.
> 
>     --- Failed <<< turtlebot3_gazebo [ Exited with code 1 ]
> 
>     Summary: 12 packages finished [9.23s] 1 package failed: turtlebot3_gazebo
>     1 package had stderr output: turtlebot3_gazebo 1 package not processed
> 

9. Please describe the issue in detail.

Browsing through the forums for answers I found out that installing the gazebo_ros packages would help. so i did that following these [instructions](http://gazebosim.org/tutorials?tut=ros2_installing&cat=connect_ros) which make me run into the following problem while building:

> CMake Error in CMakeLists.txt:
>   Imported target "dart" includes non-existent path
> 
>     "/include"
> 
>   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
> 
>   * The path was deleted, renamed, or moved to another location.
> 
>   * An install or uninstall procedure did not complete successfully.
> 
>   * The installation package was faulty and references files it does not
>   provide.
> 
> 
> 
> CMake Generate step failed.  Build files cannot be regenerated correctly.
> 
> Failed   <<< gazebo_ros [30.4s, exited with code 1]
> 
> Summary: 9 packages finished [41.5s]
>  1 package failed: gazebo_ros
>   1 package had stderr output: gazebo_ros
>   2 packages not processed

Does anyone know how to fix this?
Sicerly Niklas

**Comment by ashekim** [comment]
Hello @nikboy111.

I think you built gazebo_ros_pkgs as a source file.
`$ sudo apt install ros-foxy-gazebo-ros-pkgs`
Please install it as a binary rather than a build from source.

Thank you.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
