### ISSUE TITLE
Intrinsic Camera Calibration display issues with Turtlebot3 burger. 

### ISSUE THREAD

**Issue by kylehannibal** [ROBOTIS-GIT/turtlebot3#841]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [X] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [X] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [X] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [X] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [X] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - roslaunch turtlebot3_autorace_camera intrinsic_camera_calibration.launch mode:=calibration

8. Copy and Paste the error messages on terminal.

    - No error message, however no display shows as intended. 

9. Please describe the issue in detail.

    - After running all of the code in the auto race manual, the intrinsic camera calibration for the detection of lines on a track refuses to open. This works on a seperate computer, but not this one. There is no issue with the installation, all lines have been followed exactly as posted in the noetic version of the tutorial
[intrinsic_camera_calibration.txt](https://github.com/ROBOTIS-GIT/turtlebot3/files/8210176/intrinsic_camera_calibration.txt)

**Comment by ashekim** [comment]
Hello. @kylehannibal.

Please enter the `$ ls /dev/video0` command to check whether the camera is recognized by Turtlebot3.

Intrinsic camera calibration is the step of calibrating the inside of the camera. 
So the extrinsic camera calibration will detect the lines on the track.

thank you.
