### ISSUE TITLE
Using new model Lidar with Turtlebot3

### ISSUE THREAD

**Issue by pitosalas** [ROBOTIS-GIT/turtlebot3#852]
I recently received a new Lidar for my Turtlebot3. The TB3 is a couple of years old and for one reason or another its Lidar "broke". As you know, TB3 now is supplied with a newer Lidar LDS-02. When we installed the new Lidar with the software that worked otherwise we see the following.

The Lidar does spin, it does publish /scan -- but we don't see any data coming over the topic. 

Could this be because some slight difference between LDS-01 and LDS-02?

**Comment by ROBOTIS-Will** [comment]
Hi @pitosalas 
The LDS-02 starts rotating as soon as it is powered.
Please make sure if you added the LDS version setting in your `.bashrc` file.
```
$ echo 'export LDS_MODEL=LDS-02' >> ~/.bashrc
$ source ~/.bashrc
```

Could you give us more details about which version of ROS you are running and how to reproduce the issue with a list of commands you entered?
Thank you.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
