### ISSUE TITLE
turtlebot3_frontier_exploration

### ISSUE THREAD

**Issue by YXGuan** [ROBOTIS-GIT/turtlebot3#854]
1. Which TurtleBot3 platform do you use?

    - [ ] Burger

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Noetic Ninjemys

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 4

4. Which OS you installed on SBC?

    - [ ] Ubuntu preinstalled server (18.04/20.04)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 20.04 LTS (Focal Fossa)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

`     roslaunch turtlebot3_slam turtlebot3_frontier_exploration.launch `
https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_slam/launch/turtlebot3_frontier_exploration.launch

8. Copy and Paste the error messages on terminal.

`ERROR: cannot launch node of type [frontier_exploration/explore_client]: Cannot locate node of type [explore_client] in package [frontier_exploration]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [frontier_exploration/explore_server]: Cannot locate node of type [explore_server] in package [frontier_exploration]. Make sure file exists in package path and permission is set to executable (chmod +x)
`

9. Please describe the issue in detail.

   Hi there, I still could not locate explore_client and explore_server node after installing the frontier_exploration library 
![image](https://user-images.githubusercontent.com/55643200/163693798-496ef2ca-4cce-4e87-869e-d7210586461c.png)
Your help would be much appreciated.

**Comment by ROBOTIS-Will** [comment]
Hi @YXGuan 

It looks like the Frontier Exploration package has been deprecated since Melodic and has not been properly developed for Noetic.
You may want to try other similar packages instead such as [explore_lite](http://wiki.ros.org/explore_lite)

Thanks.
