### ISSUE TITLE
Issue with Turtlebot3 - Ros 2 Foxy - SLAM

### ISSUE THREAD

**Issue by Comet92** [ROBOTIS-GIT/turtlebot3#856]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [ x ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ x ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ x ] Raspberry Pi 4 2GB
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ x ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ x ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]
  
Sorry I don't know where to find this information. As I looked at the Bringup messages there was no mention of the Software or Firmware version

7. Specify the commands or instructions to reproduce the issue.

    - source /opt/ros/foxy/setup.bash
    - export TURTLEBOT3_MODEL=waffle_pi
    - ros2 launch turtlebot3_cartographer cartographer.launch.py

I basically did as explained in the "Getting started " tutorial of the robotis website. And I also did the bringup in another terminal as well. I tried to find many solution to this problem, unsuccessfully however.

8. Copy and Paste the error messages on terminal.

    - Package 'turtlebot3_cartographer' not found: "package 'turtlebot3_cartographer' not found, searching: ['/home/ubuntu/turtlebot3_ws/install/turtlebot3', '/home/ubuntu/turtlebot3_ws/install/turtlebot3_teleop', '/home/ubuntu/turtlebot3_ws/install/turtlebot3_bringup', '/home/ubuntu/turtlebot3_ws/install/turtlebot3_node', '/home/ubuntu/turtlebot3_ws/install/turtlebot3_example', '/home/ubuntu/turtlebot3_ws/install/turtlebot3_description', '/home/ubuntu/turtlebot3_ws/install/ld08_driver', '/opt/ros/foxy']"

9. Please describe the issue in detail.

Dear Robotis team,

I am a french student in computer science and I am currently working on a robotic project in my university. As part of it, I have to use a Turtlebot 3 (waffle) using ros2 foxy. The Turtlebot3 was bought last November and I began to work on it in February.

As of now, I have managed to use the teleoperation quite effectively. However, I have found huge troubles when trying to use the SLAM.

I am currently following the Robotis Turtlebot3 quick start manual (https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/) and I followed every single step of the process.

My issue is that when I try to use the following command on my remote computer :

ros2 launch turtlebot3_cartographer [cartographer.launch.py](http://cartographer.launch.py/)

My computer seems unable to find any package named cartographer (as seen in the screen picture provided along this email).

I tried to solve this issue by myself at first. For instance I used other sources of information on the internet about the ros2 cartographer, but I was unsuccessful as all I did was not working properly or not even at all. I also tried to reinstall the turtlebot3's software completely, but the issue with the cartographer is still there.

I tried to check in the robot's directory if I was able to find such a package and I did. Nontheless I don't see how I could make it work. Thus I send you this in the hope that you will be able to help me with this issue.

![Capture d’écran du 2022-05-10 09-26-04](https://user-images.githubusercontent.com/85106244/167574067-8ad4f1d2-f525-4ab9-bc70-9e4213b81f0a.png)

**Comment by ROBOTIS-Will** [comment]
Hi @Comet92 

The Cartographer must be installed and launched on your `PC`, not on the TurtleBot3 RPi.
If you have installed the desktop version of Foxy, you should have it installed along with Foxy, but if you haven't, please refer to the thread below.
https://github.com/ros2/cartographer/issues/19#issuecomment-654301213

**Comment by whni** [comment]
> Hi @Comet92
> 
> The Cartographer must be installed and launched on your `PC`, not on the TurtleBot3 RPi. If you have installed the desktop version of Foxy, you should have it installed along with Foxy, but if you haven't, please refer to the thread below. [ros2/cartographer#19 (comment)](https://github.com/ros2/cartographer/issues/19#issuecomment-654301213)

Hi @ROBOTIS-Will is there any specific reason that we cannot run cartographer on the robot and see the map on PC? I can see cartographer is running correctly on my robot but on PC rviz2, it shows "no map received"

Thank you!
