### ISSUE TITLE
Turtlebot3 not getting connected to the ubuntu terminal 

### ISSUE THREAD

**Issue by kchanakya91** [ROBOTIS-GIT/turtlebot3#859]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - 

- [ ] [ ] Burger

    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ 

- [ ] ] ROS 1 Melodic Morenia

    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - 

- [ ] [ ] Raspberry Pi 4

    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - 

- [ ] [ ] Raspbian distributed by ROBOTIS

    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - 

- [ ] Ubuntu preinstalled server (18.04/20.04)

    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ 

- [ ] ] Ubuntu 18.04 LTS (Bionic Beaver)

    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [1.14.13]

7. Specify the commands or instructions to reproduce the issue.

 

8. Copy and Paste the error messages on terminal.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun May 15 00:44:22 2022 from 10.200.144.242
pi@raspberrypi:~ $ roslaunch turtlebot3_bringup turtlebot3_robot.launch
... logging to /home/pi/.ros/log/27192726-d3a6-11ec-a485-dca6320a1aab/roslaunch-raspberrypi-29338.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.200.12.58:43889/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (ld08_driver/ld08_driver)

RLException: ERROR: unable to contact ROS master at [http://master:11311]
The traceback for the exception was written to the log file

9. Please describe the issue in detail.

We are unable to connect to the turtlebot3 using my pc.

**Comment by ROBOTIS-Will** [comment]
Hi @kchanakya91 

Have you searched similar keywords like #608?
You may not have completed the network environment setup.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
