### ISSUE TITLE
Existing package error issue due to Python 3 upgrade -> roslaunch turtlebot3_bringup turtlebot3_robot.launch  

### ISSUE THREAD

**Issue by 0Roo** [ROBOTIS-GIT/turtlebot3#866]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Waffle

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Melodic Morenia

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 3B+

4. Which OS you installed on SBC?

    - [ ] Ubuntu preinstalled server (18.04/20.04)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - roslaunch turtlebot3_bringup turtlebot3_robot.launch

8. Copy and Paste the error messages on terminal.

    - RLException: ERROR: unable to contact ROS master at [http://192.168.0.31:11311]
The traceback for the exception was written to the log file

9. Please describe the issue in detail.

    - To use Python 3,
 $ sudo apt install python3-pip python3-all-dev python3-rospkg
 $ sudo apt install ros-melodic-desktop-full --fix-missing
  Enter to modify the rospkg.
Personally written python3 files work well in ros, but when I run the previously given package, I get the above error message.
As far as I know, the existing package was written in python 2, is there a way to continue using it?
Alternatively, can you tell us an example of the code to control the motor's motion through cmd_veltopic to implement the robot's motion part?

**Comment by ROBOTIS-Will** [comment]
Your issue `unable to contact ROS master` doesn't seem to be related to the Python version.
Please see below similar issues.
https://github.com/ROBOTIS-GIT/turtlebot3/issues?q=unable+to+contact+ROS+master+

Converting `cmd_vel` to DYNAMIXEL command can be found from OpenCR TurtleBot3 firmware
https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/examples/turtlebot3_waffle/turtlebot3_core/turtlebot3_core.ino#L165
https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/examples/turtlebot3_waffle/turtlebot3_core/turtlebot3_core.ino#L803
https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/examples/turtlebot3_waffle/turtlebot3_core/turtlebot3_core.ino#L90

**Comment by sunghowoo** [comment]
@0Roo This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
