### ISSUE TITLE
LiDAR - location of 0 degree value and possiblity to stop lidar from rotating while measuring

### ISSUE THREAD

**Issue by florianfhws** [ROBOTIS-GIT/turtlebot3#869]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ x] Waffle
    - [x ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ x] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [x ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

  roslaunch hls_lfcd_lds_driver hlds_laser.launch

8. Copy and Paste the error messages on terminal.

-

9. Please describe the issue in detail.

We observed that the 0 degree angle measurement of the LIDAR sensor is not at the horizontal axis going through the sensor but  2 degrees off. So even when the sensor is perfectly straight mounted on the robot the zero degree measurement will be 2 degrees off. 
Is this expected behavior?

Additionally we would like to anaylze the LIDAR accuracy however this is complicated when the LIDAR is rotating is it possible to use the sensor with rotation disabled?

**Comment by ajsnyde** [comment]
Also wondering if you can use the distance measuring regardless of rpm.

**Comment by sunghowoo** [comment]
@florianfhws This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
