### ISSUE TITLE
Navigation Issue in Noetic

### ISSUE THREAD

**Issue by pradrn** [ROBOTIS-GIT/turtlebot3#870]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [x] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=$HOME/map.yaml

8. Copy and Paste the error messages on terminal.

![Screenshot from 2022-06-01 13-37-10](https://user-images.githubusercontent.com/40749183/171359435-ed9cb574-d098-4425-9cae-5b87202d5b7a.png)
![Screenshot from 2022-06-01 13-37-36](https://user-images.githubusercontent.com/40749183/171359733-61241d18-db8e-4bc3-b4b5-9a00e8c676c5.png)

9. Please describe the issue in detail.

![Screenshot from 2022-06-01 13-36-57](https://user-images.githubusercontent.com/40749183/171359556-da29f429-ce57-43c4-a47d-89c03f8c091f.png)

So when i was running the Navigation Tutorial, I was not getting the LDS sensor overlay on my map. And i was continuously getting warnings regarding Costmap2ROS as you can see in the images present. Please help in solving this issue for me.

**Comment by ROBOTIS-Will** [comment]
Hi @pradrn 
There is an identical issue #78.
Does it help to solve your problem?

**Comment by pradrn** [comment]
Hi,

So i did have a look at the identical issue #78 as mentioned. I am yet to try fiddling around with chrony config file and DS3231.

This is the frequency of the tf topics which i checked
![Screenshot from 2022-06-02 12-20-36](https://user-images.githubusercontent.com/40749183/171573360-30beb8eb-d81c-412d-b1f3-ffebe7b5b80b.png)

I tried to sync the time between the remote laptop and the RasPi. I ran the command in both remote PC and the RasPi
![Screenshot from 2022-06-02 12-22-00](https://user-images.githubusercontent.com/40749183/171573587-7009b785-d73e-40b7-bc40-36b8ce1a7f5e.png)
![Screenshot from 2022-06-02 12-26-56](https://user-images.githubusercontent.com/40749183/171573633-a1d4d22a-d270-4dad-8592-14045bbfcb49.png)

I then used the command `sudo date -s "dd mm yyy hh:mm:ss` to update the time manually. Then i ran the navigation command again, yet the same issue continued. The LDS overlap was missing and the Costmap2ROS warning were present.

![Screenshot from 2022-06-02 12-27-39](https://user-images.githubusercontent.com/40749183/171573902-f0413926-970f-4495-bde3-02e5ffc3f5c2.png)

**Comment by BENBEY-I** [comment]
i had the same problem, here's the steps that i did to solve it : 
- deactivated the automatic date and time in the PC setting 
- changed the time ( -2h to have UTC time)
try this 2 steps if it doesn't work try to change the time in the raspberry using the command sudo date -s "dd mm yyy hh:mm:ss"

i solved it just by setting the time

**Comment by pradrn** [comment]
Hi @BENBEY-I,

Thanks for the response. I tried the steps you mentioned and disabled the automatic date and time in remote PC, changed the time in both RasPi and PC so that  they match. The warnings and LDS overlay did not occur.

In addition to this, next I played  around with the  RTC to make sure that it is synced with the local time and TZ. After this I reenabled the NTP in  both remote and RasPi.

Unfortunately, I was still not  able to get the LDS overlay and the warnings  for Costmap2DROS was present.

**Comment by sunghowoo** [comment]
@pradrn Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
