### ISSUE TITLE
Problem about Lidar LaserScan not attatch to map issue / 라이다 스캔 데이터가 맵에 고정되지 않는 문제

### ISSUE THREAD

**Issue by RounLee1** [ROBOTIS-GIT/turtlebot3#872]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [o ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [o ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ o] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ o] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [o ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

roslaunch turtlebot_navigation turtlebot_navigation

8. Copy and Paste the error messages on terminal.

[ WARN] []: global_costmap: Pre-Hydroparameter “static_map” unused since “plugins” is provided
[ WARN] []: global_costmap: Pre-Hydroparameter “map_type” unused since “plugins” is provided
[ INFO] []: global_costmap: Using plugin “static_layer”
[ INFO] []: Requesting the map…
[ INFO] []: Resizing costmap to 384 X384 at 0.050000 m/pix
[ INFO] []: Received a 384 X 384 map at 0.050000 m/pix
[ INFO] []: Subscribing to updates
[ INFO] []: global_costmap: Using plugin “inflation_layer”
[ WARN] []: local_costmap: Pre-Hydro parameter “static_map” unused since “plugins” is provided
[ WARN] []: local_costmap: Pre-Hydro parameter “map_type” unused since “plugins” is provided
[ INFO] []: local_costmap: Using plugin “obstacle_layer”
[ INFO] []: Subscribed to Topics:scan_filtered
[ INFO] []: local_costmap: Using plugin “inflation_layer”
[ INFO] []: Created local_planner dwa_local_planner/DWAPlannerROS
[ INFO] []: Sim period is set to 0.20

10. Please describe the issue in detail.

I'm trying to launch turtlebot_navigation without OPENCR, just using dynamixel, imu, Lidar directly connect to Raspberry pi 4 

현재 다이나믹셀, IMU, 그리고 YDlidar사의 X4 Lidar로 OpenCR없이 라즈베리파이에 USB로 직접 연결하여 터틀봇 네비게이션을 해보려 하는 시도 중에 있습니다.

I already finished tf tree, urdf setting, and also check rqt_graph and it as same as the book "ROS 로봇 프로그래밍" which handle about ROBOTIS Turtlebot's slam, navigation. And also i can change it by publish tf and urdf from Lidar itself. Odometry included.

이미 tf, urdf 설정에 관한 시도를 해보았으며, rqt_graph와 rqt_tf_tree를 확인해보았을 때, ROS 로봇 프로그래밍이라는 책의 터틀봇 tf tree 구조와 일치하였습니다. 또한 이 정보를 해당 구조와 동일 구조가 아닌 라이다 자체에서 발급하는 urdf와 tf 사용도 해보았습니다. Odometry도 정상적임을 확인하였습니다.

When launch turtlebot_navigation 

 터틀봇 네비게이션 패키지를 실행시켰을 때

There are always errors about Lidar Scan data did not attach to the map, so that move_base(navigation) not work properly

 항상 라이다 데이터가 예시 영상들과 달리 맵에 붙어 있지 않고 움직이며 그로인해 자율 주행이 적절히 되지 않는 것 같습니다.

Furthermore, When i checks the param folder, costmap yaml, global yaml, local yaml, There's any plugin setting and also not set to scan topic name to scan_filtered, It just set to the original(github ver) file.

파라미터 내부 yaml 파일들을 체크했을 때도 어떤 플러그인 설정이나 토픽명을 INFO에 한 것과 같은 설정이 되어있지 않습니다.

Errors pop up again although i purge the package (ros-melodic-navigation, turtlebot-navigation) and reinstall it

ros-melodic-navigation과 turtlebot-navigation을 삭제 후 재설치에도 같은 에러가 발생합니다.

혹시 도움을 얻을 수 있을까요?

**Comment by ROBOTIS-Will** [comment]
Hi, @RounLee1 

If you are running the TurtleBot3 without the OpenCR, you're missing the IMU sensor which calculates position and compensates position errors along with the LDS sensor.
Since OpenCR not only publishes IMU data, but also calculates and publishes motor encoder value for odometry, running TurtleBot3 without the OpenCR may cause several issues.

Please understand that removing / replacing the core component of the product isn't something we can support.
Thank you.

**Comment by sunghowoo** [comment]
@RounLee1 This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
