### ISSUE TITLE
Having trouble to bring up

### ISSUE THREAD

**Issue by Keita1Mori** [ROBOTIS-GIT/turtlebot3#878]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [x] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [x] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    

8. Copy and Paste the error messages on terminal.

    <img src ="https://user-images.githubusercontent.com/71181654/174522867-3636aa39-e6c5-4e66-be9c-51196433cae5.jpg" width = "320px">

9. Please describe the issue in detail.

    -

**Comment by ashekim** [comment]
Hi @Keita1Mori.
Thank you for your questions.

Please reset OpenCR by referring to the attached [link](https://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup).
If the same problem still occurs, please replace the USB cable.

Thank you.

**Comment by Keita1Mori** [comment]
Thanks.
I will try it.

**Comment by Keita1Mori** [comment]
Couldn't update on Ubuntu mate
<img src = "https://user-images.githubusercontent.com/71181654/174765146-c245627f-2911-4c87-b231-e9a2156a8193.jpeg" width = "320px">

**Comment by ashekim** [comment]
Hi @Keita1Mori 
Please check if the Rpi network is connected.
I'm attaching a [link](https://askubuntu.com/questions/91543/apt-get-update-fails-to-fetch-files-temporary-failure-resolving-error) with a problem similar to yours.


Additionally,
We are providing the SBC image for the convenience of users.
We recommend that you use the [images](https://emanual.robotis.com/docs/en/platform/turtlebot3/sbc_setup/#sbc-setup) we provide.

Thank you.

**Comment by Keita1Mori** [comment]
I'm still having trouble for opencr setting I tried the switching but still it says NG. What is wrong with this?
<img src = "https://user-images.githubusercontent.com/71181654/175464128-cd2f269c-9b11-4b77-89b8-19f6b92038c8.jpeg" width = "320px">

**Comment by ROBOTIS-Will** [comment]
@Keita1Mori 

It looks like you didn't configured the serial port access for OpenCR.
Please fix the permission of the OpenCR connected port (in Ubuntu, it is /dev/ttyACM0)
```bash
$ sudo usermod -aG dialout turtlebot3
```
then reboot to apply the permission.

**Comment by Keita1Mori** [comment]
Thanks I have solved that problem but I still have another problem with this can you help me to solve it?
<img src = "https://user-images.githubusercontent.com/71181654/175506095-49ae4e54-9228-4647-984f-2da3267d4061.jpeg" width = "320px">

**Comment by ashekim** [comment]
@Keita1Mori 

Hi.
Please check if the launch file of the package to be executed exists.
And build again after installing the package.

Thank you.

**Comment by sunghowoo** [comment]
@Keita1Mori This issue will be closed due to prolonged inactivity. If the issue persists, feel free to reopen it.
