### ISSUE TITLE
How turtlebot3 connect with remote PC?

### ISSUE THREAD

**Issue by KaiqiaoTian** [ROBOTIS-GIT/turtlebot3#88]
Hi, I just got my turtlebot 3 , and confuse by the wifi connect with remote PC.

Pls help.

Thanks,
kaiqiao

**Comment by plguhur** [comment]
Well this is pretty well explained in the tutorials: https://turtlebot3.readthedocs.io/en/latest/sbc_software.html

Where are you stucked? Which model do you have?

**Comment by KaiqiaoTian** [comment]
Hi, 
I have turtlebot 3 burger. I follow the tutorials. But I don't know it connect with wifi or bluetooth?

There is no wifi module in turtlebot 3 burger. and I try bluetooth,  it cannot find remote pc.

Thanks
kaiqiao

**Comment by YuehChuan** [comment]
@KaiqiaoTian  ou need to have a small router, both remote PC and Raspberry pi3 connect under that router.
ex: 192.168.0. X

**Comment by routiful** [comment]
Hi @KaiqiaoTian :)

Raspberry Pi 3 supports wifi and bluetooth. [[Ref](https://www.raspberrypi.org/products/raspberry-pi-3-model-b/)]
So, you can connect between burger and remote pc by using TCP/IP communication.
Before you operate burger, you need to take some steps.
Here is a tutorial link for it.

[[Remote PC]](https://turtlebot3.readthedocs.io/en/latest/pc_software.html#network-configuration)

[[TurtleBot3]](https://turtlebot3.readthedocs.io/en/latest/sbc_software.html#network-configuration-burger-and-waffle)

If you have any problem while you following this step, please feel free to comment for me.
Thanks
Darby

**Comment by KaiqiaoTian** [comment]
It works now, under the same router. Thanks guys.
