### ISSUE TITLE
Cartographer 3D with depth camera not working [simulation]

### ISSUE THREAD

**Issue by lorenzo-bianchi** [ROBOTIS-GIT/turtlebot3#881]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [X] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [X] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [X] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

7. Specify the commands or instructions to reproduce the issue.

    - export TURTLEBOT3_MODEL=waffle_pi
    - ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
    - ros2 launch turtlebot3_cartographer cartographer.launch.py use_sim_time:=True configuration_basename:=turtlebot3_3d.lua

8. Copy and Paste the error messages on terminal.

    - I have no error on terminal

9. Please describe the issue in detail.

Hello everyone,
I'm trying to obtain a 3D map like [https://user-images.githubusercontent.com/33628476/51532693-16753b80-1e41-11e9-9c31-c74adcb8a22a.png](this) using Waffle Pi's depth camera but the result I obtain is completely bad.
As soon as I launch cartographer node I obtain in RViz the point cloud from topic /points2 but after just some seconds all the points start rotating because of frames misalignment due to cartographer. Moreover imu_link appears and disappears continuously.

![Schermata del 2022-06-26 18-17-47](https://user-images.githubusercontent.com/38653958/175824644-cddf10cc-cb9a-4aea-9839-008816e46382.png)
![Schermata del 2022-06-26 18-20-10](https://user-images.githubusercontent.com/38653958/175824646-668e28d6-a1c6-43a4-8e95-b90709b4fb5c.png)

I think the problem might be in some parameters of lua file, pasted below:

`include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "imu_link",
  published_frame = "odom",
  odom_frame = "odom",
  provide_odom_frame = false,
  publish_frame_projected_to_2d = false,
  use_odometry = true,
  use_nav_sat = false,
  use_landmarks = false,
  
  num_laser_scans = 0,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  
  num_point_clouds = 1,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
  landmarks_sampling_ratio = 1.,
}

TRAJECTORY_BUILDER_3D.num_accumulated_range_data = 1
TRAJECTORY_BUILDER_3D.min_range = 0.2
TRAJECTORY_BUILDER_3D.max_range = 15.
TRAJECTORY_BUILDER_3D.use_online_correlative_scan_matching = true

MAP_BUILDER.use_trajectory_builder_3d = true
MAP_BUILDER.num_background_threads = 7

POSE_GRAPH.optimization_problem.huber_scale = 5e2
POSE_GRAPH.optimization_problem.log_solver_summary = true
POSE_GRAPH.optimize_every_n_nodes = 0 -- 0 to disable global SLAM
POSE_GRAPH.constraint_builder.sampling_ratio = 0.03
POSE_GRAPH.optimization_problem.ceres_solver_options.max_num_iterations = 20
POSE_GRAPH.constraint_builder.min_score = 0.62
POSE_GRAPH.constraint_builder.global_localization_min_score = 0.66

POSE_GRAPH.optimization_problem.local_slam_pose_translation_weight = 1e3
POSE_GRAPH.optimization_problem.local_slam_pose_rotation_weight = 1e3
POSE_GRAPH.optimization_problem.odometry_translation_weight = 1e1
POSE_GRAPH.optimization_problem.odometry_rotation_weight = 1e1

return options`

I tried to make many modifications but the result is always the same.

I would really appreciate if you could help me fix this problem.
Thanks in advance.

**Comment by sunghowoo** [comment]
@lorenzo-bianchi Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
