### ISSUE TITLE
ubuntu20.04, Motor does not work 

### ISSUE THREAD

**Issue by boglebogle7** [ROBOTIS-GIT/turtlebot3#883]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [ o ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ o ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ o ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ o ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ o ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - Arduino IDE -> Example ->"setup motor" sketch

8. Copy and Paste the error messages on terminal.
After setup (1,2)->
 There is no status packet!  
Cannot Find ID1
Cannot Find ID2

9. Please describe the issue in detail.
    -  In Emanuel -> Teleoperation, it does not not work at all, though bringup does not have any problems. 
    - So, i tried motor test with Arduino IDE for Dynamixel. But there was an error to find ID of motors during setup sketch.
    -  I just kept following every steps on Emanuel, and it was okay for other waffles. That's why I am confused with this situation. Is there any ideas to check the connection of motors?

**Comment by ROBOTIS-Will** [comment]
Hi @kibomun 

When configuring DYNAMIXEL with the `setup motor` Arduino sketch, only one DYNAMIXEL should be connected to the OpenCR during the setup process.

Also, please make sure to update the OpenCR board manager and DYNAMIXEL2Arduino Arduino library to the latest version which resolves ROS2 communication issue.
https://github.com/ROBOTIS-GIT/OpenCR/issues/310

Thanks!

**Comment by sunghowoo** [comment]
@boglebogle7 This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
