### ISSUE TITLE
When can I use 10.Example section for foxy ?

### ISSUE THREAD

**Issue by boglebogle7** [ROBOTIS-GIT/turtlebot3#888]
Hello, 
When entering 10,Example section(https://emanual.robotis.com/docs/en/platform/turtlebot3/basic_examples/#move-using-interactive-markers), it says " NOTE: This feature is available for Kinetic, Dashing only."
though i remembered that it was okay for foxy users.
So I wonder when it would be possible to be accessed.  
Thanks A LOT!! :)

**Comment by ROBOTIS-Ashe** [comment]
@boglebogle7 

It is guided by Dashing standards, but you can try it in the Foxy version.
Unfortunately, an e-manual Foxy version is not yet planned.
thank you!
