### ISSUE TITLE
Enable Pi Camera v2.1 for Noetic / Melodic for Pi 4 (Pi OS) needs updating

### ISSUE THREAD

**Issue by LW-G38** [ROBOTIS-GIT/turtlebot3#903]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [x] ROS 1 Melodic Morenia
    - [x] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [x] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [1.15.14]
    - Firmware version: [1.2.6]

7. Specify the commands or instructions to reproduce the issue.

   -I own a Turtlebot3 waffle pi with Pi 3b. Recently I decided to upgrade it with my Pi4, a new LDS-02, and a Pi camera v2.1 module. I first used Noetic (Ubuntu 20.04 server), but it seems like Pi camera is not supported by the given image file of Ubuntu 20.04 in Turtlebot3 eManual - it's arm64. I think Pi camera v2.1 may only work with archhf for Ubuntu systems.

Then I tried an alternative solution - using Melodic for Pi OS for my Pi4. Thus, I can configure the Pi camera from the Pi OS, which is much easier with raspi-config functions. Unfortunately, the link of Melodic for Pi OS in the eManual is too old and it could not boot.

I think an easy solution could be an update of Melodic for Pi OS, or if you can give me instructions of enabling Pi Camera v2.1 on Ubuntu arm64 that will be great. Thanks! 

8. Copy and Paste the error messages on terminal.

    - N/A

9. Please describe the issue in detail.

    - Please see No.7

**Comment by wojciechmadry** [comment]
I had a similar problem on ROS 2 Galactic Ubuntu arm64, these steps fix my issue with raspicam:

1. Add those lines to /boot/firmware/config.txt before uart line
```
start_x=1
gpu_mem=256
```

2.  Install userland (I think it is not necessary but I'm not sure.)
```
sudo apt install cmake
git clone https://github.com/raspberrypi/userland.git
cd userland
./buildme --aarch64
touch ~/.bash_aliases
echo -e 'PATH=$PATH:/opt/vc/bin\nexport PATH' >> ~/.bash_aliases
echo -e 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/vc/lib\nexport LD_LIBRARY_PATH' >> ~/.bash_aliases
source ~/.bashrc
ldconfig
```

3. Create file /etc/udev/rules.d/10-vchiq-permissions.rule and insert

```
SUBSYSTEM==\"vchiq\",GROUP=\"video\",MODE=\"0660\"
```

4. `sudo usermod -a -G video ubuntu`

5.  `sudo apt-get install libraspberrypi-bin libraspberrypi-dev`

6. Reboot system

7. Test if the camera works `raspistill -o image.jpg`
