### ISSUE TITLE
When you run bringup in dashing, it looks like this

### ISSUE THREAD

**Issue by kimjunho654** [ROBOTIS-GIT/turtlebot3#905]
ubuntu@ubuntu:~/turtlebot3_ws$ ros2 launch turtlebot3_bringup robot.launch.py
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-09-08-10-44-07-366243-ubuntu-17884
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : turtlebot3_waffle.urdf
[ERROR] [launch]: Caught exception in launch (see debug for traceback): init() missing 1 required keyword-only argument: ‘node_executable’
[INFO] [robot_state_publisher-1]: process started with pid [17894]
Task exception was never retrieved
future: <Task finished coro=<LaunchService._process_one_event() done, defined at /opt/ros/dashing/lib/python3.6/site-packages/launch/launch_service.py:179> exception=RuntimeError(‘Signal event received before subprocess transport available.’,)>
Traceback (most recent call last):
File “/opt/ros/dashing/lib/python3.6/site-packages/launch/launch_service.py”, line 181, in _process_one_event
await self.__process_event(next_event)
File “/opt/ros/dashing/lib/python3.6/site-packages/launch/launch_service.py”, line 201, in __process_event
visit_all_entities_and_collect_futures(entity, self.__context))
File “/opt/ros/dashing/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py”, line 38, in visit_all_entities_and_collect_futures
sub_entities = entity.visit(context)
File “/opt/ros/dashing/lib/python3.6/site-packages/launch/action.py”, line 59, in visit
return self.execute(context)
File “/opt/ros/dashing/lib/python3.6/site-packages/launch/actions/opaque_function.py”, line 75, in execute
return self.__function(context, *self.__args, **self.__kwargs)
File “/opt/ros/dashing/lib/python3.6/site-packages/launch/actions/execute_process.py”, line 275, in __on_signal_process_event
raise RuntimeError(‘Signal event received before subprocess transport available.’)
RuntimeError: Signal event received before subprocess transport available.
[robot_state_publisher-1] Initialize urdf model from file: /home/ubuntu/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_waffle.urdf
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link base_link had 7 children
[robot_state_publisher-1] Link camera_link had 2 children
[robot_state_publisher-1] Link camera_depth_frame had 1 children
[robot_state_publisher-1] Link camera_depth_optical_frame had 0 children
[robot_state_publisher-1] Link camera_rgb_frame had 1 children
[robot_state_publisher-1] Link camera_rgb_optical_frame had 0 children
[robot_state_publisher-1] Link caster_back_left_link had 0 children
[robot_state_publisher-1] Link caster_back_right_link had 0 children
[robot_state_publisher-1] Link imu_link had 0 children
[robot_state_publisher-1] Link base_scan had 0 children
[robot_state_publisher-1] Link wheel_left_link had 0 children
[robot_state_publisher-1] Link wheel_right_link had 0 children
[robot_state_publisher-1] got segment base_footprint
[robot_state_publisher-1] got segment base_link
[robot_state_publisher-1] got segment base_scan
[robot_state_publisher-1] got segment camera_depth_frame
[robot_state_publisher-1] got segment camera_depth_optical_frame
[robot_state_publisher-1] got segment camera_link
[robot_state_publisher-1] got segment camera_rgb_frame
[robot_state_publisher-1] got segment camera_rgb_optical_frame
[robot_state_publisher-1] got segment caster_back_left_link
[robot_state_publisher-1] got segment caster_back_right_link
[robot_state_publisher-1] got segment imu_link
[robot_state_publisher-1] got segment wheel_left_link
[robot_state_publisher-1] got segment wheel_right_link
[robot_state_publisher-1] Adding fixed segment from base_footprint to base_link
[robot_state_publisher-1] Adding fixed segment from base_link to camera_link
[robot_state_publisher-1] Adding fixed segment from camera_link to camera_depth_frame
[robot_state_publisher-1] Adding fixed segment from camera_depth_frame to camera_depth_optical_frame
[robot_state_publisher-1] Adding fixed segment from camera_link to camera_rgb_frame
[robot_state_publisher-1] Adding fixed segment from camera_rgb_frame to camera_rgb_optical_frame
[robot_state_publisher-1] Adding fixed segment from base_link to caster_back_left_link
[robot_state_publisher-1] Adding fixed segment from base_link to caster_back_right_link
[robot_state_publisher-1] Adding fixed segment from base_link to imu_link
[robot_state_publisher-1] Adding fixed segment from base_link to base_scan
[robot_state_publisher-1] Adding moving segment from base_link to wheel_left_link
[robot_state_publisher-1] Adding moving segment from base_link to wheel_right_link
[ERROR] [robot_state_publisher-1]: process[robot_state_publisher-1] failed to terminate ‘5’ seconds after receiving ‘SIGINT’, escalating to ‘SIGTERM’
[INFO] [robot_state_publisher-1]: sending signal ‘SIGTERM’ to process[robot_state_publisher-1]
[ERROR] [robot_state_publisher-1]: process has died [pid 17894, exit code -15, cmd ‘/opt/ros/dashing/lib/robot_state_publisher/robot_state_publisher /home/ubuntu/turtlebot3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_waffle.urdf __node:=robot_state_publisher __params:=/tmp/launch_params_0_05q304’].

I ran the bringup in dashing and followed the turtlebot manual.

**Comment by sunghowoo** [comment]
@kimjunho654 Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
