### ISSUE TITLE
TurtleBot3 Waffle Pi IMU initial bias

### ISSUE THREAD

**Issue by LVJ047** [ROBOTIS-GIT/turtlebot3#907]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [1.1.0]
    - Firmware version: [1.2.3]

7. Specify the commands or instructions to reproduce the issue.

    - rostopic echo /imu

8. Copy and Paste the error messages on terminal.

![image](https://user-images.githubusercontent.com/48725411/190475498-2f85e05f-6f15-4b06-ba88-acc43de2bf51.png)
![image](https://user-images.githubusercontent.com/48725411/190475846-be46324e-934c-4b30-9f6b-321d14e698f4.png)

9. Please describe the issue in detail.

    - I am currently performing static test on turtlebot3, which shows the bias as indicated in the images attached. How must this bias be removed? Does the IMU need calibration? If yes, could you provide the procedure to do the same?
    - Also does the values for the following factors be changed? If yes, how must these be calculated?
![image](https://user-images.githubusercontent.com/48725411/190477272-f7cf88af-1334-491b-bded-a33fca2d6932.png)
    - Finally, does the covariance matrix for the IMU be changed? If yes, how to determine the covariance value for the sensor?

**Comment by sunghowoo** [comment]
@LVJ047 Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. The bias in the IMU readings is a common issue, especially during static tests, and can often be corrected through calibration. The IMU configuration you're referring to was set up a long time ago, and unfortunately, we don't have detailed records to trace it easily. We apologize for the limited assistance we can provide on this matter. It might be more appropriate to direct your question to IMU-specific communities or forums, where you can get more targeted guidance. Thank you for your understanding.
