### ISSUE TITLE
https://emanual.robotis.com/docs/en/platform/turtlebot3/sbc_setup/  BAD tutorial

### ISSUE THREAD

**Issue by kennydedavion** [ROBOTIS-GIT/turtlebot3#909]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [x] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [x] etc (http://www.robotis.com/service/download.php?no=1738 )

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - desktop
    - wlan
    - anything

8. Copy and Paste the error messages on terminal.

    - not found

9. Please describe the issue in detail.

    - after I found the website turtlebot3, which offered to download the iso axis and the following steps for everything to implement the tutorial, control and odometry of the robot. I downloaded the specified image for rpi3b, then burned the image with the Etcher program and started the sd card in rpi. after entering the login, which I had to look for in the context of the entire tutorial, because it is given in a way to skip. and after logging in I wanted to connect wifi, but ls didn't load it at all and installation of the wlan manager is not possible, due to the absence of a connection. and when, as a noob, I wanted to run destop for better functioning with the OS, but it is also not accessible on the image. it would be very appropriate, and I have already recommended this to other creators of similar tutorials. and I give this instruction to a completely ignorant person and let them follow the tutorial. try it yourself, and you will find out that the included etcher that you mentioned does not offer any partition settings and the like at all, let alone try to connect ros to the ip when the wifi is not detected at all. I was so happy to learn your tutorial on controlling turtlebot in rviz, because I was very interested in the possibilities of connecting a joystick for control. I have a remote control with a gyroscope, an evolveo that also has a keyboard and I use it to control my robotic dog. Unfortunately, I have to tell you that I failed you in your tutorial on implementing turtlebot in ros and rviz, because there are so many mistakes just at the beginning and I haven't even gotten anywhere yet. more success

**Comment by sunghowoo** [comment]
@kennydedavion Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
