### ISSUE TITLE
Problem with extracting opencr_update.tar.bz2

### ISSUE THREAD

**Issue by Mr360p** [ROBOTIS-GIT/turtlebot3#915]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [x] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - tar -xjf ./opencr_update.tar.bz2

8. Copy and Paste the error messages on terminal.

    - bzip2: (stdin) is not a bzip2 file.
    - tar: Child returned status 2
    - tar: Error is not recoverable: exiting now

9. Please describe the issue in detail.

    - I followed the instruction about OpenCR setup in Robotis e-manual. After downloading opencr update file, I can't extract it, with the mentioned error. I tried with previous versions, 0.2.0 faced the same issue but the 0.1.0 showed no error. When I run "head" command for three versions it show a lot of nonsense characters.

**Comment by ROBOTIS-Will** [comment]
Hi @Mr360p 
Thanks for reporting the issue.
Please try with the command below without the `j` option.
Thank you.
```
$ tar -xf ./opencr_update.tar.bz2
```

**Comment by sunghowoo** [comment]
@Mr360p this issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
