### ISSUE TITLE
Bringup getting stuck

### ISSUE THREAD

**Issue by amelia413** [ROBOTIS-GIT/turtlebot3#917]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [x] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    [INFO] [1667931680.847630, 0.000000]: Connecting to /dev/ttyACM0 at 115200 baud

9. Please describe the issue in detail.
  I've checked the USB connection and the battery is full as well, but the bringup is getting stuck at this point.
    
![image](https://user-images.githubusercontent.com/97603446/200643416-ec3ed42f-ad82-4b95-944f-c67052e5b289.png)

**Comment by yun-goon** [comment]
Hi @amelia413 
If the Arduino OpenCR package version is not the latest, you may encounter port errors. Please ensure you update the OpenCR package to the latest version and refer to the manual to reconfigure the settings. Thank you.

**Comment by sunghowoo** [comment]
This issue will be closed due to prolonged inactivity. If the issue persists, feel free to reopen it.
