### ISSUE TITLE
Turtlebot3 Waffle Pi with Manipulator Bringup failure

### ISSUE THREAD

**Issue by LukasNieland** [ROBOTIS-GIT/turtlebot3#919]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [X ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [X ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [X ] Raspberry Pi 4 4GB
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [X ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [X ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - when trying the ros2 launch turtlebot_manipulation_bringup hardware.launch.py there there is a substitution error.

8. Copy and Paste the error messages on terminal.

    - ![Screenshot from 2022-11-15 11-21-15](https://user-images.githubusercontent.com/43176306/201897581-ebe48723-1009-4037-b3e9-188e0ef60dd5.png)

9. Please describe the issue in detail.

    - I have tried to use the turtlebot3 with the open manipulator for month now and no version of ROS seems to work. ROS2 Foxy has a full instruction in the manual so I chose this one after trying noetic and melodic, as kinetic does not work with the rasp 4. Everything seemed fine, the normal bringup for the turtlebot and the teleop work, the catkin build runs through without errors and then when I try to bringup the manipulator there is the substition error and I can not find anything to fix it. Please Help :D It

**Comment by sunghowoo** [comment]
@LukasNieland This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it. https://github.com/ROBOTIS-GIT/turtlebot3_manipulation/tree/humble
