### ISSUE TITLE
Dynamixel XL430 seems to stop working properly and stops after a while

### ISSUE THREAD

**Issue by elimas9** [ROBOTIS-GIT/turtlebot3#921]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [x] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [x] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [x] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [0.0.0]
    - Firmware version: [1.2.3]

7. Specify the commands or instructions to reproduce the issue.

    Dynamixel XL430 seems to stop working properly

8. Copy and Paste the error messages on terminal.

    Dynamixel XL430 seems to stop working properly

9. Please describe the issue in detail.

Hi,
we have recently experienced some problems with one of the two Dynamixel XL430 motors on the robot.
After almost half an hour of the navigation experiment, it seems that the performance of one of these motors (always the same one) deteriorates, and during some of these experiments, always the same motor, completely stops working.
We are not sure if it is an overheating issue or anything else. Do you have already experienced similar behaviour for this kind of motors?
To fix this problem, we are considering substituting this motor which causes us a problem. We are wondering if the following Dynamixel motor models are compatible with our turtlebot: 

- Dynamixel XD430 
- Dynamizel XM430
- Dynamixel AX-18A

or otherwise which types of Dynamixel motors you suggest to buy.
In case we change the type of motors, should we do any modifications to the launch files in the turtlebot3_bringup folder?

Thank you very much!

**Comment by sunghowoo** [comment]
@elimas9 We apologize for the delayed response and appreciate your patience. We have assembled a TF team dedicated to addressing issues related to TurtleBot3 and are actively working on providing solutions.

Please note that we do not support End-of-Life (EOL) ROS versions. Our current support is limited to ROS1 Noetic and ROS2 Humble. We kindly ask you to try the latest supported version. If the issue persists, feel free to resubmit it, and our team will address it promptly.

Additionally, if you experience recurring motor malfunctions, we recommend reaching out to the Robotis Forum for technical assistance. https://forum.robotis.com/tag/x-series
