### ISSUE TITLE
lds02 publishes no data on /scan topic

### ISSUE THREAD

**Issue by zIxxong2** [ROBOTIS-GIT/turtlebot3#927]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [x] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [x] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [x] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

 SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix:
 * /turtlebot3_lds/frame_id: base_scan

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (ld08_driver/ld08_driver)

ROS_MASTER_URI=http://192.168.133.5:11311

process[turtlebot3_core-1]: started with pid [26595]
process[turtlebot3_lds-2]: started with pid [26596]
process[turtlebot3_diagnostics-3]: started with pid [26597]
/dev/ttyUSB0    CP2102 USB to UART Bridge Controller
/dev/ttyACM0    OpenCR Virtual ComPort in FS Mode
FOUND LiDAR_LD08 @port :/dev/ttyUSB0
[INFO] [1671073196.947438]: ROS Serial Python Node
[INFO] [1671073197.196164]: Connecting to /dev/ttyACM0 at 115200 baud
[INFO] [1671073199.608390]: Requesting topics...
[INFO] [1671073199.676416]: Note: publish buffer size is 1024 bytes
[INFO] [1671073199.688765]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1671073199.709148]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1671073200.049892]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1671073200.108630]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1671073200.320196]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1671073200.336221]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1671073200.369372]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1671073200.420916]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1671073202.911555]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1671073202.969953]: Note: subscribe buffer size is 1024 bytes
[INFO] [1671073202.976273]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
[INFO] [1671073203.015123]: Setup subscriber on sound [turtlebot3_msgs/Sound]
[INFO] [1671073203.089976]: Setup subscriber on motor_power [std_msgs/Bool]
[INFO] [1671073203.122931]: Setup subscriber on reset [std_msgs/Empty]
[INFO] [1671073203.160020]: Setup TF on Odometry [odom]
[INFO] [1671073203.173653]: Setup TF on IMU [imu_link]
[INFO] [1671073203.183157]: Setup TF on MagneticField [mag_link]
[INFO] [1671073203.194733]: Setup TF on JointState [base_link]
[INFO] [1671073203.208026]: --------------------------
[INFO] [1671073203.222099]: Connected to OpenCR board!
[INFO] [1671073203.245832]: This core(v1.2.2) is compatible with TB3 Burger
[INFO] [1671073203.267397]: --------------------------
[INFO] [1671073203.279889]: Start Calibration of Gyro
[INFO] [1671073205.722135]: Calibration End

7. Specify the commands or instructions to reproduce the issue.

    - HERE

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.

turtlebot3 and everything was running fine in simulation stage and It can visualize the surroundings using rviz and read the data from the lds vis the scan topic in simulation (roslaunch turtlebot3_gazebo turtlebot3_world.launch).  
I can move turtlebot3 in real world 
However, even though the Lidar rotates just fine, there appears to be no data on the scan topic. when I put "rostopic echo /scan " in remote PC , it doesn't output anything 
so I cant make a map in real world .. 

 I already installed  LDS-02 driver on turtlebot3 (SBC) and set the timesync!!

**Comment by WeiShengAng** [comment]
Hi, may i ask how you solve the problem? Thank you.
