### ISSUE TITLE
Map -> Odom flips robot and odom

### ISSUE THREAD

**Issue by fnaser** [ROBOTIS-GIT/turtlebot3#93]
Up until the part of running slam / amcl it works fine, but as soon as a new tf map -> odom gets published the Turtlebot3 drives forward instead of backwards and backwards instead of forwards. Any idea how to solve this issue? (IMU and motors are mounted correctly.)

**Comment by routiful** [comment]
Hello :)

If it's not an excuse, would you show me Rviz screen when you get an error?
It will be help to me to solve your issue

Thanks
Darby

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while.
You can reopen this issue to show this issue to the users whenever.
Thanks. :)
