### ISSUE TITLE
Humble - nav2 params file has not updated with new server name

### ISSUE THREAD

**Issue by yegarti** [ROBOTIS-GIT/turtlebot3#934]
nav2 has  renamed "recoveries server" to "behavior server".
https://navigation.ros.org/configuration/packages/configuring-behavior-server.html
> Note: pre-Rolling/Humble this was the Recovery server, not behavior server.

Need to update the turtlebot nav2 params file with the new name.
for example:
https://github.com/ROBOTIS-GIT/turtlebot3/blob/humble-devel/turtlebot3_navigation2/param/waffle.yaml#L317

**Comment by GyuH13** [comment]
Thank you for your interest and advice.
We always strive to provide prompt updates to ensure the best quality in our products and resources.
The TurtleBot3 currently works well with the existing source and manual.
If a parameter name change becomes necessary, we will update it accordingly
