### ISSUE TITLE
Gazebo actors are not seen by sensor

### ISSUE THREAD

**Issue by laurafbec** [ROBOTIS-GIT/turtlebot3#936]
1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [ ] Waffle
    - [X] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [X] ROS2 Galaxy

3. Please describe the issue in detail.
Hello, when running turtlebot3 simulation actors from Gazebo are not detected by the sensor.
Can anyone help me to fix this issue?
Thanks in advance

**Comment by sunghowoo** [comment]
@laurafbec If actors in your TurtleBot3 Gazebo simulation are not detected by the sensor, it’s likely due to missing collision properties. Ensure the sensor plugin is correctly configured to detect all objects, and add a collision element to the actor's SDF or URDF file.
