### ISSUE TITLE
Error while using nav2

### ISSUE THREAD

**Issue by Prajwal-C10** [ROBOTIS-GIT/turtlebot3#945]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

 
Waffle

  

2. Which ROS is working with TurtleBot3?

   ROS2 Humble Hawsbill

3. Which OS you installed on Remote PC?

 Ubuntu 22.04.2 LTS

4. Specify the commands or instructions to reproduce the issue.
ros2 launch turtlebot3_navigation2 navigation2.launch.py use_sim_time:=True map:=maps/my_map.yaml 

5 Copy and Paste the error messages on terminal.

    [INFO] [launch]: All log files can be found below /home/prajwal/.ros/log/2023-04-04-03-34-39-244466-mera-laptop-4992
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): while parsing a block mapping
  in "/opt/ros/humble/share/turtlebot3_navigation2/param/waffle.yaml", line 2, column 3
expected <block end>, but found '<block mapping start>'
  in "/opt/ros/humble/share/turtlebot3_navigation2/param/waffle.yaml", line 31, column 5

**Comment by GyuH13** [comment]
Hi @Prajwal-C10 
Based on the error message, it seems there might be a syntax or indentation error in the YAML file. Did you make any modifications to the YAML file?
If not, please try reinstalling the TurtleBot package. I also recommend installing it by building from source.
