### ISSUE TITLE
Opposite orientation with the 2D pose estimate

### ISSUE THREAD

**Issue by 943230714** [ROBOTIS-GIT/turtlebot3#95]
After I create a map, I want to test the navigation part. But there is a obstacle that the orientation is opposite. Then when I set up the goal position, whole process is wrong.

**Comment by routiful** [comment]
Hello :)

Can you show me Rviz screen when you get an error??
That helps me to find solution for you.

Thanks
Darby

**Comment by 943230714** [comment]
Oh,I found the error that the wheel had fixed the wrong side yesterday.

**Comment by routiful** [comment]
Great. If you have any problems, please feel free to ask to me :)
