### ISSUE TITLE
I encounter the error while running the command. [WARN] [1685504198.228856]: Failed to get param: timeout expired

### ISSUE THREAD

**Issue by me-anep** [ROBOTIS-GIT/turtlebot3#962]
1. Which TurtleBot3 platform do you use?
    - Burger

2. Which ROS is working with TurtleBot3?
    - ROS 1 Kinetic

3. Which SBC(Single Board Computer) is working on TurtleBot3?
    - Raspberry Pi 3B+

4. Which OS you installed on SBC?
    - Raspbian distributed by ROBOTIS

5. Which OS you installed on Remote PC?
    - Ubuntu 16.04 LTS (Xenial Xerus)

6. Specify the software and firmware version(Can be found from Bringup messages)
    - I don't know how to find this info

7. Specify the commands or instructions to reproduce the issue.
    - $roslaunch turtlebot3_bringup trutlebot3_robot.launch

8. Copy and Paste the error messages on terminal.
    - [WARN] [1685252790.095034]: Failed to get param: timeout expired

9. Please describe the issue in detail.

    - I encounter this error even after I reboot OpenCR it still happen.

**Comment by me-anep** [comment]
![prob](https://github.com/ROBOTIS-GIT/turtlebot3/assets/135087946/bf689140-1034-4d25-8ba4-915eefa797ce)

**Comment by AnhHazz** [comment]
Maybe this caused by time, try to sync time between two device 
```
$ sudo apt-get install ntpdate
$ sudo ntpdate ntp.ubuntu.com
```
and remember to `export TURTLEBOT3_MODEL=burger`

**Comment by sunghowoo** [comment]
@me-anep Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
