### ISSUE TITLE
[help needed] Unable to Identify Contribution Opportunities 

### ISSUE THREAD

**Issue by SANTHOSH-MAMIDISETTI** [ROBOTIS-GIT/turtlebot3#964]
hello ,
I would love contributing to opensource and I am planning to build my career full time in robotics . I would like to contribute to the this repository, but I have noticed that the available information is predominantly  issues which are years old or comprises questions from other users. I am seeking guidance in finding an issue that I can actively work on.  @robotpilot   @kijongGil @HPaper

**Comment by sunghowoo** [comment]
@SANTHOSH-MAMIDISETTI Thank you for your interest in contributing to open source and for your enthusiasm in building a career in robotics. We genuinely appreciate your offer to contribute to this repository.

However, as of 2022, we have significantly reduced our active management of this open platform. While we are in the process of forming an open-source TF team to handle outstanding issues, this repository is not currently a priority for us. Given these circumstances, we may not be able to provide the level of support and collaboration necessary for meaningful contributions at this time.

We recommend exploring other actively maintained robotics projects or repositories where your efforts can have a more immediate and impactful contribution. Your passion and initiative are commendable, and we encourage you to continue pursuing open source opportunities within the robotics community. Thank you again for your understanding and interest.
