### ISSUE TITLE
After launching amcl I'm getting the COSTMAP2D ROS 

### ISSUE THREAD

**Issue by LOKAKSHAI** [ROBOTIS-GIT/turtlebot3#971]
[ WARN] [1689676793.565301391]: Costmap2DROS transform timeout. Current time: 1689676793.5653, global_pose stamp: 0.0000, tolerance: 0.5000

**Comment by sunghowoo** [comment]
@LOKAKSHAI Thank you for your interest and for reaching out. We kindly ask that you follow the issue template format when submitting your question to ensure clarity and efficiency in addressing it. Additionally, please test the issue using the latest supported version. If the problem persists, feel free to reopen the issue with the required details. Thank you for your understanding
