### ISSUE TITLE
issue connecting to opencr board from jetson nano

### ISSUE THREAD

**Issue by qTp-METEOR** [ROBOTIS-GIT/turtlebot3#974]
1. Which TurtleBot3 platform do you use?

    - [V ] Burger

2. Which ROS is working with TurtleBot3?

    - [ V] ROS 1 Melodic Morenia

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [V ] etc (Please specify your SBC here)
    - Jetson nano

4. Which OS you installed on SBC?

    - [ V] etc (Please specify your OS here)
    - the recommended jetson default image which is a version of ubuntu 18.04

5. Which OS you installed on Remote PC?

    - [ V] Ubuntu 18.04 LTS (Bionic Beaver)

6. Specify the software and firmware version(Can be found from Bringup messages)

didnt get to bringup because i cant connect to the opencr board

7. Specify the commands or instructions to reproduce the issue.

i am unable to find /dev/ttyUSB0 or /dev/ttyACM0 which needs to be used to setup the opencr in the jetson tutorial

8. Copy and Paste the error messages on terminal.

No error message but this is what i do find when doing "ls /dev/tty*"

tty      tty18    tty28    tty38    tty48    tty58    ttyp0    ttypb
tty0     tty19    tty29    tty39    tty49    tty59    ttyp1    ttypc
tty1     tty2     tty3     tty4     tty5     tty6     ttyp2    ttypd
tty10    tty20    tty30    tty40    tty50    tty60    ttyp3    ttype
tty11    tty21    tty31    tty41    tty51    tty61    ttyp4    ttypf
tty12    tty22    tty32    tty42    tty52    tty62    ttyp5    ttyS0
tty13    tty23    tty33    tty43    tty53    tty63    ttyp6    ttyS1
tty14    tty24    tty34    tty44    tty54    tty7     ttyp7    ttyS2
tty15    tty25    tty35    tty45    tty55    tty8     ttyp8    ttyS3
tty16    tty26    tty36    tty46    tty56    tty9     ttyp9    ttyTHS1
tty17    tty27    tty37    tty47    tty57    ttyGS0   ttypa    ttyTHS2

9. Please describe the issue in detail.

dont have much more to add. maybe its worth noting that the arduino lights are on and i disconect the usb from the jetson the arduino lights turn off so i dont think that the physical connection is the issue

**Comment by sunghowoo** [comment]
@qTp-METEOR Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
