### ISSUE TITLE
Cannot move robot in Turtlebot3 Gazebo simulations

### ISSUE THREAD

**Issue by saadi-tech** [ROBOTIS-GIT/turtlebot3#986]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger
    - [Yes] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [ ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [Yes] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [ ] Raspberry Pi 4
    - [ Only simulation ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [ ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [Yes] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - After setting the proper env variables,
    - ros2 launch turtlebot3_gazebo empty_world.launch.py 
    - But it does not launch the robot simulation properly. I cannot see any new published topics like /scan, /imu etc. The robot also doest not move while using keyboard_teleop (the commands are being sent to /cmd_Vel, but their is no subscriber).

8. Copy and Paste the error messages on terminal.

    - [robot_state_publisher-4] [WARN] [1695018012.582064766] [robot_state_publisher]: No robot_description parameter, but command-line argument available.  Assuming argument is name of URDF file.  This backwards compatibility fallback will be removed in the future.
    - I removed this warning by using:
    parameters=[{'use_sim_time': use_sim_time,
                         'robot_description': Command(['cat ', urdf])}],
                         
       in robot_state_publisher.launch.py, now the warning is gone. But the robot does not work. I do not see any errors on the terminal or Gazebo logs.

9. Please describe the issue in detail.

    - I want to launch turtlebot3 and move it around in Gazebo using teleop. But after setting everything according to the official guide, it still does not work. When I launch this robot 'waffle', it does not start topics like /odom, /scan etc. I try to move it using keyboard_teleop, but again it doest not work. The commands are sent into the /cmd_vel correctly, but there is no subscriber to this topic. 
   First, it was showing a warning 'No robot_description parameter'. So I thought it could be the problem, so I changed the robot_state_publisher file. But again it does not start the required topics and the robot does not move. I do not see any error on Gazebo terminal or gazebo logs.
   Please help!!!!

**Comment by sunghowoo** [comment]
@saadi-tech Apologies for the delayed response. We have assembled a TF team to address TurtleBot3 issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
