### ISSUE TITLE
Need LDS_01 lidars config file(.lua file)

### ISSUE THREAD

**Issue by Rajatsurya** [ROBOTIS-GIT/turtlebot3#998]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ ] Burger

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Noetic Ninjemys

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Raspberry Pi 4

4. Which OS you installed on SBC?

    - [ ] Ubuntu MATE (16.04/18.04/20.04)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 20.04 LTS (Focal Fossa)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

9. Please describe the issue in detail.

    - I am trying to autonomously navigate the turtle bot by using cartographer in order to do this I need the config file of LDS_01 lidar (.lua file) this repo gives the config file for LDS_02 lidar sensor (turtlebot3_lds_2d.lua - this file is present in turtlebot3_slam/config folder) can you please provide the config file of LDS_01 or at least tell me what to change in the LDS_02 config file so that cartographer works properly on the turtle bot which has the LDS_01 sensor

**Comment by sunghowoo** [comment]
@Rajatsurya Apologies for the delayed response. Please refer to GYUH13's answer for initial guidance. This issue will be closed due to prolonged inactivity. If the problem persists, feel free to reopen it, and we will address it promptly. Thank you for your understanding!
